initial commit
eastgenomics/eris pull request #1
Opened 2022-06-01 14:42 UTC by Jay-Miles

Added draft script to define database models in Django

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eris/1)

2022-06-01 14:42 UTC, pep8speaks commented
Hello @Jay-Miles! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/models.py`](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py):

> [Line 18:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L18): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 18:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L18): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 20:11](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L20): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 20:64](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L20): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 20:66](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L20): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 35:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L35): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 35:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L35): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 44:60](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L44): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 44:62](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L44): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 53:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L53): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 53:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L53): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 57:19](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L57): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 57:21](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L57): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 66:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 66:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 72:72](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 72:74](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L72): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 86:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L86): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 86:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L86): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 108:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L108): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 108:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L108): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 115:72](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L115): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 115:74](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L115): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 126:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L126): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 126:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L126): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 135:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L135): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 135:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L135): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 150:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L150): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 150:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L150): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 152:56](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L152): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 152:58](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L152): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 162:38](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L162): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 162:40](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L162): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 164:47](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L164): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 1 [...]

2022-06-01 15:12 UTC, Yu-jinKim requested changes
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 10 unresolved discussions (waiting on @Jay-Miles)

___
*[`src/models.py` line 15 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3Umy-yAmO4FYokST_d:-N3Umy-yAmO4FYokST_e:b-wfaj2v) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L15)):*
> ```Python
> 
> 
> class ClinicalIndication(models.Model):
> ```

i don't remember the behaviour of django naming of the database table but to get ahead of that you can use this: https://github.com/eastgenomics/panel_palace/blob/main/panel_database/models.py#L15
___
*[`src/models.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UifWg0W1Wc1JAtiw8:-N3UifWg0W1Wc1JAtiw9:b553viw) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L18)):*
> ```Python
>     """ Defines a single clinical indication """
> 
>     id = models.AutoField(primary_key = True)
> ```

you don't need to specify id Autofield for the primary key https://github.com/eastgenomics/panel_palace/blob/main/panel_database/models.py#L9
___
*[`src/models.py` line 40 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3Ukpm1Dn9VWPf4rrBy:-N3Ukpm1Dn9VWPf4rrBz:b9zkmgv) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L40)):*
> ```Python
>         ClinicalIndication,
>         verbose_name='Clinical indication',
>         on_delete=models.CASCADE)
> ```

do we want to delete the ci when the source is deleted?
___
*[`src/models.py` line 44 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UjoWB-laMzqPveQCz:-N3UjoWB-laMzqPveQD-:bgorfhb) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L44)):*
> ```Python
>     source = models.TextField(verbose_name='Source name')
> 
>     date = models.CharField(verbose_name='Date', max_length = 10)
> ```

there is a DateField in Django i believe unless we want a timestamp?
___
*[`src/models.py` line 77 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UlfmF7Mfv64iuaiOc:-N3UlfmF7Mfv64iuaiOd:bs0n3ah) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L77)):*
> ```Python
>         ReferenceGenome,
>         verbose_name='Reference genome ID',
>         on_delete=models.CASCADE)
> ```

we definitely don't want to delete the reference genome when the panel is deleted
___
*[`src/models.py` line 91 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UnLbWCatr8gfa-8T6:-N3UnLbX29dW4ut5N-dN:b2nnt3u) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L91)):*
> ```Python
>         ClinicalIndication,
>         verbose_name='Clinical indication',
>         on_delete=models.CASCADE)
> ```

no cascade
___
*[`src/models.py` line 96 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UnOig0xB8actWaS35:-N3UnOig0xB8actWaS36:b2nnt3u) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L96)):*
> ```Python
>         Panel,
>         verbose_name='Panel',
>         on_delete=models.CASCADE)
> ```

no cascade
___
*[`src/models.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3Um_mGBjxV-EoLORt7:-N3Um_mGBjxV-EoLORt8:baxaa9z) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L115)):*
> ```Python
>         on_delete=models.CASCADE)
> 
>     start_date = models.CharField(verbose_name='Start date', max_length = 10)
> ```

is that a full date?
___
*[`src/models.py` line 117 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UmcRTC5nAON9eDXNF:-N3UmcRUBJ_62-H1SjaZ:b-df3mee) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L117)):*
> ```Python
>     start_date = models.CharField(verbose_name='Start date', max_length = 10)
> 
>     end_date = models.BooleanField(verbose_name='Currently in use')
> ```

full date? Matt might have made a mistake in the schema, i don't believe we want that to be a boolean
___
*[`src/models.py` line 126 at r1](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N3UnbQPC0IxuSGCNxwL:-N3UnbQPC0IxuSGCNxwM:bct1d70) ([raw file](https://github.com/eastgenomics/panel_requests/blob/77da28ece52a4e6e28ba8ef8f8de26b893538f55/src/models.py#L126)):*
> ```Python
>     """ Defines a single HGNC ID (for a gene) """
> 
>     id = models.AutoField(primary_key = True)
> ```

would that be 1100 for BRCA1 for example?


<!-- Sent from Reviewable.io -->

2022-06-06 10:48 UTC, Jay-Miles commented
I've made the requested changes

2022-06-09 08:18 UTC, Yu-jinKim requested changes
> Reviewed 1 of 1 files at r3, 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 13 unresolved discussions (waiting on @Jay-Miles)

___
*[`requirements.txt` line 1 at r4](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N46Ws9WAGo6NLCHC0yh:-N46Ws9WAGo6NLCHC0yi:b-m2z1o) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8569d11b0ba0200b1100b8626c8bd9ee93246939/requirements.txt#L1)):*
> ```help
> panelapp
> ```

you should specify a version with the packages like so: `panelapp==1.0.0`
___
*[`panel_requests/panel_requests/settings.py` line 83 at r4](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N46X4Md2hV_6UfEZu58:-N46X4Md2hV_6UfEZu59:bty0dqc) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8569d11b0ba0200b1100b8626c8bd9ee93246939/panel_requests/panel_requests/settings.py#L83)):*
> ```Python
> DATABASES = {
>     'default': {
>         'ENGINE': 'django.db.backends.mysql',
> ```

does django not have mariadb support?
___
*[`requests_app/models.py` line 24 at r4](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N46XIJ30iZCsEjtDAJv:-N46XIJ30iZCsEjtDAJw:b-748p35) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8569d11b0ba0200b1100b8626c8bd9ee93246939/requests_app/models.py#L24)):*
> ```Python
>         db_table = 'clinical_indication'
>         verbose_name_plural = 'clinical_indications'
>         indexes = [models.Index(fields=[
> ```

you don't have to specify every column in the table for the indexes, just the ones you think are going to be queried often


<!-- Sent from Reviewable.io -->

2022-08-04 10:24 UTC, Yu-jinKim requested changes
> Reviewed 5 of 6 files at r5, 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 26 unresolved discussions (waiting on @Jay-Miles)

___
*[`panel_requests/README.md` line 1 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8bxFj3AgouLMnnEnz9:-N8bxFj3AgouLMnnEnzA:b-8joxht) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/README.md#L1)):*
> ```Markdown
> # panel_requests
> ```

i recommend starting to write stuff down so that you don't forget the first commands that you started working on
___
*[`panel_requests/requirements.txt` line 1 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8bxP8E1mmy5afhpqvX:-N8bxP8E1mmy5afhpqvY:b-eud0oc) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requirements.txt#L1)):*
> ```help
> datetime
> ```

you need versions, use `pip freeze` to get the packages names and the versions
___
*[`panel_requests/requests_app/models.py` line 122 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cAZmw6TIxHIAO1RSn:-N8cAZmw6TIxHIAO1RSo:b-xb68j1) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/models.py#L122)):*
> ```Python
>         on_delete = models.PROTECT,)
> 
>     start_date = models.DateField(verbose_name = 'Start date')
> ```

don't we want the null=True for the start date as well?
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 664 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cEYGy1PQ30lb2WlT5:-N8cEYGy1PQ30lb2WlT6:b-9s87mj) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L664)):*
> ```Python
>                 ref_genome)
> 
>             # if that CI currently has no panels, create a blank form
> ```

do we want to do that? why not just create nothing and inform the user?
also if a CI has no panels isn't that a problem?
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 718 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cFIWh0QIm1SFt1CSu:-N8cFIWh0QIm1SFt1CSv:bpxl3wo) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L718)):*
> ```Python
> 
>         else:
>             print("Arguments must be specified in this order: " \
> ```

this is not necessarily the issue that happens here. If an argument is missing, it would trigger this error message which is not 100% accurate
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 72 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cG1nYBQupip6w5-Ff:-N8cG1nYBQupip6w5-Fg:b-os5nrp) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L72)):*
you should use the datetime python package to format your dates

```
>>> from datetime import datetime
>>> time="220725"
>>> date_object = datetime.strptime(time, "%y%m%d")
>>> datetime.strftime(date_object, "%Y-%m-%d")
'2022-07-25'
```

Reference for formatting datetime: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 98 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cI9is3raZ08UyB-CA:-N8cI9is3raZ08UyB-CB:b970f9l) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L98)):*
> ```Python
>                 # add any individual hgnc ids to a separate list
> 
>                 if (element) and (element[:4].upper() == 'HGNC'):
> ```

no need for parentheses around the first element
you can use .startswith() --> `element.upper().startswith("HGNC")`
also i would add `:` to the HGNC just in case
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 116 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cI_LgBZ7CE9FQx9Kp:-N8cI_LgBZ7CE9FQx9Kq:b4q79eh) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L116)):*
> ```Python
>                     if len(panel_records) == 0:
> 
>                         print('No record has panelapp ID {}'.format(element))
> ```

Maybe an assert would be more appropriate here? to stop the code and show the user that there is an issue
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 127 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cIwzL9pPw1ujlYy0e:-N8cIwzL9pPw1ujlYy0f:bdl18pk) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L127)):*
> ```Python
> 
>                         for record in panel_records:
>                             if float(record['panel_version']) > float(max_v):
> ```

use the packaging package for version comparison
Example in dias: https://github.com/eastgenomics/dias_batch_running/blob/5a0bc23230401d0f8eab1dd711ec90c144844697/general_functions.py#L614
Docs: https://packaging.pypa.io/en/latest/version.html
___
*[`panel_requests/requests_app/management/commands/seed.py` line 75 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cKg5o5xmBhiyV5IBf:-N8cKg5o5xmBhiyV5IBg:b6lruhd) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L75)):*
> ```Python
> 
>         # 'source' arg is always required, and has 3 valid values
>         parser.add_argument(
> ```

i wonder if subparsers would be useful here for ease of use and scalability
Example in dias: https://github.com/eastgenomics/dias_batch_running/blob/master/dias.py#L20

It would allow you to isolate commands and argument for test directory, panels and requests form
___
*[`panel_requests/requests_app/management/commands/seed.py` line 143 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cLO1P8sBWzDe_WsJN:-N8cLO1P8sBWzDe_WsJO:b6qiflc) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L143)):*
> ```Python
>         # parse out data on the panel and its genes and regions
> 
>         if panel_data:
> ```

an assert would be better as if data is not retrieved it means that there is an issue
at least an else to indicate if a panelapp panel was not retrieved properly
___
*[`panel_requests/requests_app/management/commands/seed.py` line 221 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cMOSo7KHaI8xIDU81:-N8cMOSo7KHaI8xIDU82:bhhaxbk) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L221)):*
> ```Python
>                     print('Parsing PanelApp data for all panels...')
>                     parsed_data = self.parse_all_pa_panels()
>                     print('Data parsing completed.')
> ```

I think i'd rather have those prints inside the functions as things can go wrong inside the function and these can be misleading
___
*[`requests_app/management/commands/seed.py` line 2 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cNS01Crfn4-2LVIob:-N8cNS01Crfn4-2LVIoc:bdy5nnk) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d [...]

2022-08-04 15:35 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 40 of 43 files reviewed, 26 unresolved discussions (waiting on @Jay-Miles and @Yu-jinKim)

___
*[`requirements.txt` line 1 at r4](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N46Ws9WAGo6NLCHC0yh:-N8dFc_85xgYfZYoLukL:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8569d11b0ba0200b1100b8626c8bd9ee93246939/requirements.txt#L1)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you should specify a version with the packages like so: `panelapp==1.0.0`
</blockquote></details>

Done.
___
*[`panel_requests/requirements.txt` line 1 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8bxP8E1mmy5afhpqvX:-N8dFeki-8v1eCC_LjBd:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requirements.txt#L1)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you need versions, use `pip freeze` to get the packages names and the versions
</blockquote></details>

Done.
___
*[`panel_requests/panel_requests/settings.py` line 83 at r4](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N46X4Md2hV_6UfEZu58:-N8dFgtDDULg0txQz6_p:b-f6r7i5) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8569d11b0ba0200b1100b8626c8bd9ee93246939/panel_requests/panel_requests/settings.py#L83)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

does django not have mariadb support?
</blockquote></details>

It does, but you can't specifically tell it to use MariaDB because it uses the same backend as MySQL, you just have to install MariaDB and it uses it automatically. I don't know how this works if you also have MySQL installed and want to use that for a different project, the documentation is rather vague.
___
*[`panel_requests/requests_app/models.py` line 122 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cAZmw6TIxHIAO1RSn:-N8dGFNd9VdO-Keppolu:b-x1uwiy) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/models.py#L122)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

don't we want the null=True for the start date as well?
</blockquote></details>

I'd thought that any records in this table must have a start date by definition, because the record only gets created when the relevant CI-panel link comes into usage. So if the CI-panel link hasn't started to be used, a usage record for it wouldn't exist.
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 664 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cEYGy1PQ30lb2WlT5:-N8dH3wb9mvOIKiW4h5T:b-y0rn23) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L664)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do we want to do that? why not just create nothing and inform the user?
also if a CI has no panels isn't that a problem?
</blockquote></details>

Yes, it is a problem, but there are a number of CIs for which the associated panelapp panel is null - for example because the original target was something like 'relevant single gene' or 'relevant panel in panelapp', or because PA has decided that the panel is internal. 

So I think my thinking was that for those CIs, this would generate a blank form on which the user could add in the 'relevant' genes, and we could use that to create a panel for the CI.
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 718 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cFIWh0QIm1SFt1CSu:-N8dJ2XaBnkA2SyQxEi1:b-nja81p) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L718)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

this is not necessarily the issue that happens here. If an argument is missing, it would trigger this error message which is not 100% accurate
</blockquote></details>

Do you mean that the issue is whether or not the arguments are present, and not the order that they're given in?
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 72 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cG1nYBQupip6w5-Ff:-N8dJzlnCSSNTqTAAT7J:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L72)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you should use the datetime python package to format your dates

```
>>> from datetime import datetime
>>> time="220725"
>>> date_object = datetime.strptime(time, "%y%m%d")
>>> datetime.strftime(date_object, "%Y-%m-%d")
'2022-07-25'
```

Reference for formatting datetime: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 98 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cI9is3raZ08UyB-CA:-N8dKPmFEqocDSLRwgET:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L98)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

no need for parentheses around the first element
you can use .startswith() --> `element.upper().startswith("HGNC")`
also i would add `:` to the HGNC just in case
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 116 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cI_LgBZ7CE9FQx9Kp:-N8dKYt28rdhen5Z9eZN:byctn3w) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L116)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Maybe an assert would be more appropriate here? to stop the code and show the user that there is an issue
</blockquote></details>

This is the same issue as above of a CI having no panels - depends on how we want to deal with that.
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 127 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cIwzL9pPw1ujlYy0e:-N8dRoed4Q8KkjNahrPg:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/insert_ci.py#L127)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

use the packaging package for version comparison
Example in dias: https://github.com/eastgenomics/dias_batch_running/blob/5a0bc23230401d0f8eab1dd711ec90c144844697/general_functions.py#L614
Docs: https://packaging.pypa.io/en/latest/version.html
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/seed.py` line 143 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cLO1P8sBWzDe_WsJN:-N8dTDwK3xA9U_2AD-ZZ:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L143)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

an assert would be better as if data is not retrieved it means that there is an issue
at least an else to indicate if a panelapp panel was not retrieved properly
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/manageme [...]

2022-08-15 08:27 UTC, Yu-jinKim requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, 16 of 16 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 4 unresolved discussions (waiting on @Jay-Miles)

___
*[`panel_requests/requests_app/management/commands/create_form.py` line 718 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cFIWh0QIm1SFt1CSu:-N9VaEw_5e-PVPHUrzxZ:bw6wsso) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L718)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

Do you mean that the issue is whether or not the arguments are present, and not the order that they're given in?
</blockquote></details>

the issue is that it could be both so the message can be misleading
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 688 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9Va5zG4kf-EuQP2b1H:-N9Va5zG4kf-EuQP2b1I:b-69fzmo) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/create_form.py#L688)):*
> ```Python
>                 # write a blank form
> 
>                 filename = 'request_form_{}_{}_{}_{}_EMPTY.xlsx'.format(
> ```

which version of python are you using? Can you not use f-strings (Python 3.6 or above)?
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 551 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9VbE-y5Owjw_BvTIoA:-N9VbE-y5Owjw_BvTIoB:b36y771) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/insert_ci.py#L551)):*
> ```Python
>                 for match in matching_panels:
> 
>                     ci_panel, created = create_record_ci_panel(
> ```

i don't really see the advantage to having the `get_or_create` functions in their functions


<!-- Sent from Reviewable.io -->

2022-08-16 16:22 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 38 of 46 files reviewed, 4 unresolved discussions (waiting on @Jay-Miles and @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/create_form.py` line 718 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cFIWh0QIm1SFt1CSu:-N9bISMJ1oQU56sLPDax:b-jq1vot) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/create_form.py#L718)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

the issue is that it could be both so the message can be misleading
</blockquote></details>

Done. Updated to clarify.
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 688 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9Va5zG4kf-EuQP2b1H:-N9bHauTDnfA07aigw6z:b-qmbn1m) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/create_form.py#L688)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

which version of python are you using? Can you not use f-strings (Python 3.6 or above)?
</blockquote></details>

Done. brb, just going back over every script I've ever written to use this instead
___
*[`panel_requests/requests_app/management/commands/insert_ci.py` line 551 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9VbE-y5Owjw_BvTIoA:-N9bS_uk5koc-8BlVYVi:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/insert_ci.py#L551)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i don't really see the advantage to having the `get_or_create` functions in their functions
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-17 10:24 UTC, Yu-jinKim requested changes
> Reviewed 2 of 6 files at r12, 3 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 43 of 46 files reviewed, 4 unresolved discussions (waiting on @Jay-Miles and @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/create_form.py` line 36 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9fF4otDvkHpIKh2Ucj:-N9fF4otDvkHpIKh2Uck:bzigsw5) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/create_form.py#L36)):*
> ```Python
> from django.core.management.base import BaseCommand
> 
> from . import parse_pa as parse_pa
> ```

do you need to do the `as` ?
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 89 at r14](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9fGfUWCqVD4OGNHsuY:-N9fGfUWCqVD4OGNHsuZ:b-gvct6q) ([raw file](https://github.com/eastgenomics/panel_requests/blob/40e148e2d7c44ebae03f1ee53d32436a1d25ad0e/panel_requests/requests_app/management/commands/create_form.py#L89)):*
> ```Python
> 
>         parser.add_argument(
>             "hgnc_dump",
> ```

i think you're going to have to add how the hgnc dump is created and what columns are required in your readme


<!-- Sent from Reviewable.io -->

2022-08-17 13:07 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 39 of 47 files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/create_form.py` line 36 at r11](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9fF4otDvkHpIKh2Ucj:-N9fVW5pBTsWY84KktMn:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8752ac93f9a0d84387688d1bc1801b085d57e248/panel_requests/requests_app/management/commands/create_form.py#L36)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do you need to do the `as` ?
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/create_form.py` line 89 at r14](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N9fGfUWCqVD4OGNHsuY:-N9fuWWIB61n_fUAaiT2:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/40e148e2d7c44ebae03f1ee53d32436a1d25ad0e/panel_requests/requests_app/management/commands/create_form.py#L89)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i think you're going to have to add how the hgnc dump is created and what columns are required in your readme
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/seed.py` line 75 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cKg5o5xmBhiyV5IBf:-N9fbULfBox0qpjFHBop:b-80yt03) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L75)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i wonder if subparsers would be useful here for ease of use and scalability
Example in dias: https://github.com/eastgenomics/dias_batch_running/blob/master/dias.py#L20

It would allow you to isolate commands and argument for test directory, panels and requests form
</blockquote></details>

I'm not ignoring this recommendation! I'm just not familiar with subparsers so I'm dealing with everything else first. Will work on this once I've sorted the other issues/comments.


<!-- Sent from Reviewable.io -->

2022-08-23 14:36 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 39 of 47 files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/seed.py` line 75 at r6](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-N8cKg5o5xmBhiyV5IBf:-NAA7ZNTBIivGtxOKyXT:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/5593dcc09a8a67c5d8111a25480456f49716141a/panel_requests/requests_app/management/commands/seed.py#L75)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

I'm not ignoring this recommendation! I'm just not familiar with subparsers so I'm dealing with everything else first. Will work on this once I've sorted the other issues/comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 15:58 UTC, mattgarner requested changes
> Reviewed 5 of 6 files at r1, 5 of 20 files at r4, 10 of 18 files at r6, 1 of 2 files at r7, 16 of 16 files at r10, 1 of 4 files at r13, 3 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 42 of 47 files reviewed, 9 unresolved discussions (waiting on @Jay-Miles, @mattgarner, and @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFZ-ZB-cmC8-_cZgxc:-NAFZ-ZB-cmC8-_cZgxd:b-g5qsfe) (no related file):*
Could you check this over with a linter? 

pep8 bot seems quite angry :angry: 

___
___
*[`docs/pa_all_panel_objects.txt` line 1 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFQpH31D1ksC8UY3OX:-NAFQpH31D1ksC8UY3OY:bkpu10o) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/pa_all_panel_objects.txt#L1)):*
> ```help
> 399: Additional findings health related: id=399; version=0.114; signedoff=False; is_superpanel=False
> ```

Could this doc be given a version/date so that we know which pa we are referring to?



_Code quote:_
```help
3
```
___
*[`docs/pa_panel_entity_counts.txt` line 1 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFRLfEDyapMrwpQkWu:-NAFRLfF6htwyd7lFWJf:b-sff8w5) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/pa_panel_entity_counts.txt#L1)):*
> ```help
> Number of genes, regions and STRs in each PA panel
> ```

Versioning please



_Code quote:_
```help
N
```
___
*[`docs/panel_dump_90_current.txt` line 0 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFRdCa9xsVYci1Uqla:-NAFRdCb4NSWN7-rTeg6:b-ix9uo8) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/panel_dump_90_current.txt#L0)):*
Perhaps a readme for the files in this dir would be useful to describe what they are and/or are for
___
*[`panel_requests/README.md` line 46 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFTFaV8IYmU98ffTYw:-NAFTFaV8IYmU98ffTYx:b-xyming) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/panel_requests/README.md#L46)):*
> ```Markdown
> ```
> - This command retrieves data from a JSON file, inserts it into the appropriate database models, and links these to the appropriate panel data as specified within the test directory.
> - The JSON file should be created from the original test directory MS Excel file and take the following format:
> ```

How should the TD be converted to json?



_Code quote:_
```Markdown
The JSON file should be created from the original test directory MS Excel file and take the following format:
```


<!-- Sent from Reviewable.io -->

2022-08-25 13:10 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 32 of 47 files reviewed, 9 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFZ-ZB-cmC8-_cZgxc:-NAK31nw80w7Q00ZCFFz:b-406qms) (no related file):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you check this over with a linter? 

pep8 bot seems quite angry :angry: 
</blockquote></details>

Done. Except for the line continuation things, because what it wanted just seemed silly - although if PEP-8 needs to be appeased in its entirety I can try and find a workaround.

___
___
*[`docs/pa_all_panel_objects.txt` line 1 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFQpH31D1ksC8UY3OX:-NAK3T842N7qdSZHpt2B:btckr4c) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/pa_all_panel_objects.txt#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this doc be given a version/date so that we know which pa we are referring to?
</blockquote></details>

Done. (In the sense that I removed the docs because they were actually unnecessary). Added a line to the readme that points to the panelapp handbook instead.
___
*[`docs/pa_panel_entity_counts.txt` line 1 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFRLfEDyapMrwpQkWu:-NAK3fFE2P5Fh_a_6CUA:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/pa_panel_entity_counts.txt#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Versioning please
</blockquote></details>

Done.
___
*[`docs/panel_dump_90_current.txt` line  at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFRdCa9xsVYci1Uqla:-NAK3gOB4aDAoTwCmTKx:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/docs/panel_dump_90_current.txt#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps a readme for the files in this dir would be useful to describe what they are and/or are for
</blockquote></details>

Done.
___
*[`panel_requests/README.md` line 46 at r15](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFTFaV8IYmU98ffTYw:-NAK6o2qByDI4VwquY4P:b-x7ffv1) ([raw file](https://github.com/eastgenomics/panel_requests/blob/8d69e55f1153d973a7bbc36eb9df6c10e696c884/panel_requests/README.md#L46)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

How should the TD be converted to json?
</blockquote></details>

Done. Linked to test directory parser repo in the readme. 


<!-- Sent from Reviewable.io -->

2022-08-29 15:06 UTC, mattgarner requested changes
> Reviewed 1 of 8 files at r15, 14 of 14 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 7 unresolved discussions (waiting on @Jay-Miles and @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFZ-ZB-cmC8-_cZgxc:-NAe49KJ3TsII_niKCed:b2wchqu) (no related file):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

Done. Except for the line continuation things, because what it wanted just seemed silly - although if PEP-8 needs to be appeased in its entirety I can try and find a workaround.
</blockquote></details>

Looks much happier now. It's fine to break pep-8 if there's good reason to do so.

___
___
*[`panel_requests/requests_app/management/commands/parse_pa.py` line 22 at r16](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAe4rrK9fy-YCmoH5Sr:-NAe4rrLCYmWWBFvDMxO:b-yuof2x) ([raw file](https://github.com/eastgenomics/panel_requests/blob/c6129ebe3ad208add80ca5a533b57a198dc39600/panel_requests/requests_app/management/commands/parse_pa.py#L22)):*
> ```Python
> 
> 
> class Data:
> ```

Would this benefit from a more descriptive class name?



_Code quote:_
```Python
Data
```
___
*[`panel_requests/requests_app/management/commands/parse_pa.py` line 116 at r16](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAe5u563vy79MsHilLf:-NAe5u563vy79MsHilLg:b-9xi2o6) ([raw file](https://github.com/eastgenomics/panel_requests/blob/c6129ebe3ad208add80ca5a533b57a198dc39600/panel_requests/requests_app/management/commands/parse_pa.py#L116)):*
> ```Python
>                 gene_dict = {
>                     'transcript': gene['transcript'],
>                     'hgnc_id': gene['gene_data']['hgnc_id'][5:],
> ```

Do we want to strip the `HGNC:` part from the ID

This will depend if a complete HGNC ID looks like `HGNC:1` or `1`. Something to check in the docs perhaps.
If there's a strong reason to do this one way or the other which conflicts with the docs I'm happy to discuss



_Code quote:_
```Python
[5:]
```


<!-- Sent from Reviewable.io -->

2022-08-31 11:42 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 42 of 47 files reviewed, 7 unresolved discussions (waiting on @Jay-Miles, @mattgarner, and @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/parse_pa.py` line 22 at r16](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAe4rrK9fy-YCmoH5Sr:-NAnT7AT8GiPHF23inof:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/c6129ebe3ad208add80ca5a533b57a198dc39600/panel_requests/requests_app/management/commands/parse_pa.py#L22)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would this benefit from a more descriptive class name?
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/parse_pa.py` line 116 at r16](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAe5u563vy79MsHilLf:-NAnhRDh0fuBLhEmMUaB:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/c6129ebe3ad208add80ca5a533b57a198dc39600/panel_requests/requests_app/management/commands/parse_pa.py#L116)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do we want to strip the `HGNC:` part from the ID

This will depend if a complete HGNC ID looks like `HGNC:1` or `1`. Something to check in the docs perhaps.
If there's a strong reason to do this one way or the other which conflicts with the docs I'm happy to discuss
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 11:42 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 42 of 47 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

*[a discussion](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NAFZ-ZB-cmC8-_cZgxc:-NAnhVU7Ewo_5dX3X6w6:b-896fix) (no related file):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Looks much happier now. It's fine to break pep-8 if there's good reason to do so.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-09-22 08:55 UTC, mattgarner reviewed
> Reviewed 4 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: 46 of 47 files reviewed, 5 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2022-09-22 09:08 UTC, Yu-jinKim approved these changes
> Reviewed 1 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2022-10-07 13:31 UTC, Jay-Miles reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 6 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[`panel_requests/requests_app/management/commands/parse_form.py` line 143 at r18](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NDcSsiZ2Oa_I-7RiiaZ:-NDmd5aw57-0U1tXItF7:b-p30alq) ([raw file](https://github.com/eastgenomics/panel_requests/blob/298903d422470363aee6e083cdc52da29eeadcef/panel_requests/requests_app/management/commands/parse_form.py#L143)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is that something that we need to talk about ? I'm not sure i understand here
</blockquote></details>

Yeah I think this needs discussing further, I'm not sure what values the id and version fields should really hold for non-panelapp panels, if anything
___
*[`panel_requests/requests_app/management/commands/parse_form.py` line 175 at r18](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NDcT75g9SqE32I4Jvrg:-NDmbV6B5u4SFviCvdGm:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/298903d422470363aee6e083cdc52da29eeadcef/panel_requests/requests_app/management/commands/parse_form.py#L175)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could you assign row[1] to a variable? so that you can name what row[1] is, i assume it's the gene ?
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/parse_form.py` line 204 at r18](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NDcTLkb57_eaHZPQBZm:-NDmbWCn0TYaBzds85CH:b-896fix) ([raw file](https://github.com/eastgenomics/panel_requests/blob/298903d422470363aee6e083cdc52da29eeadcef/panel_requests/requests_app/management/commands/parse_form.py#L204)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

same here if you could assign row[1]
</blockquote></details>

Done.
___
*[`panel_requests/requests_app/management/commands/seed.py` line 125 at r18](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NDcTfoWEQSg8I_xWono:-NDmbtJC27bnCzLWlqrN:b-agwnmt) ([raw file](https://github.com/eastgenomics/panel_requests/blob/298903d422470363aee6e083cdc52da29eeadcef/panel_requests/requests_app/management/commands/seed.py#L125)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

shouldn't `parser` be called panel_data or something like that?
</blockquote></details>

I don't think so, 'parser' is an instance of the class described in parse_pa, which is the collection of functions to parse panel data rather than being the data itself. 'panel_data' is defined in the next few lines and is the actual panel data retrieved from panelapp.
___
*[`panel_requests/requests_app/management/commands/seed.py` line 185 at r18](https://reviewable.io/reviews/eastgenomics/panel_requests/1#-NDcTtyp8loEIxL_qzTk:-NDmcoOs-C2YtuFAiGzR:b-o2vm1b) ([raw file](https://github.com/eastgenomics/panel_requests/blob/298903d422470363aee6e083cdc52da29eeadcef/panel_requests/requests_app/management/commands/seed.py#L185)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

same here, wouldn't `form` be a more appropriate name?
</blockquote></details>

As above - this variable is an instance of the class containing the parsing functions.


<!-- Sent from Reviewable.io -->

2022-10-18 10:13 UTC, Yu-jinKim approved these changes
> Reviewed 14 of 14 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/panel_requests/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2022-11-30 13:24 UTC, Yu-jinKim requested changes
> Reviewed 22 of 22 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/1)* status: all files reviewed, 3 unresolved discussions (waiting on @Jay-Miles and @mattgarner)

___
*[`panel_requests/README.md` line 36 at r20](https://reviewable.io/reviews/eastgenomics/eris/1#-NI7fksg87jVM_Q564Oa:-NI7fksg87jVM_Q564Ob:bebhix3) ([raw file](https://github.com/eastgenomics/eris/blob/eb8b75a650c113cab6dfda2fadbe3cd2803a30ac/panel_requests/README.md#L36)):*
> ```Markdown
> ```
> - This command retrieves all current panels from the PanelApp API, parses the data, and inserts it into the appropriate database models.
> - It can be executed as-is and has no variable arguments.
> ```

dynamic might be more appropriate than variable
___
*[`panel_requests/requests_app/tests.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/1#-NI7gQTCDYdeNuc2t_xG:-NI7gQTCDYdeNuc2t_xH:b-jqjvu4) ([raw file](https://github.com/eastgenomics/eris/blob/eb8b75a650c113cab6dfda2fadbe3cd2803a30ac/panel_requests/requests_app/tests.py#L156)):*
> ```Python
> 
> 
> # class TestForm:
> ```

why not delete ?


<!-- Sent from Reviewable.io -->

2023-08-03 08:45 UTC, jethror1 commented
Closing as superseded by changes in https://github.com/eastgenomics/eris/pull/4

2023-08-03 08:45 UTC, closed without merging