more filter on gene submission
eastgenomics/eris pull request #38
Opened 2023-10-04 13:29 UTC by JasonLing95

- filter to only allow digit after HGNC:
- filter to return error if gene symbol already exist in db

relevant Jira ticket: https://cuhbioinformatics.atlassian.net/browse/IN-297?atlOrigin=eyJpIjoiMGFiOGNlODZlMDEzNDA5NmI0MDViMjI5YzllODJmNzciLCJwIjoiaiJ9

2023-10-04 13:29 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`web/forms.py`](https://github.com/eastgenomics/eris/blob/a63ed051c9d354a3fd7580294c0b4ca20126fe6d/web/forms.py):

> [Line 85:80](https://github.com/eastgenomics/eris/blob/a63ed051c9d354a3fd7580294c0b4ca20126fe6d/web/forms.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 87:9](https://github.com/eastgenomics/eris/blob/a63ed051c9d354a3fd7580294c0b4ca20126fe6d/web/forms.py#L87): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

2023-10-04 17:17 UTC, corbin-chris requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/38)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`web/forms.py` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eris/38#-NfvcoLaES5D7IyE3AUM:-NfvcoLaES5D7IyE3AUN:b-q8p5pg) ([raw file](https://github.com/eastgenomics/eris/blob/a63ed051c9d354a3fd7580294c0b4ca20126fe6d/web/forms.py#L66)):*
> ```Python
>             self.add_error("hgnc_id", "HGNC ID must start with 'HGNC:'")
> 
>         if not hgnc_id[5:].isdigit():
> ```

isdigit() also lets the user pass subscript and superscript: https://stackoverflow.com/questions/44891070/whats-the-difference-between-str-isdigit-isnumeric-and-isdecimal-in-pyth

Try using regex instead, 're.match', which will return a match object if things match, or None otherwise. The pattern ^[\d]+$ matches any number of digits 0-9 only, and the ^ at the start and $ at the end means the whole string must match be digits. 

https://regex101.com/ is a lifesaver for testing any regex stuff. You can put  ^[\d]+$ in the 'Regular expression' box and try it out against different targets in 'Test string'.



_Code snippet:_
```Python
import re

id_without_hgnc = hgnc_id[5:]
if not re.match(r'^[\d]+$', id_without_hgnc):
    # your error message here
    
```


<!-- Sent from Reviewable.io -->

2023-10-05 09:23 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/38)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`web/forms.py` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eris/38#-NfvcoLaES5D7IyE3AUM:-Nfz8bc07vN75STca8ga:b-n08e4s) ([raw file](https://github.com/eastgenomics/eris/blob/a63ed051c9d354a3fd7580294c0b4ca20126fe6d/web/forms.py#L66)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

isdigit() also lets the user pass subscript and superscript: https://stackoverflow.com/questions/44891070/whats-the-difference-between-str-isdigit-isnumeric-and-isdecimal-in-pyth

Try using regex instead, 're.match', which will return a match object if things match, or None otherwise. The pattern ^[\d]+$ matches any number of digits 0-9 only, and the ^ at the start and $ at the end means the whole string must match be digits. 

https://regex101.com/ is a lifesaver for testing any regex stuff. You can put  ^[\d]+$ in the 'Regular expression' box and try it out against different targets in 'Test string'.
</blockquote></details>

changed to regex match 0-9


<!-- Sent from Reviewable.io -->

2023-10-05 09:38 UTC, corbin-chris approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)



<!-- Sent from Reviewable.io -->

2023-10-05 09:38 UTC, merged