First Commit
eastgenomics/eris pull request #4
Opened 2023-07-26 07:35 UTC by JasonLing95

2023-07-31 13:22 UTC, jethror1 requested changes
> Reviewed 23 of 78 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 23 of 78 files reviewed, 7 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`panel_requests/settings.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag-g4f5ZFef7XUmXkQ:-Nag-g4f5ZFef7XUmXkR:b4uymw0) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/panel_requests/settings.py#L32)):*
> ```Python
> 
> # SECURITY WARNING: don't run with debug turned on in production!
> DEBUG = True
> ```

can this be in in config to allow switching



_Code quote:_
```Python
True
```
___
*[`requests_app/tests_requests_app.py` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag1IUo8RGqtI3193Mk:-Nag1IUo8RGqtI3193Ml:bovwj8n) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/tests_requests_app.py#L16)):*
> ```Python
> 
> # TODO: unit testing need revisit
> # TODO: this file is not touched yet
> ```

agreed, the tests don't seem that comprehensive, can they be dropped from this PR so something not ready isn't merged?



_Code quote:_
```Python
# TODO: unit testing need revisit
# TODO: this file is not touched yet
```
___
*[`requests_app/management/queries.py` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag2Sdb5L1fTk-ZDis9:-Nag2Sdb5L1fTk-ZDisA:btw8ydj) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L123)):*
> ```Python
> def remove_panel_clin_indication_link(panel_id: int, indication_id: int, panel_name: str, \
>                                       r_code: str, user: str) -> \
>                                         tuple[ClinicalIndicationPanelHistory | None, str | None]:
> ```

for this kind of function formatting something like this might be a bit cleaer:
```
def remove_panel_clin_indication_link( 
    panel_id: int, 
    indication_id: int, 
    panel_name: str, 
    rcode: str, 
    user: str
    ) -> tuple[ClinicalIndicationPanelHistory | None, str | None]:
```



_Code quote:_
```Python
def remove_panel_clin_indication_link(panel_id: int, indication_id: int, panel_name: str, \
                                      r_code: str, user: str) -> \
                                        tuple[ClinicalIndicationPanelHistory | None, str | None]:
```
___
*[`requests_app/management/queries.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag4TBo0kKhX_VrcDw5:-Nag4TBo0kKhX_VrcDw6:b1bauau) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L202)):*
> ```Python
>             err = "The clinical indication \"{}\" is present more than once in the database,".format(r_code) \
>             + " but none are current, so can't infer which to use -" + \
>                 " exiting without making changes"
> ```

message says exiting but function just returns None, will it always exit on returning None from being called?



_Code quote:_
```Python
" exiting without making changes"
```
___
*[`requests_app/management/queries.py` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag3qppAaC9DbqRYSgr:-Nag3qppAaC9DbqRYSgs:brempci) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L206)):*
> ```Python
>         
>         # deduplicate dict
>         current_indications = [dict(t) for t in {tuple(d.items()) for d in current_indications}]
> ```

confused by this, can you explain whats going on? 



_Code quote:_
```Python
        # deduplicate dict
        current_indications = [dict(t) for t in {tuple(d.items()) for d in current_indications}]
```
___
*[`requests_app/management/commands/_insert_ci.py` line 116 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag5J_UEg3a9kCcT1Kg:-Nag5J_UEg3a9kCcT1Kh:b-v0abct) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/commands/_insert_ci.py#L116)):*
> ```Python
>     td_date: str = json_data["date"]
> 
>     unique_td_source: str = f"{td_source} + {config_source} + {td_date}"
> ```

where is this used and why is it a string formatted with `+` in it?



_Code quote:_
```Python
unique_td_source: str = f"{td_source} + {config_source} + {td_date}"
```
___
*[`requests_app/management/commands/_insert_ci.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag6FHgBJ1W0DzRxlGX:-Nag6FHgBJ1W0DzRxlGY:b9qzdpa) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/commands/_insert_ci.py#L256)):*
> ```Python
> 
>             cpi_instance.save()
> ```

brain has given up here, coming back in a bit


<!-- Sent from Reviewable.io -->

2023-07-31 13:24 UTC, jethror1 requested changes
> Reviewed 27 of 78 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 48 of 78 files reviewed, 7 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-07-31 13:56 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 48 of 78 files reviewed, 7 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`panel_requests/settings.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag-g4f5ZFef7XUmXkQ:-Nag7Ejw-tTVLbNC1qAK:b-8zynan) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/panel_requests/settings.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be in in config to allow switching
</blockquote></details>

changed to fetch from env
___
*[`requests_app/tests_requests_app.py` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag1IUo8RGqtI3193Mk:-Nag7LpIAYBwId1cQ3R3:bvyavih) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/tests_requests_app.py#L16)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

agreed, the tests don't seem that comprehensive, can they be dropped from this PR so something not ready isn't merged?
</blockquote></details>

dropped test_requests_app.py
___
*[`requests_app/management/queries.py` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag2Sdb5L1fTk-ZDis9:-Nag7h2t7ZMa5oEFBIjK:b-r29x9z) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L123)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

for this kind of function formatting something like this might be a bit cleaer:
```
def remove_panel_clin_indication_link( 
    panel_id: int, 
    indication_id: int, 
    panel_name: str, 
    rcode: str, 
    user: str
    ) -> tuple[ClinicalIndicationPanelHistory | None, str | None]:
```
</blockquote></details>

restructured
___
*[`requests_app/management/queries.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag4TBo0kKhX_VrcDw5:-Nag7sTn48J03zJ1woEh:b-bb5jfc) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L202)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

message says exiting but function just returns None, will it always exit on returning None from being called?
</blockquote></details>

this part is returning None which will be caught on a higher-level and displaying the error message returned - which one do you think is better

1. the above method where this function will return None (caught in higher-level) + error message which will be displayed

2. the method itself raise Error and print the error message in the function without returning to higher-level
___
*[`requests_app/management/queries.py` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag3qppAaC9DbqRYSgr:-NagDxMk7m19Wo_qjbc3:b-3by74h) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L206)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

confused by this, can you explain whats going on? 
</blockquote></details>

I will modify the function a bit and change this bit. Stay tuned!
___
*[`requests_app/management/commands/_insert_ci.py` line 116 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag5J_UEg3a9kCcT1Kg:-NagDAUs2ONNS7vY4nGe:bldr2i7) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/commands/_insert_ci.py#L116)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where is this used and why is it a string formatted with `+` in it?
</blockquote></details>

this is used when we make panels from test directory, specifically those clinical indication that have HGNCs as panels. We want to make a unique td_source of test_directory filename, config used to make the test-directory and when the TD is made for those panel. Most panels will have "PanelApp" as their "panel_source" since that's where we get the panel from. Some is created from when we are seeding from TD thus the unique td_source


![Screenshot 2023-07-31 at 14.54.22.png](https://files.reviewableusercontent.io/images/reviewable/60819172/T5c4_HOCAJPYxRCL3K-gLM2M/Screenshot%202023-07-31%20at%2014.54.22.png)


<!-- Sent from Reviewable.io -->

2023-07-31 15:25 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 48 of 79 files reviewed, 7 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_insert_ci.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag6FHgBJ1W0DzRxlGX:-NagYUER--IvYcVm0zLN:b32wtd) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/commands/_insert_ci.py#L256)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

brain has given up here, coming back in a bit
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-07-31 15:27 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 48 of 79 files reviewed, 7 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/queries.py` line 123 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag2Sdb5L1fTk-ZDis9:-NagYihr68eynqmLgxFy:bnrworc) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L123)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

restructured
</blockquote></details>

function reformatted. 
___
*[`requests_app/management/queries.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag4TBo0kKhX_VrcDw5:-NagYlZQ8s6db3mkNYHY:bxozn0l) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L202)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this part is returning None which will be caught on a higher-level and displaying the error message returned - which one do you think is better

1. the above method where this function will return None (caught in higher-level) + error message which will be displayed

2. the method itself raise Error and print the error message in the function without returning to higher-level
</blockquote></details>

ignore above. Function reformatted to be clearer.


<!-- Sent from Reviewable.io -->

2023-07-31 15:27 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 48 of 79 files reviewed, 7 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/queries.py` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag3qppAaC9DbqRYSgr:-NagYqtp3CRcQ6v9K9Zb:buz6ld4) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L206)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I will modify the function a bit and change this bit. Stay tuned!
</blockquote></details>

Function reformatted.


<!-- Sent from Reviewable.io -->

2023-08-01 08:18 UTC, jethror1 requested changes
> Reviewed 7 of 78 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 55 of 79 files reviewed, 8 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`web/views.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakA91w60e5RkUFJ9ZE:-NakA91w60e5RkUFJ9ZF:b-70y2az) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/web/views.py#L1)):*
> ```Python
> import collections
> ```

 can you update docstrings in this file, some are missing / need more details / missing param descriptions


<!-- Sent from Reviewable.io -->

2023-08-01 08:19 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 55 of 79 files reviewed, 10 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`web/templates/base.html` line 22 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakAOYr-r9WU-ACOsBZ:-NakAOYs6EgXj-E69XM8:b-8g7wsf) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/web/templates/base.html#L22)):*
> ```HTML
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
> 
> </head>
> ```

CDNs won't work when deployed to server behind firewall (I assume)



_Code quote:_
```HTML
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eris</title>

    <!-- Favicon -->
    <link rel="favicon icon" href="{% static 'images/favicon.ico' %}"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Color Palette -->
    <!--  https://www.color-hex.com/color-palette/1027214  -->

    <!-- Bootstrap Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
```
___
*[`web/templates/base.html` line 58 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakAU461499aGJKcUYw:-NakAU461499aGJKcUYx:b-amb601) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/web/templates/base.html#L58)):*
> ```HTML
>     {% block content %}{% endblock %}
>     <!-- Bootstrap JS -->
>     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
> ```

also this CDN



_Code quote:_
```HTML
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
```


<!-- Sent from Reviewable.io -->

2023-08-01 08:26 UTC, Yu-jinKim commented on requests_app/management/commands/_insert_ci.py
> +        return td_filename.split("-")[-1].lstrip("v").strip()
can we get a small comment of the expected format using an example?

2023-08-01 08:29 UTC, jethror1 requested changes
> Reviewed 11 of 78 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 65 of 79 files reviewed, 11 unresolved discussions (waiting on @JasonLing95 and @oniblock)

___
*[`requests_app/management/queries.py` line 182 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakCIMt-gftY4Qj41SR:-NakCIMt-gftY4Qj41SS:b-eish8j) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L182)):*
> ```Python
>     have multiple results, and you only want 1 'current' indication entry.
>     If there's just one result found, it will return the indication regardless of whether it's active or not.
>     Generates info and error messages too.
> ```

can you add to the docstring what is returned for each scenario since there's several



_Code quote:_
```Python
 Generates info and error messages too.
```
___
*[`requests_app/management/queries.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakCNfFDI1P0kHxvY2U:-NakCNfFDI1P0kHxvY2V:bpgqdb3) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L202)):*
> ```Python
>             err = "The clinical indication \"{}\" is present more than once in the database,".format(r_code) \
>             + " but none are current, so can't infer which to use -" + \
>                 " exiting without making changes"
> ```

multi line strings would be better formatted with parentheses:
```
err = (
    f"The clinical indication \"{r\_code}\" is present more than once in the database, "
    " but none are current, so can't infer which to use - exiting without making changes"
)
```



_Code quote:_
```Python
            err = "The clinical indication \"{}\" is present more than once in the database,".format(r_code) \
            + " but none are current, so can't infer which to use -" + \
                " exiting without making changes"
```
___
*[`requests_app/management/queries.py` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag3qppAaC9DbqRYSgr:-NakCg6lCL6h_zaGrBU9:b-1z4xde) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L206)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Function reformatted.
</blockquote></details>

still confused by this, I assume `current_indications` is a dict, what are you doing to it? what structure is it before and after?


<!-- Sent from Reviewable.io -->

2023-08-01 08:36 UTC, jethror1 reviewed
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 66 of 79 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @oniblock)



<!-- Sent from Reviewable.io -->

2023-08-01 08:39 UTC, jethror1 reviewed
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 68 of 79 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @oniblock)



<!-- Sent from Reviewable.io -->

2023-08-01 08:41 UTC, jethror1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 68 of 79 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @oniblock)



<!-- Sent from Reviewable.io -->

2023-08-01 08:44 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 65 of 79 files reviewed, 11 unresolved discussions (waiting on @JasonLing95 and @oniblock)

___
*[`requests_app/management/commands/_utils.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakG9962OqsP3Pvtw64:-NakG9962OqsP3Pvtw65:b-ssrd9n) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_utils.py#L2)):*
> ```Python
> def sortable_version(version: str) -> str:
>     """
> ```

where and why are either of these functions needed? why `zfill(5)`?



_Code quote:_
```Python
def sortable_version(version: str) -> str:
    """
```


<!-- Sent from Reviewable.io -->

2023-08-01 08:48 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 65 of 79 files reviewed, 12 unresolved discussions (waiting on @JasonLing95 and @oniblock)

___
*[`requests_app/management/commands/_queries.py` line 63 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakH9HACoUyS089DH_X:-NakH9HACoUyS089DH_Y:bk8xaqw) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_queries.py#L63)):*
> ```Python
>     """
>     Fetch ci-panel and make it active. If it doesn't exist, create it.
>     """
> ```

can we add params to this fucntion and the one below



_Code quote:_
```Python
    """
    Fetch ci-panel and make it active. If it doesn't exist, create it.
    """
```


<!-- Sent from Reviewable.io -->

2023-08-01 09:11 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 65 of 81 files reviewed, 12 unresolved discussions (waiting on @jethror1 and @oniblock)

___
*[`requests_app/management/queries.py` line 182 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakCIMt-gftY4Qj41SR:-NakMRy_3EwSJX0uLWa2:bnm7qph) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L182)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add to the docstring what is returned for each scenario since there's several
</blockquote></details>

file removed. please ignore
___
*[`requests_app/management/queries.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakCNfFDI1P0kHxvY2U:-NakMU0F-WRWXGK2J1Uh:bnm7qph) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L202)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

multi line strings would be better formatted with parentheses:
```
err = (
    f"The clinical indication \"{r\_code}\" is present more than once in the database, "
    " but none are current, so can't infer which to use - exiting without making changes"
)
```
</blockquote></details>

file removed. please ignore
___
*[`requests_app/management/queries.py` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-Nag3qppAaC9DbqRYSgr:-NakMOsf1Af6Baq0EVnS:bnm7qph) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/requests_app/management/queries.py#L206)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

still confused by this, I assume `current_indications` is a dict, what are you doing to it? what structure is it before and after?
</blockquote></details>

file removed. please ignore


<!-- Sent from Reviewable.io -->

2023-08-01 09:17 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 65 of 81 files reviewed, 12 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_insert_ci.py` line 40 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280278821:-NakNjop4Mpvg7GJXVRb:b8e3ntx) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_ci.py#L40)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can we get a small comment of the expected format using an example?
</blockquote></details>

added example
___
*[`requests_app/management/commands/_queries.py` line 63 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakH9HACoUyS089DH_X:-NakNiF49NZX32uSwgta:b51kggp) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_queries.py#L63)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we add params to this fucntion and the one below
</blockquote></details>

added comments


<!-- Sent from Reviewable.io -->

2023-08-01 09:17 UTC, jethror1 requested changes
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 18 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/seed.py` line 24 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakITD40W-r63MjeqK3:-NakITD40W-r63MjeqK4:b-syr808) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L24)):*
> ```Python
>     )
> 
>     def _validate_td(self, directory: str) -> bool:
> ```

missing doc string



_Code quote:_
```Python
def _validate_td(self, directory: str) -> bool:
```
___
*[`requests_app/management/commands/seed.py` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakIUjCEbI1GK4Q5cSq:-NakIUjCEbI1GK4Q5cSr:bk1pmei) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L30)):*
> ```Python
>         return True
> 
>     def _validate_file_exist(self, file_paths: list[str]) -> bool:
> ```

missing docstring



_Code quote:_
```Python
ef _validate_file_exist(self, file_paths: list[str]) -> bool:
```
___
*[`requests_app/management/commands/seed.py` line 33 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakIfZm-QkxHu3gYym9:-NakIfZm-QkxHu3gYymA:b-2a2v7t) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L33)):*
> ```Python
>         for file_path in file_paths:
>             if not file_path or not os.path.isfile(file_path):
>                 raise Exception(f"File {file_path} does not exist")
> ```

if you are checking for existence of multiple things and going to raise an error, I think it can be nicer to check all up front and error if one or more does not exist. This way if 3 files don't exist, you don't have to run it 3 times and get 3 separate exceptions, maybe something like this:
```
missing = []
for file_path in file_paths:
     if not file_path or not os.path.isfile(file_path):
        missing.append(file_path)

if missing:
    raise Exception(f"One or more files missing: {missing}")

```



_Code quote:_
```Python
          raise Exception(f"File {file_path} does not exist")
```
___
*[`requests_app/management/commands/seed.py` line 84 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakJfwQ-WHznUQVJ4Iw:-NakJfwQ-WHznUQVJ4Ix:bsighme) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L84)):*
> ```Python
>             type=str,
>             help="Path to hgnc dump .txt file",
>             default="testing_files/hgnc_dump_20230613.txt",
> ```

not sure we should hard code a default, seems better to not accidentally use an old version from testing dir



_Code quote:_
```Python
default="testing_files/hgnc_dump_20230613.txt",
```
___
*[`requests_app/management/commands/seed.py` line 107 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakLmzR63ANi-UKBrRH:-NakLmzR63ANi-UKBrRI:b-ywfjq0) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L107)):*
> ```Python
>             "--markname",
>             type=str,
>             help="Path to markname csv file",
> ```

what is markname?



_Code quote:_
```Python
markname
```
___
*[`web/views.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakA91w60e5RkUFJ9ZE:-NakNTqPB0s7zC2zTNDj:bfxgdd4) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/web/views.py#L1)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

updated
</blockquote></details>

can you add some more detail as to the logic in each, some are confusing as to know what is going on since its more than a simple one line db call to return some data to the front end
___
*[`web/views.py` line 409 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakNNvO0HTdUV163ehd:-NakNNvO0HTdUV163ehe:b-5ubcgb) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/web/views.py#L409)):*
> ```Python
>     """
> 
>     limit: int = 50
> ```

what is limit used for?



_Code quote:_
```Python
 limit: int = 50
```


<!-- Sent from Reviewable.io -->

2023-08-01 09:19 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 18 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_utils.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakG9962OqsP3Pvtw64:-NakNnZB4US1iG7D1Fgx:b-b3ekxo) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_utils.py#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where and why are either of these functions needed? why `zfill(5)`?
</blockquote></details>

both functions sortable_version change the version from 1.1 to 00001.00001 something like that which allows sorting within the database. normalize_version change it back to 1.1

just a function to make it sortable using django-orm e.g. Panel.objects.filter(panel_version_lte=13.1) something like that


<!-- Sent from Reviewable.io -->

2023-08-01 09:24 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 18 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/seed.py` line 24 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakITD40W-r63MjeqK3:-NakPRwdDl6xn3saV_d1:b-7tfmjp) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing doc string
</blockquote></details>

added
___
*[`requests_app/management/commands/seed.py` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakIUjCEbI1GK4Q5cSq:-NakPRR17kjlVfZhC0zX:b-7tfmjp) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L30)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing docstring
</blockquote></details>

added
___
*[`requests_app/management/commands/seed.py` line 33 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakIfZm-QkxHu3gYym9:-NakP8-PA-j0JARPQYY6:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L33)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you are checking for existence of multiple things and going to raise an error, I think it can be nicer to check all up front and error if one or more does not exist. This way if 3 files don't exist, you don't have to run it 3 times and get 3 separate exceptions, maybe something like this:
```
missing = []
for file_path in file_paths:
     if not file_path or not os.path.isfile(file_path):
        missing.append(file_path)

if missing:
    raise Exception(f"One or more files missing: {missing}")

```
</blockquote></details>

updated
___
*[`requests_app/management/commands/seed.py` line 84 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakJfwQ-WHznUQVJ4Iw:-NakOyXdBVqaKOfiYL7B:bjmt86n) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L84)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure we should hard code a default, seems better to not accidentally use an old version from testing dir
</blockquote></details>

this just ease my testing process of calling python manage.py seed transcript rather than putting in --hgnc --mane --markname --g2refseq
___
*[`requests_app/management/commands/seed.py` line 107 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakLmzR63ANi-UKBrRH:-NakOu_71SChp0VOhIui:b-om1w7a) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L107)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is markname?
</blockquote></details>

one of the table from hgmd database


<!-- Sent from Reviewable.io -->

2023-08-01 09:25 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 18 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`web/views.py` line 409 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakNNvO0HTdUV163ehd:-NakPbhD9pDCpU5EleuS:b-t4agng) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/web/views.py#L409)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is limit used for?
</blockquote></details>

default calling of history, we limit it to 50 rows. if user want all of them, there is checkbox in the front-end


<!-- Sent from Reviewable.io -->

2023-08-01 09:27 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 18 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`web/views.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eris/4#-NakA91w60e5RkUFJ9ZE:-NakQ9Pp13IABqdGn50k:btxw5fz) ([raw file](https://github.com/eastgenomics/eris/blob/01f93b47eda62dc5375e7c64e965cd5a8d787ca9/web/views.py#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add some more detail as to the logic in each, some are confusing as to know what is going on since its more than a simple one line db call to return some data to the front end
</blockquote></details>

which functions need more docstring please


<!-- Sent from Reviewable.io -->

2023-08-01 09:57 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 24 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_insert_panel.py` line 36 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakQ42L7fvUc-YmO3Yl:-NakQ42M60BX3GXL26su:bcv80ho) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L36)):*
> ```Python
>     """
>     Insert data from parsed JSON into database.
>     """
> ```

this function is pretty chonky, would it be useful to break it down?



_Code quote:_
```Python
def insert_data_into_db(panel: PanelClass) -> None:
    """
    Insert data from parsed JSON into database.
    """
```
___
*[`requests_app/management/commands/_insert_panel.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakONe64WOR-Tdo_bwK:-NakONe717npCGc4SADG:b-15p4pw) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L219)):*
> ```Python
>             start_37=single_region.get("grch37_coordinates")[0]
>             if single_region.get("grch37_coordinates")
>             else None,
> ```

This is v confusing to read all being one big block, where you have some if/else logic, do you think its more readable like this?

```
chrom=single_region.get("chromosome"),
start_37=(
    single_region.get("grch37_coordinates")[0]
    if single_region.get("grch37_coordinates") else None
),
end37=...
```



_Code quote:_
```Python
            start_37=single_region.get("grch37_coordinates")[0]
            if single_region.get("grch37_coordinates")
            else None,
```
___
*[`requests_app/management/commands/_insert_panel.py` line 248 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakPlKdBTbWHzGqOwJT:-NakPlKe1aP7QlOr_YEk:bk1pmei) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L248)):*
> ```Python
> 
> @transaction.atomic
> def insert_form_data(parsed_data: dict) -> None:
> ```

missing docstring



_Code quote:_
```Python
def insert_form_data(parsed_data: dict) -> None:
```
___
*[`requests_app/management/commands/_insert_panel.py` line 260 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakOzhJBCx4NnlK9zyy:-NakOzhJBCx4NnlK9zyz:bo368hl) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L260)):*
> ```Python
>     if associated_panel.panel_name != panel_name:
>         raise ValueError(
>             "Panel name in database does not match panel name in excel. Aborting."
> ```

would be more useful if the values causing the error were added to the message



_Code quote:_
```Python
Panel name in database does not match panel name in excel. Aborting."
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 11 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakQKVd6h7MkanQbWw9:-NakQKVd6h7MkanQbWwA:b-aryczh) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_parse_transcript.py#L11)):*
> ```Python
> 
> 
> def seed_transcripts(
> ```

strongly dislike this function as it be huge:
- can each reading in of a file be abstracted to its own function (also will make it much easier to unit test)
- also think that each of the for loops should be split out or changed somehow, there's a lot of logic in here and its confusing
- read in of files line by line isn't optimal, pandas / polars would be a better solution and easier to read / apply column-wise logic
- needs a docstring and comments where there's complex many line loops



_Code quote:_
```Python
def seed_transcripts(
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 29 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakRY_O-SuPD-Xl0vEw:-NakRY_O-SuPD-Xl0vEx:bcsxeo9) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_parse_transcript.py#L29)):*
I'd consider using pandas to read in these tsvs and csv for speed/readability/functionality:

```
# read header line
>>> with open('hgnc_complete_set.txt') as f:
...     header = f.readline().split('\t')
... 
>>> header
['hgnc_id', 'symbol', 'name', 'locus_group', 'locus_type', 'status', 'location', 'location_sortable', 'alias_symbol', 'alias_name', 'prev_symbol', 'prev_name', 'gene_group', 'gene_group_id', 'date_approved_reserved', 'date_symbol_changed', 'date_name_changed', 'date_modified', 'entrez_id', 'ensembl_gene_id', 'vega_id', 'ucsc_id', 'ena', 'refseq_accession', 'ccds_id', 'uniprot_ids', 'pubmed_id', 'mgd_id', 'rgd_id', 'lsdb', 'cosmic', 'omim_id', 'mirbase', 'homeodb', 'snornabase', 'bioparadigms_slc', 'orphanet', 'pseudogene.org', 'horde_id', 'merops', 'imgt', 'iuphar', 'kznf_gene_catalog', 'mamit-trnadb', 'cd', 'lncrnadb', 'enzyme_id', 'intermediate_filament_db', 'rna_central_ids', 'lncipedia', 'gtrnadb', 'agr', 'mane_select', 'gencc\n']

##
# do asserts here on what you want to check about the file
##

# read to df
>>> hgnc_df = pd.read_csv('hgnc_complete_set.txt', header=0, names=header, sep='\t', low_memory=False)
>>> hgnc_df
          hgnc_id    symbol                                               name          locus_group                 locus_type  ... lncipedia gtrnadb         agr                     mane_select     gencc\n
0          HGNC:5      A1BG                             alpha-1-B glycoprotein  protein-coding gene  gene with protein product  ...       NaN     NaN      HGNC:5   ENST00000263100.8|NM_130786.4         NaN
1      HGNC:37133  A1BG-AS1                               A1BG antisense RNA 1       non-coding RNA       RNA, long non-coding  ...  A1BG-AS1     NaN  HGNC:37133                             NaN         NaN
2      HGNC:24086      A1CF                     APOBEC1 complementation factor  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:24086   ENST00000373997.8|NM_014576.4         NaN
3          HGNC:7       A2M                              alpha-2-macroglobulin  protein-coding gene  gene with protein product  ...       NaN     NaN      HGNC:7  ENST00000318602.12|NM_000014.6      HGNC:7
4      HGNC:27057   A2M-AS1                                A2M antisense RNA 1       non-coding RNA       RNA, long non-coding  ...   A2M-AS1     NaN  HGNC:27057                             NaN         NaN
...           ...       ...                                                ...                  ...                        ...  ...       ...     ...         ...                             ...         ...
43703  HGNC:25820    ZYG11B       zyg-11 family member B, cell cycle regulator  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:25820   ENST00000294353.7|NM_024646.3  HGNC:25820
43704  HGNC:13200       ZYX                                              zyxin  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:13200  ENST00000322764.10|NM_003461.5         NaN
43705  HGNC:51695     ZYXP1                                 zyxin pseudogene 1           pseudogene                 pseudogene  ...       NaN     NaN  HGNC:51695                             NaN         NaN
43706  HGNC:29027     ZZEF1  zinc finger ZZ-type and EF-hand domain contain...  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:29027   ENST00000381638.7|NM_015113.4         NaN
43707  HGNC:24523      ZZZ3                   zinc finger ZZ-type containing 3  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:24523   ENST00000370801.8|NM_015534.6         NaN

[43708 rows x 54 columns]


# limit to required columns
>>> hgnc_df = hgnc_df[['hgnc_id', 'symbol' [...]

2023-08-01 10:00 UTC, Yu-jinKim commented on requests_app/management/commands/_utils.py
> +def sortable_version(version: str) -> str:
yeah that's definitely not the best solution for that

2023-08-01 10:03 UTC, Yu-jinKim commented on requests_app/management/commands/edit.py
> +            if not panel_id:
an assertion would be quicker

2023-08-01 10:03 UTC, Yu-jinKim commented on requests_app/management/commands/edit.py
> +            if not panel:
assertion

2023-08-01 10:03 UTC, Yu-jinKim commented on requests_app/management/commands/edit.py
> +            if not panel_name:
assertion

2023-08-01 10:03 UTC, Yu-jinKim commented on requests_app/management/commands/edit.py
> +            if not panel:
assertion

2023-08-01 10:03 UTC, Yu-jinKim commented on requests_app/management/commands/edit.py
> +            elif len(panel) > 1:
assertion

2023-08-01 10:06 UTC, Yu-jinKim commented on requests_app/management/commands/generate.py
> +            for row in csv.DictReader(f, delimiter="\t"):
that can be panda-ified

2023-08-01 10:07 UTC, Yu-jinKim commented on requests_app/management/commands/generate.py
> +                "Test Directory has yet been imported!"
i wouldn't assume anything, just print what is actually the case

2023-08-01 10:12 UTC, Yu-jinKim commented on requests_app/management/commands/panel.py
> +    Class for panel with additional function
a bit more description please

2023-08-01 10:14 UTC, Yu-jinKim commented on requests_app/management/commands/panel.py
> +    while panelapp_url:
you should explain why you have to do that

2023-08-01 10:19 UTC, Yu-jinKim commented on requests_app/management/commands/seed.py
> +        print(kwargs)
to remove

2023-08-01 10:22 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 24 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_insert_panel.py` line 36 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakQ42L7fvUc-YmO3Yl:-Nakb1RrBFK7JBuaJQPN:bmz3h19) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this function is pretty chonky, would it be useful to break it down?
</blockquote></details>

separated gene and region insertion into its own function
___
*[`requests_app/management/commands/_insert_panel.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakONe64WOR-Tdo_bwK:-NakbVi24x_B3ubu-ygO:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L219)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

This is v confusing to read all being one big block, where you have some if/else logic, do you think its more readable like this?

```
chrom=single_region.get("chromosome"),
start_37=(
    single_region.get("grch37_coordinates")[0]
    if single_region.get("grch37_coordinates") else None
),
end37=...
```
</blockquote></details>

updated
___
*[`requests_app/management/commands/_insert_panel.py` line 248 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakPlKdBTbWHzGqOwJT:-NakbWOcBpKqBvgzi74U:br22zho) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L248)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing docstring
</blockquote></details>

thrown the function away. it's not relevant for now
___
*[`requests_app/management/commands/_insert_panel.py` line 260 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakOzhJBCx4NnlK9zyy:-Nakb_hf5Jwxjtg5ZaPW:br22zho) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_insert_panel.py#L260)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

would be more useful if the values causing the error were added to the message
</blockquote></details>

thrown the function away. it's not relevant for now


<!-- Sent from Reviewable.io -->

2023-08-01 10:23 UTC, Yu-jinKim commented on README.md
> +This command required 5 files:
this will need a lot more explanation, feel free to look into the panel manual for that

2023-08-01 10:26 UTC, Yu-jinKim commented on requests_app/models.py
> +    external_id = models.TextField(
is TextField appropriate for this? Isn't CharField better ?

2023-08-01 10:26 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 67 of 81 files reviewed, 35 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_utils.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakG9962OqsP3Pvtw64:-NakYNEs1_oo2zdF-ZaP:b-rdwpvw) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_utils.py#L2)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

both functions sortable_version change the version from 1.1 to 00001.00001 something like that which allows sorting within the database. normalize_version change it back to 1.1

just a function to make it sortable using django-orm e.g. Panel.objects.filter(panel_version_lte=13.1) something like that
</blockquote></details>

and storing of 1.1 as a version doesn't allow sorting? have you examples of this because its confusing why adding a load of zero's enables sorting

also, is this version field being stored as a string?
___
*[`requests_app/management/commands/generate.py` line 42 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakZ6bw8GymsQ_FWil8:-NakZ6bw8GymsQ_FWil9:b-qfcdpp) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L42)):*
this looks to just read the first line and breaks, which would be nicer as:
```
>>> with open('hgnc_complete_set.txt') as f:
...     header = f.readline().split('\t')

>>> required = ['hgnc', 'locus', 'approved']
>>> assert all([x in header for x in required]), ('Missing required columns')

```



_Code quote:_
```Python
        with open(file_path, "r") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                if "HGNC ID" not in row:
                    raise ValueError("HGNC ID column not found in HGNC dump")

                if "Locus type" not in row:
                    raise ValueError("Locus Type column not found in HGNC dump")

                if "Approved name" not in row:
                    raise ValueError("Approved Name column not found in HGNC dump")

                break
```
___
*[`requests_app/management/commands/generate.py` line 46 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakZvGy9SVVMxNNuTPL:-NakZvGy9SVVMxNNuTPM:bk1pmei) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L46)):*
> ```Python
>         return True
> 
>     def _parse_hgnc(self, file_path) -> set:
> ```

missing docstring



_Code quote:_
```Python
  def _parse_hgnc(self, file_path) -> set:
```
___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-Nak_-r0BjvZTPS2Mg0x:b-52hylo) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
> ```Python
>                     re.IGNORECASE,
>                 ):
>                     rnas.add(row["HGNC ID"])
> ```

whats this doing?



_Code quote:_
```Python
                if re.search("rna", row["Locus type"], re.IGNORECASE) or re.search(
                    "mitochondrially encoded",
                    row["Approved name"],
                    re.IGNORECASE,
                ):
                    rnas.add(row["HGNC ID"])
```
___
*[`requests_app/management/commands/generate.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_4ja3uY1SKFP36FE:-Nak_4ja3uY1SKFP36FF:bcacq85) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L62)):*
> ```Python
>     def _generate_genepanels(self, rnas: set, output_directory: str) -> None:
>         """
>         Main function to generate genepanel.tsv
> ```

missing params



_Code quote:_
```Python
Main function to generate genepanel.tsv
```
___
*[`requests_app/management/commands/generate.py` line 104 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_EX-AiMcN4lYjtq0:-Nak_EX-AiMcN4lYjtq1:br0tnyn) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L104)):*
> ```Python
>                 for hgnc in panel_genes[panel_id]:
>                     # for each gene associated with that panel
>                     if hgnc in ["HGNC:12029", "HGNC:5541"] or hgnc in rnas:
> ```

as we discussed, can this be abstracted out into a config with an explanation why these IDs are being excluded



_Code quote:_
```Python
["HGNC:12029", "HGNC:5541"]
```
___
*[`requests_app/management/commands/generate.py` line 113 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakaV9X7nzV-CNAB2Yw:-NakaV9X7nzV-CNAB2Yx:b-jc1uf2) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L113)):*
> ```Python
>                             hgnc,
>                         ]
>                     )
> ```

this is pretty long, maybe this would be better:
```
# normalise version, set to 1.0 if doesn't exist already

version = (
    normalize_version(panel_dict['panel_id__panel_version'])
    if panel_dict['panel_id__panel_version'] else '1.0'
)

results.append([
    f"{r_code}\_{ci_name}",
    f"{panel_dict['panel_id__panel_name']}_{version}",
    hgnc,
])
```



_Code quote:_
```Python
                    results.append(
                        [
                            f"{r_code}_{ci_name}",
                            f"{panel_dict['panel_id__panel_name']}_{normalize_version(panel_dict['panel_id__panel_version']) if panel_dict['panel_id__panel_version'] else '1.0'}",
                            hgnc,
                        ]
                    )
```
___
*[`requests_app/management/commands/generate.py` line 124 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakbFSI-Jk8o0OJlQJ2:-NakbFSI-Jk8o0OJlQJ3:bk1pmei) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L124)):*
> ```Python
>                 f.write(f"{data}\n")
> 
>     def _generate_g2t(self, output_directory) -> None:
> ```

missing docstring



_Code quote:_
```Python
def _generate_g2t(self, output_directory) -> None:
```
___
*[`requests_app/management/commands/generate.py` line 151 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nakboo03hRrPr2fkeYg:-Nakboo03hRrPr2fkeYh:b-1bmwiz) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L151)):*
> ```Python
>         parser.add_argument("command", nargs="?")
>         parser.add_argument("--hgnc")
>         parser.add_argument("--output")
> ```

why is this not just in with the initial set up of the cmd line args?



_Code quote:_
```Python
    def add_arguments(self, parser):
        parser.add_argument("command", nargs="?")
        parser.add_argument("--hgnc")
        parser.add_argument("--output")
```
___
*[`requests_app/management/commands/generate.py` line 154 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakblQxC2sujXbTuAfJ:-NakblQxC2sujXbTuAfK:blfvipa) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L154)):*
> ```Python
> 
>     def handle(self, *args, **options):
>         cmd = options.get("command")
> ```

string doc



_Code quote:_
```Python
    def handle(self, *args, **options):
        cmd = options.get("command")
```
___
*[`requests_app/management/commands/panel.py` line 1 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakcHcODdOgiTF0HeCI:-NakcHcP7bodOcizaPjs:b-gzsjzb) ([raw file](https://github.com/eastgenom [...]

2023-08-01 10:27 UTC, Yu-jinKim commented on requests_app/models.py
> +    created_date = models.DateField(
you could combine them https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

2023-08-01 10:27 UTC, Yu-jinKim commented on requests_app/models.py
> +    created_date = models.DateField(
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

2023-08-01 10:29 UTC, Yu-jinKim commented on requests_app/models.py
> +    created_date = models.DateField(
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

2023-08-01 10:29 UTC, Yu-jinKim commented on requests_app/models.py
> +    created_date = models.DateField(
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

2023-08-01 10:30 UTC, Yu-jinKim commented on requests_app/models.py
> +    confidence_level = models.CharField(
you can probably reduce the max length

2023-08-01 10:31 UTC, Yu-jinKim commented on requests_app/models.py
> +    hgnc_id = models.CharField(verbose_name="HGNC id", max_length=255, unique=True)
i think you can assume that an id won't be longer than 20 anytime soon

2023-08-01 10:33 UTC, Yu-jinKim commented on requests_app/models.py
> +    created_date = models.DateField(
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

2023-08-01 10:36 UTC, Yu-jinKim commented on web/forms.py
> +        if "," in panel_name:
some panels have commas in them

2023-08-01 10:43 UTC, Yu-jinKim commented on web/views.py
> +    Panel info page
more info plz

2023-08-01 10:45 UTC, Yu-jinKim commented on web/views.py
> +        # form submission
should probably an elif for POST. Can a method be something else?

2023-08-01 10:46 UTC, Yu-jinKim commented on web/views.py
> +            print(form_valid, form.errors, panel)
to remove

2023-08-01 10:47 UTC, Yu-jinKim commented on web/views.py
> +        actions: list[str] = [
what is that?

2023-08-01 10:47 UTC, Yu-jinKim commented on web/views.py
> +    Edit Panel gene page
no POST request?

2023-08-01 12:53 UTC, jethror1 requested changes
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 70 of 81 files reviewed, 74 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/seed.py` line 107 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakLmzR63ANi-UKBrRH:-Nal8jam2oycjVM6NhDp:b-waprsg) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/seed.py#L107)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

one of the table from hgmd database
</blockquote></details>

can you add this to the help (or readme), if one of us looks at this in X months time I would 100% not remember


<!-- Sent from Reviewable.io -->

2023-08-01 12:53 UTC, jethror1 reviewed
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 71 of 81 files reviewed, 74 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-08-01 12:53 UTC, jethror1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 71 of 81 files reviewed, 74 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-08-01 12:54 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 71 of 81 files reviewed, 74 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`README.md` line 147 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280427186:-Nal9KomCQcBOYsoRxEv:bk7mh1) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/README.md#L147)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

this will need a lot more explanation, feel free to look into the panel manual for that
</blockquote></details>

agreed, will there be big changes in the next PRs to how it works and should it wait for the readme to be written until its stable(ish)?


<!-- Sent from Reviewable.io -->

2023-08-01 14:41 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 70 of 81 files reviewed, 74 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_parse_transcript.py` line 18 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280384950:-NalXhqyCcQuzA28fLGl:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_parse_transcript.py#L18)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

docstring
</blockquote></details>

done
___
*[`requests_app/management/commands/_parse_transcript.py` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280386083:-NalXlFpAsBvbt7JsBs0:bcn88in) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_parse_transcript.py#L28)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i think we talked about this function, i think you need to rewrite this.
i won't do a deep dive
</blockquote></details>

rewritten
___
*[`requests_app/management/commands/_parse_transcript.py` line 29 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#-NakRY_O-SuPD-Xl0vEw:-NalXoL29MNde3wh7KzQ:b-mqe64m) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_parse_transcript.py#L29)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd consider using pandas to read in these tsvs and csv for speed/readability/functionality:

```
# read header line
>>> with open('hgnc_complete_set.txt') as f:
...     header = f.readline().split('\t')
... 
>>> header
['hgnc_id', 'symbol', 'name', 'locus_group', 'locus_type', 'status', 'location', 'location_sortable', 'alias_symbol', 'alias_name', 'prev_symbol', 'prev_name', 'gene_group', 'gene_group_id', 'date_approved_reserved', 'date_symbol_changed', 'date_name_changed', 'date_modified', 'entrez_id', 'ensembl_gene_id', 'vega_id', 'ucsc_id', 'ena', 'refseq_accession', 'ccds_id', 'uniprot_ids', 'pubmed_id', 'mgd_id', 'rgd_id', 'lsdb', 'cosmic', 'omim_id', 'mirbase', 'homeodb', 'snornabase', 'bioparadigms_slc', 'orphanet', 'pseudogene.org', 'horde_id', 'merops', 'imgt', 'iuphar', 'kznf_gene_catalog', 'mamit-trnadb', 'cd', 'lncrnadb', 'enzyme_id', 'intermediate_filament_db', 'rna_central_ids', 'lncipedia', 'gtrnadb', 'agr', 'mane_select', 'gencc\n']

##
# do asserts here on what you want to check about the file
##

# read to df
>>> hgnc_df = pd.read_csv('hgnc_complete_set.txt', header=0, names=header, sep='\t', low_memory=False)
>>> hgnc_df
          hgnc_id    symbol                                               name          locus_group                 locus_type  ... lncipedia gtrnadb         agr                     mane_select     gencc\n
0          HGNC:5      A1BG                             alpha-1-B glycoprotein  protein-coding gene  gene with protein product  ...       NaN     NaN      HGNC:5   ENST00000263100.8|NM_130786.4         NaN
1      HGNC:37133  A1BG-AS1                               A1BG antisense RNA 1       non-coding RNA       RNA, long non-coding  ...  A1BG-AS1     NaN  HGNC:37133                             NaN         NaN
2      HGNC:24086      A1CF                     APOBEC1 complementation factor  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:24086   ENST00000373997.8|NM_014576.4         NaN
3          HGNC:7       A2M                              alpha-2-macroglobulin  protein-coding gene  gene with protein product  ...       NaN     NaN      HGNC:7  ENST00000318602.12|NM_000014.6      HGNC:7
4      HGNC:27057   A2M-AS1                                A2M antisense RNA 1       non-coding RNA       RNA, long non-coding  ...   A2M-AS1     NaN  HGNC:27057                             NaN         NaN
...           ...       ...                                                ...                  ...                        ...  ...       ...     ...         ...                             ...         ...
43703  HGNC:25820    ZYG11B       zyg-11 family member B, cell cycle regulator  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:25820   ENST00000294353.7|NM_024646.3  HGNC:25820
43704  HGNC:13200       ZYX                                              zyxin  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:13200  ENST00000322764.10|NM_003461.5         NaN
43705  HGNC:51695     ZYXP1                                 zyxin pseudogene 1           pseudogene                 pseudogene  ...       NaN     NaN  HGNC:51695                             NaN         NaN
43706  HGNC:29027     ZZEF1  zinc finger ZZ-type and EF-hand domain contain...  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:29027   ENST00000381638.7|NM_015113.4         NaN
43707  HGNC:24523      ZZZ3                   zinc finger ZZ-type containing 3  protein-coding gene  gene with protein product  ...       NaN     NaN  HGNC:24523   ENST00000370801.8|NM_015534.6         NaN

[43708 rows x 54 columns]


# limit to required columns
>>> hgnc_df = hgnc_df[['hgnc_id', 'symbol', 'alias_symbol', 'prev_symbol']]
>>> hgnc_df
          hgnc_id    symbol                   alias_symbol                prev_symbol
0          HGNC:5      A1BG                            NaN                        NaN
1      HGNC:37133  A1BG-AS1                       FLJ23569  NCRNA00181|A1BGAS|A1BG-AS
2      HGNC:24086      A1CF  ACF|ASP|ACF64|ACF65|APOBEC1CF                        NaN
3          HGNC:7       A2M           FWP007|S863-7|CPAMD5                        NaN
4      HGNC:27057   A2M-AS1                            NaN                        NaN
...           ...       ...                            ...                        ...
43703  HGNC:25820    ZYG11B                       FLJ13456                      ZYG11
43704  HGNC:13200       ZYX                            NaN                        NaN
43705  HGNC:51695     ZYXP1                            NaN                        NaN
43706  HGNC:29027     ZZEF1         KIAA0399|ZZZ4|FLJ10821                        NaN
43707  HGNC:24523      ZZZ3             DKFZP564I052|ATAC1                        NaN

[43708 rows x 4 columns]

```
As far as I can tell below is then just making dicts from the above columns, so maybe something like this for making the 2 dicts of id to symbol and symbol to id as an example:
```
>>> id_to_symbol = dict(zip(hgnc_df['hgnc_id'], hgnc_df['symbol']))
>>> symbol_to_id = dict(zip(hgnc_df['symbol'], hgnc_df['hgnc_id']))
```

can also strip the columns first if needed with: `hgnc_df = hgnc_df.apply(lambda x: x.str.strip())`
</blockquote></details>

panda-fied
___
*[`requests_app/management/commands/_queries.py` line 21 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280387182:-NalOTz4Cd1Am1b6H7DD:bkmvlp4) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_queries.py#L21)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can there be other exceptions?
</blockquote></details>

the error is either DoesNotExist or MultipleObject
https://docs.djangoproject.com/en/4.2/ref/models/querysets/#django.db.models.query.QuerySet.get

MultipleObject is not possible here as we're fetching using database id rather than name or etc
___
*[`requests_app/management/commands/_queries.py` line 42 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280388329:-NalOynOCbhqsXqrKwMf:b-t9ikk8) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/_queries.py#L42)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

do you handle the possible exceptions  [...]

2023-08-02 08:51 UTC, jethror1 reviewed
> Reviewed 4 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 71 of 81 files reviewed, 63 unresolved discussions (waiting on @oniblock and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-08-02 10:52 UTC, jethror1 requested changes
> Reviewed 1 of 78 files at r1, 5 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 77 of 81 files reviewed, 64 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_parse_transcript.py` line 98 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapW4uH-WWu_-NrEHHJ:-NapW4uH-WWu_-NrEHHK:buwwdq0) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L98)):*
> ```Python
>     filtered_mane = mane[
>         mane["MANE TYPE"] == "MANE SELECT"
>     ]  # only mane select transcripts
> ```

are we also not using MANE clinical?



_Code quote:_
```Python
    filtered_mane = mane[
        mane["MANE TYPE"] == "MANE SELECT"
    ]  # only mane select transcripts
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 137 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapWJhH6LsMxbCEVPIJ:-NapWJhH6LsMxbCEVPIK:b-iph1ec) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L137)):*
> ```Python
>             }
>         )
>         .to_dict()["transcript"]
> ```

having a trailing function call seems  weird (surprised it actually works), can it be put on the same line as the above closing parentheses?



_Code quote:_
```Python
.to_dict()["transcript"]
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 143 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapYGPz4SvRWFnk8skI:-NapYGPz4SvRWFnk8skJ:bwnkoc6) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L143)):*
> ```Python
> def _prepare_gene2refseq_file(g2refseq_file: str) -> dict:
>     """
>     Prepare gene2refseq file
> ```

docstring doesn't seem to cover what the function does, I think it needs something more like "Reads through gene2refseq file from HGMD database and generates a dict mapping of HGMD ID to refcore and refversion



_Code quote:_
```Python
Prepare gene2refseq file
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 160 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-Nap_4f27tidLLp-rJ5a:-Nap_4f27tidLLp-rJ5b:bxdf74s) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L160)):*
pandas time:

```
>>> df = pd.read_csv('gene2refseq_202306131409.csv')
>>> df
       hgmdID  ...                                           exonENDS
0           1  ...  7333088,7518389,7579920,7587300,7595641,759743...
1           2  ...  9067839,9068224,9068842,9069813,9070578,907248...
2           3  ...                         42693997,42695631,42720910
3           4  ...  53307713,53307929,53308133,53308349,53308528,5...
4           5  ...                76467727,76468909,76469327,76470117
...       ...  ...                                                ...
11867   15596  ...  49890600,49891107,49891473,49894469,49895180,4...
11868   15597  ...  32191503,32191908,32192250,32192530,32193124,3...
11869   15598  ...  114439675,114440739,114443933,114444652,114446...
11870   15599  ...  32277765,32311181,32316319,32316649,32316874,3...
11871   15600  ...  54630633,54631107,54631306,54631787,54632237,5...

[11872 rows x 14 columns]

# turn 2 target columns into single list column
>>> df['core_plus_version'] = pd.Series(zip(df['refcore'], df['refversion'])).map(list)
>>> df
       hgmdID  ...  core_plus_version
0           1  ...     [NM_145891, 2]
1           2  ...     [NM_000014, 5]
2           3  ...     [NM_017436, 6]
3           4  ...     [NM_015665, 5]
4           5  ...     [NM_001088, 2]
...       ...  ...                ...
11867   15596  ...  [NM_001258017, 1]
11868   15597  ...     [NM_022107, 2]
11869   15598  ...     [NM_015523, 3]
11870   15599  ...     [NM_004798, 3]
11871   15600  ...  [NM_001081637, 2]

[11872 rows x 15 columns]

# turn hgmd ID and new column to dict
return dict(zip(df.hgmdID, df.core_plus_version))
```

this will return a dict formatted as `15600: ['NM_001081637', 2]` which is what we want right?



_Suggestion:_
```Python
    gene2refseq_hgmd: dict[str, list] = collections.defaultdict(list)

    with open(g2refseq_file, "r") as f:
        for row in csv.DictReader(f, delimiter=","):
            if "hgmdID" not in row or "refcore" not in row or "refversion" not in row:
                raise ValueError(
                    "Check gene2refseq columns headers. Error with gene2refseq file"
                )
            # no idea how to make this into pandas
            gene2refseq_hgmd[row["hgmdID"].strip()].append(
                [row["refcore"], row["refversion"]]
            )
            
    
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 167 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapX6xCB688UPLz4BJg:-NapX6xCB688UPLz4BJh:b-91hghi) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L167)):*
> ```Python
> def _prepare_markname_file(markname_file: str) -> dict:
>     """
>     Prepare markname file
> ```

 you add more detail on the markname file (i.e. use and origin)



_Code quote:_
```Python
Prepare markname file
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 248 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapX_etESBK_hZtn499:-NapX_evBNoU1fPdrQLm:bkk66yl) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L248)):*
> ```Python
> 
>                 # hgmd write HGNC ID as XXXXX rather than HGNC:XXXXX
>                 shortened_hgnc_id = hgnc_id[5:]
> ```

`.replace('HGNC:', '')` I think would be better in case the prefix gets dropped in the future



_Code quote:_
```Python
shortened_hgnc_id = hgnc_id[5:]
```
___
*[`requests_app/management/commands/generate.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280401493:-NapbgjI0i0xZ7T8bZ7M:bclnbcv) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/generate.py#L32)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

panda-fied
</blockquote></details>

have you not pushed as it still seems to be `csv.DictReader` to me?
___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-NapeUcrEoQq2xn4SP0P:b6iwcnt) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
can we pandas it for speed and readability:

```
>>> hgnc = pd.read_csv('hgnc_complete_set.txt', sep='\t', low_memory=False)
>>> hgnc
          hgnc_id    symbol  ...                     mane_select       gencc
0          HGNC:5      A1BG  ...   ENST00000263100.8|NM_130786.4         NaN
1      HGNC:37133  A1BG-AS1  ...                             NaN         NaN
2      HGNC:24086      A1CF  ...   ENST00000373997.8|NM_014576.4         NaN
3          HGNC:7       A2M  ...  ENST00000318602.12|NM_000014.6      HGNC:7
4      HGNC:27057   A2M-AS1  ...                             NaN         NaN
...           ...       ...  ...                             ...         ...
43703  HGNC:25820    ZYG11B  ...   ENST00000294353.7|NM_024646.3  HGNC:25820
43704  HGNC:13200       ZYX  ...  ENST00000322764.10|NM_003461.5         NaN
43705  HGNC:51695     ZYXP1  ...                             NaN         NaN
43706  HGNC:29027     ZZEF1  ...   ENST00000381638.7|NM_015113.4         NaN
43707  HGNC:24523      ZZZ3  ...   ENST00000370801.8|NM_01 [...]

2023-08-02 10:53 UTC, jethror1 reviewed
> Reviewed 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 78 of 81 files reviewed, 64 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-08-02 11:42 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 77 of 81 files reviewed, 64 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/_parse_transcript.py` line 98 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapW4uH-WWu_-NrEHHJ:-Naq1M4hAiJ6iO9hMq8r:bb7067g) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L98)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are we also not using MANE clinical?
</blockquote></details>

based on the function used in g2t https://github.com/eastgenomics/g2t_ops/blob/main/g2t_ops/transcript_assigner.py#L36
don't think so

added a comment on function origin / inspiration
___
*[`requests_app/management/commands/_parse_transcript.py` line 137 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapWJhH6LsMxbCEVPIJ:-Naq2CUfDTMlsV0I_GUY:b-n9tkhd) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L137)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

having a trailing function call seems  weird (surprised it actually works), can it be put on the same line as the above closing parentheses?
</blockquote></details>

changed
___
*[`requests_app/management/commands/_parse_transcript.py` line 143 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapYGPz4SvRWFnk8skI:-NaptMCy43HZKEEEMhn3:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L143)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

docstring doesn't seem to cover what the function does, I think it needs something more like "Reads through gene2refseq file from HGMD database and generates a dict mapping of HGMD ID to refcore and refversion
</blockquote></details>

updated
___
*[`requests_app/management/commands/_parse_transcript.py` line 160 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-Nap_4f27tidLLp-rJ5a:-NapyjLW8XTqFrPrGRZU:bqhguls) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L160)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

pandas time:

```
>>> df = pd.read_csv('gene2refseq_202306131409.csv')
>>> df
       hgmdID  ...                                           exonENDS
0           1  ...  7333088,7518389,7579920,7587300,7595641,759743...
1           2  ...  9067839,9068224,9068842,9069813,9070578,907248...
2           3  ...                         42693997,42695631,42720910
3           4  ...  53307713,53307929,53308133,53308349,53308528,5...
4           5  ...                76467727,76468909,76469327,76470117
...       ...  ...                                                ...
11867   15596  ...  49890600,49891107,49891473,49894469,49895180,4...
11868   15597  ...  32191503,32191908,32192250,32192530,32193124,3...
11869   15598  ...  114439675,114440739,114443933,114444652,114446...
11870   15599  ...  32277765,32311181,32316319,32316649,32316874,3...
11871   15600  ...  54630633,54631107,54631306,54631787,54632237,5...

[11872 rows x 14 columns]

# turn 2 target columns into single list column
>>> df['core_plus_version'] = pd.Series(zip(df['refcore'], df['refversion'])).map(list)
>>> df
       hgmdID  ...  core_plus_version
0           1  ...     [NM_145891, 2]
1           2  ...     [NM_000014, 5]
2           3  ...     [NM_017436, 6]
3           4  ...     [NM_015665, 5]
4           5  ...     [NM_001088, 2]
...       ...  ...                ...
11867   15596  ...  [NM_001258017, 1]
11868   15597  ...     [NM_022107, 2]
11869   15598  ...     [NM_015523, 3]
11870   15599  ...     [NM_004798, 3]
11871   15600  ...  [NM_001081637, 2]

[11872 rows x 15 columns]

# turn hgmd ID and new column to dict
return dict(zip(df.hgmdID, df.core_plus_version))
```

this will return a dict formatted as `15600: ['NM_001081637', 2]` which is what we want right?
</blockquote></details>

updated with a groupby instead since we want a list of list [refcore, refversion]. very helpful
___
*[`requests_app/management/commands/_parse_transcript.py` line 167 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapX6xCB688UPLz4BJg:-NapypfnB3xmSRnZEHv9:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L167)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

 you add more detail on the markname file (i.e. use and origin)
</blockquote></details>

done
___
*[`requests_app/management/commands/_parse_transcript.py` line 248 at r11](https://reviewable.io/reviews/eastgenomics/eris/4#-NapX_etESBK_hZtn499:-Napz-rtDkT4mFtKQV5q:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/36e206d0de42ade47266ac98d8994fddc3a3c398/requests_app/management/commands/_parse_transcript.py#L248)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`.replace('HGNC:', '')` I think would be better in case the prefix gets dropped in the future
</blockquote></details>

done
___
*[`requests_app/management/commands/generate.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280401493:-Napz1I08dtuEfG2zgmF:b-94o9fh) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/generate.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

have you not pushed as it still seems to be `csv.DictReader` to me?
</blockquote></details>

ah wrong comment. this validate doesn't matter since we only want to read one row from the csv to validate the columns within
___
*[`requests_app/management/commands/generate.py` line 42 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-NakZ6bw8GymsQ_FWil8:-Naq-pThAtwb_Y3dWdgb:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L42)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

panda-fied
</blockquote></details>

done
___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-Naq0qkD6tUG4Qj61nQw:b-mqe64m) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we pandas it for speed and readability:

```
>>> hgnc = pd.read_csv('hgnc_complete_set.txt', sep='\t', low_memory=False)
>>> hgnc
          hgnc_id    symbol  ...                     mane_select       gencc
0          HGNC:5      A1BG  ...   ENST00000263100.8|NM_130786.4         NaN
1      HGNC:37133  A1BG-AS1  ...                             NaN         NaN
2      HGNC:24086      A1CF  ...   ENST00000373997.8|NM_014576.4         NaN
3          HGNC:7       A2M  ...  ENST00000318602.12|NM_000014.6      HGNC:7
4      HGNC:27057   A2M-AS1  ...                             NaN         NaN
...           ...       ...  ...                             ...         ...
43703  HGNC:25820    ZYG11B  ...   ENST00000294353.7|NM_024646.3  HGNC:25820
43704  HGNC:13200       ZYX  ...  ENST00000322764.10|NM_003461.5         NaN
43705  HGNC:51695     ZYXP1  ...                             NaN         NaN
43706  HGNC:29027     ZZEF1  ...   ENST00000381638.7|NM_015113.4         NaN
43707  [...]

2023-08-02 12:59 UTC, jethror1 requested changes
> Reviewed 2 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 55 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-NaqJDRs2AsAOfmEkR-x:b2kp8b) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

panda-fied
</blockquote></details>

doesn't this do the opposite of what you want? in the example I wrote it includes `~` before the subsetting (i.e. `~df["Locus type"]...` which matches the inverse of the condition (i.e. where "Locus type" contains 'rna' and we want to exclude)

```
df = df[
            ~df["Locus type"].str.contains("rna", case=False)
            | ~df["Approved name"].str.contains("mitochondrially encoded", case=False)
        ]

```


<!-- Sent from Reviewable.io -->

2023-08-02 13:05 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 55 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-NaqLXgG9suxUCcmhJzy:b-rx9wdq) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

doesn't this do the opposite of what you want? in the example I wrote it includes `~` before the subsetting (i.e. `~df["Locus type"]...` which matches the inverse of the condition (i.e. where "Locus type" contains 'rna' and we want to exclude)

```
df = df[
            ~df["Locus type"].str.contains("rna", case=False)
            | ~df["Approved name"].str.contains("mitochondrially encoded", case=False)
        ]

```
</blockquote></details>

I think we are trying to get the HGNC ids of those that are rnas

below is the original - if regex match, we add to set
```
 with open(file_path, "r") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                # get all rnas
                if re.search(
                    "rna",
                    row["Locus type"],
                    re.IGNORECASE,
                ) or re.search(
                    "mitochondrially encoded",
                    row["Approved name"],
                    re.IGNORECASE,
                ):
                    rnas.add(row["HGNC ID"])
```


<!-- Sent from Reviewable.io -->

2023-08-02 13:37 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 55 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 56 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nak_-r0BjvZTPS2Mg0w:-NaqSncU89N3PWU6awfk:b9cyczz) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L56)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I think we are trying to get the HGNC ids of those that are rnas

below is the original - if regex match, we add to set
```
 with open(file_path, "r") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                # get all rnas
                if re.search(
                    "rna",
                    row["Locus type"],
                    re.IGNORECASE,
                ) or re.search(
                    "mitochondrially encoded",
                    row["Approved name"],
                    re.IGNORECASE,
                ):
                    rnas.add(row["HGNC ID"])
```
</blockquote></details>

yep sorry, I can't read :facepalm: 
___
*[`requests_app/management/commands/generate.py` line 151 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nakboo03hRrPr2fkeYg:-NaqSspU82eq82KFVNvS:bvjn6ft) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L151)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this is a new command. what do you mean
</blockquote></details>

where is this actually used? struggling to understand why /where the parser object is passed from


<!-- Sent from Reviewable.io -->

2023-08-02 13:38 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 53 unresolved discussions (waiting on @oniblock and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 151 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nakboo03hRrPr2fkeYg:-NaqT73A-46iUeERLclw:b3kqx) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L151)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where is this actually used? struggling to understand why /where the parser object is passed from
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2023-08-02 13:39 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 54 unresolved discussions (waiting on @JasonLing95, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 151 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nakboo03hRrPr2fkeYg:-NaqTE2a5-9iWPWB_V4C:b-f6q0wo) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L151)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

.
</blockquote></details>

accidentally resolved this, still open


<!-- Sent from Reviewable.io -->

2023-08-02 13:41 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 54 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 151 at r7](https://reviewable.io/reviews/eastgenomics/eris/4#-Nakboo03hRrPr2fkeYg:-NaqTf9j98IsByT-Bu2q:b-ymcnzr) ([raw file](https://github.com/eastgenomics/eris/blob/5dfc775d49803ece25fc5a862d91d62d71044e74/requests_app/management/commands/generate.py#L151)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

accidentally resolved this, still open
</blockquote></details>

when generating genepanels, the handler demands a --hgnc input. However, this does not make it mandatory as generate g2t doesn't require it. The --output is optional for both genepanels and g2t as the default is just the parent directory


<!-- Sent from Reviewable.io -->

2023-08-02 13:41 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 54 unresolved discussions (waiting on @oniblock and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280401493:-NaqTqu61kmjh8D0dCF3:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/generate.py#L32)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

ah wrong comment. this validate doesn't matter since we only want to read one row from the csv to validate the columns within
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-02 13:42 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: 79 of 81 files reviewed, 54 unresolved discussions (waiting on @jethror1, @oniblock, and @Yu-jinKim)

___
*[`requests_app/management/commands/generate.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eris/4#gh-1280401493:-NaqU-bh9LcxyLO9-ObK:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/d6c239afea7f7430005b16300c337bd0558edff6/requests_app/management/commands/generate.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-02 13:58 UTC, jethror1 approved these changes
> Reviewed 1 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: all files reviewed, 52 unresolved discussions (waiting on @oniblock and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-08-02 13:59 UTC, jethror1 commented
Looks good to me now as a first version to work off, needs lots of unit tests and readme to do etc. but happy as is

Happy for it to be merged when @Yu-jinKim finishes review :tada:

2023-08-03 09:16 UTC, Yu-jinKim approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oniblock)



<!-- Sent from Reviewable.io -->

2023-08-03 09:16 UTC, merged