In 154 revisit output files
eastgenomics/eris pull request #63
Opened 2023-12-12 12:16 UTC by corbin-chris

This PR addresses ticket 154.
Changes made include:
- 'generate genepanels' now only emits clinical indication/panel and clinical indication/superpanel information for the newest test directory release in the database.
- 'g2t' now has reference-genome-sensitive transcript output. Information is output only for the most recent versions of transcript releases - older releases are ignored. Additionally, assignment of clinical or non-clinical status takes into account the changes in the database models.

'generate genepanels' runs OK:
python manage.py generate genepanels --hgnc testing_files/eris/hgnc_dump_20230606_1.txt
No output directory specified. Using default output directory: <redacted>
Creating genepanels file
Genepanel file created at <redacted>

'generate g2t' runs OK:
python manage.py generate g2t --ref_genome GRCh37
No output directory specified. Using default output directory: <redacted>
Creating g2t file for reference genome GRCh37 at 11:57:02
g2t file created at <redacted>

Unit tests are passing:
----------------------------------------------------------------------
Ran 133 tests in 4.972s

OK

2023-12-12 12:17 UTC, pep8speaks commented
Hello @corbin-chris! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`requests_app/management/commands/_parse_transcript.py`](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py):

> [Line 129:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L129): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 940:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L940): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 942:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L942): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 983:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L983): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 985:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L985): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 988:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L988): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1006:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/_parse_transcript.py#L1006): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`requests_app/management/commands/generate.py`](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py):

> [Line 52:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L52): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 57:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L57): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 68:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 74:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 86:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 100:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 106:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 110:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 129:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L129): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 159:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L159): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 199:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L199): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 212:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 224:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L224): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 255:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L255): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 265:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 267:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L267): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 273:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L273): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 295:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L295): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 329:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L329): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 331:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L331): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 333:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L333): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 348:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L348): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 349:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L349): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 364:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L364): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 365:80](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L365): [E501](https://duckduckgo.com/? [...]

2023-12-13 10:44 UTC, JasonLing95 requested changes
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/63)* status: all files reviewed, 10 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/generate.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlX_YN20rlZXEZsW9tb:-NlX_YN3CToRCtd3P4ba:b-amoop3) ([raw file](https://github.com/eastgenomics/eris/blob/42bdaf41021a95d487b87531fe6c67c3eef2d6fe/requests_app/management/commands/generate.py#L194)):*
> ```Python
>                     panel_version: str = (
>                         normalize_version(panel_dict["panel_id__panel_version"])
>                         if panel_dict["panel_id__panel_version"]
> ```

panel_id_panel__version can be null if the panel is custom-made of hgncs type
___
*[`requests_app/management/commands/generate.py` line 291 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXinp33enSHHMe2FCv:-NlXinp33enSHHMe2FCw:byrq2m7) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L291)):*
> ```Python
>         """
>         errors = []
>         if not ClinicalIndicationPanel.objects.filter(current=True).exists():
> ```

see below
___
*[`requests_app/management/commands/generate.py` line 299 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXihesC_1SU7tnDphb:-NlXihesC_1SU7tnDphc:b-412gs4) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L299)):*
> ```Python
>             )
> 
>         if not TestDirectoryRelease.objects.all().exists():
> ```

if they both indicate the same thing, might be best to join them together
___
*[`requests_app/management/commands/generate.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXhhvS53MKpfyV20Cm:-NlXhhvS53MKpfyV20Cn:bqafk5c) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L307)):*
> ```Python
> 
>         # block generation of genepanel.tsv if ANY data is awaiting review (pending=True)
>         if ClinicalIndicationPanel.objects.filter(pending=True).exists():
> ```

this block might not be necessary tho because when we generate genepanel, we are getting those with current true and pending false anyway. If this block is here, it will mean we will never be able to generate genepanel with stuff pending. - also mean we don't need the check for pending False down the line because it will be blocked at this stage

What if there is a scenario which is abit tough to resolve in manual review and the decision is to generate a genepanel without them first then come back to resolve it, this block will make it tough.
___
*[`requests_app/management/commands/generate.py` line 315 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXidGS8v_QWPDVJW4r:-NlXidGS8v_QWPDVJW4s:b4pkm7w) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L315)):*
> ```Python
>         # block generation of genepanel.tsv if ANY data is awaiting review
>         # (pending=True)
>         if ClinicalIndicationSuperPanel.objects.filter(pending=True).exists():
> ```

same for here
___
*[`requests_app/management/commands/generate.py` line 325 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXaVX57HfIbl3VVp1F:-NlXaVX57HfIbl3VVp1G:b-x3991w) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L325)):*
> ```Python
>         if errors:
>             msg = "; ".join(errors)
>             return msg
> ```

raise ValueError here instead of returning it and raising it in parent function
___
*[`requests_app/management/commands/generate.py` line 339 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXaOG3DaNfauNasFnd:-NlXaOG3DaNfauNasFne:b-rz9ksd) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L339)):*
> ```Python
>         print("Creating genepanels file")
> 
>         errors = self._block_genepanels_if_db_not_ready()
> ```

you could have raised the error within the function rather than returning the error from the function then raising it in this function instead
___
*[`requests_app/management/commands/generate.py` line 551 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXfS948IfhpAXi7yFh:-NlXfS948IfhpAXi7yFi:b-xup5uw) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L551)):*
> ```Python
>             parsed_genome = _parse_reference_genome(kwargs.get("ref_genome"))
> 
>             try:
> ```

the whole thing shouldn't be lump into the try exception clause, just the ReferenceGenome.objects.get()
___
*[`tests/tests_requests_app/test_management/test_commands/test_generate/test_get_current_transcript_clinical_status_for_g2t.py` line 150 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXjg9c9pJhEQ-h0m1V:-NlXjg9c9pJhEQ-h0m1W:bd8mpju) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/tests/tests_requests_app/test_management/test_commands/test_generate/test_get_current_transcript_clinical_status_for_g2t.py#L150)):*
> ```Python
>             self.transcript, self.mane_select_rel, self.mane_plus_rel, self.hgmd_rel
>         )
>         assert not clinical
> ```

might be clearer to assert clinical is None since that's what we expect. not clinical might mean False as well
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_check_for_transcript_seeding_version_regression.py` line 87 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXlaDV4rZoLeo2hyxb:-NlXlaDV4rZoLeo2hyxc:bc255dq) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_check_for_transcript_seeding_version_regression.py#L87)):*
> ```Python
>         new_hgmd = "1.9.0"  # too old, uses subversioning
> 
>         expected_err = "Abandoning input because: hgnc release is a lower version than 2; hgmd release is a lower version than 2"
> ```

this expected error is not used anywhere


<!-- Sent from Reviewable.io -->

2023-12-19 12:07 UTC, corbin-chris reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/63#-:-Nm0WT0E3u6euXv3GZsj:bb6un1j)* status: 17 of 22 files reviewed, 10 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/generate.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlX_YN20rlZXEZsW9tb:-NlY91sYCZIf1gE9KHws:bs7wumx) ([raw file](https://github.com/eastgenomics/eris/blob/42bdaf41021a95d487b87531fe6c67c3eef2d6fe/requests_app/management/commands/generate.py#L194)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

panel_id_panel__version can be null if the panel is custom-made of hgncs type
</blockquote></details>

Done. 
___
*[`requests_app/management/commands/generate.py` line 291 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXinp33enSHHMe2FCv:-NlY9IWN1DbQlfFzDCC2:b89sqyi) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L291)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

see below
</blockquote></details>

Done now just using TestDirectory directly, rather than ClinicalIndicationPanel, which is basically a proxy for the same thing
___
*[`requests_app/management/commands/generate.py` line 299 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXihesC_1SU7tnDphb:-NlY9PbXEvnPBQfXgs3N:b-v49844) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L299)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

if they both indicate the same thing, might be best to join them together
</blockquote></details>

Done  now just using TestDirectory directly, rather than ClinicalIndicationPanel, which is basically a proxy for the same thing
___
*[`requests_app/management/commands/generate.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXhhvS53MKpfyV20Cm:-NlY9ssk80By7JvdWGhx:b-wew1p3) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L307)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this block might not be necessary tho because when we generate genepanel, we are getting those with current true and pending false anyway. If this block is here, it will mean we will never be able to generate genepanel with stuff pending. - also mean we don't need the check for pending False down the line because it will be blocked at this stage

What if there is a scenario which is abit tough to resolve in manual review and the decision is to generate a genepanel without them first then come back to resolve it, this block will make it tough.
</blockquote></details>

Done Discussed over past week: Team consensus is that blocking output until pending data is resolved, is the desired pattern
___
*[`requests_app/management/commands/generate.py` line 315 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXidGS8v_QWPDVJW4r:-Nm0WN3P0KlSLUxxdOxN:b-wew1p3) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L315)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for here
</blockquote></details>

Done Discussed over past week: Team consensus is that blocking output until pending data is resolved, is the desired pattern
___
*[`requests_app/management/commands/generate.py` line 325 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXaVX57HfIbl3VVp1F:-NlYCi2lENCyswuUndw-:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L325)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

raise ValueError here instead of returning it and raising it in parent function
</blockquote></details>

Done.
___
*[`requests_app/management/commands/generate.py` line 339 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXaOG3DaNfauNasFnd:-NlYChcV8c0y9oI-FSox:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L339)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

you could have raised the error within the function rather than returning the error from the function then raising it in this function instead
</blockquote></details>

Done.
___
*[`requests_app/management/commands/generate.py` line 551 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXfS948IfhpAXi7yFh:-NlYDFrV4kyeW65lUEi7:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/requests_app/management/commands/generate.py#L551)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the whole thing shouldn't be lump into the try exception clause, just the ReferenceGenome.objects.get()
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_generate/test_get_current_transcript_clinical_status_for_g2t.py` line 150 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXjg9c9pJhEQ-h0m1V:-NldS1-F8ETtraPfu-sy:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/tests/tests_requests_app/test_management/test_commands/test_generate/test_get_current_transcript_clinical_status_for_g2t.py#L150)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

might be clearer to assert clinical is None since that's what we expect. not clinical might mean False as well
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_check_for_transcript_seeding_version_regression.py` line 87 at r1](https://reviewable.io/reviews/eastgenomics/eris/63#-NlXlaDV4rZoLeo2hyxb:-Nm0VvPdC9AKjYau_ABQ:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/15b273e6d676f3282ca4672bdd703723d6356cb8/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_check_for_transcript_seeding_version_regression.py#L87)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this expected error is not used anywhere
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-19 12:19 UTC, JasonLing95 approved these changes
> Reviewed 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/63)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)



<!-- Sent from Reviewable.io -->

2023-12-19 12:26 UTC, merged