IN-369 Frontend Index Page
eastgenomics/eris pull request #64
Opened 2023-12-13 16:07 UTC by JasonLing95

- fix index page displaying for CI, Panel, TdRelease, Genes
- PR getting too big as there are too many changes so I'm going to open PR for the index page first. Other part of the UI will be smaller PR to review
- A few other pages has been commented out for later PR - g2t, genepanel, seed (for td seed)

NOTE: Eris is on dev server now as demo. Currently only three pages are available: index, history, manual review and seed. (UPDATE) it's not! there's some networking issue. Still getting it to work. OK IT'S WORKING NOW!

```
Found 117 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
.....................Start 2 gene bulk create: 14:52:23
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
....Preparing HGNC files
Start bulk-updating 2 gene symbols: 14:52:23
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 14:52:23
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 14:52:23
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 14:52:23
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 14:52:23
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 14:52:23
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 14:52:23
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 14:52:23
................Start bulk-updating 1 gene symbols: 14:52:23
.Start bulk-updating 2 gene symbols: 14:52:23
.
----------------------------------------------------------------------
Ran 117 tests in 5.034s

OK
Destroying test database for alias 'default'...
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eris/64)

2023-12-13 16:07 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`requests_app/management/commands/history.py`](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/requests_app/management/commands/history.py):

> [Line 73:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/requests_app/management/commands/history.py#L73): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`web/forms.py`](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/forms.py):

> [Line 41:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/forms.py#L41): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 69:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/forms.py#L69): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 93:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/forms.py#L93): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`web/urls.py`](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/urls.py):

> [Line 10:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/urls.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`web/views.py`](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py):

> [Line 107:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 122:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L122): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 168:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 251:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L251): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 316:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L316): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 338:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L338): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 347:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L347): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (150 > 79 characters)
> [Line 349:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L349): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 410:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L410): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 505:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L505): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 515:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L515): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 533:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L533): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 751:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L751): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 758:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L758): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 764:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L764): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 769:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L769): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 787:1](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L787): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 929:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L929): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 1028:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1028): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 1232:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1232): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 1278:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1278): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1280:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1280): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1281:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1281): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 1284:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1284): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 1312:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1312): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 1318:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1318): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 1336:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1336): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 1339:80](https://github.com/eastgenomics/eris/blob/2ad3af3ca03a55edd6a293f666643e854378ee96/web/views.py#L1339): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

2023-12-14 12:38 UTC, corbin-chris requested changes
> Reviewed 22 of 28 files at r1, 14 of 14 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/64)* status: all files reviewed, 13 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`docker-compose.yml` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-Nlbl2OFEhKIF31nY2nl:-Nlbl2OFEhKIF31nY2nm:b1x7lrl) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/docker-compose.yml#L38)):*
> ```YAML
>     volumes:
>       - eris_static:/staticfiles
>       - /Users/jason/Github/eris/nginx:/etc/nginx/conf.d
> ```

Should this path be left in? (E.g. is it a server path or a local one?) Does it need to update based on LOCALHOST status or anything like that?
___
*[`web/forms.py` line 34 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlbmCwK4vfl3nlmujzz:-NlbmCwK4vfl3nlmuk--:b-g1laoi) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/forms.py#L34)):*
> ```Python
>     panel_version = forms.CharField(max_length=10, required=False)
> 
>     def clean(self):
> ```

Could you please add a docstring with a short summary of how these are cleaned? It looks like it's checking for pre-existing panels before it lets you add data - in which case you might want a more descriptive name too, such as 'check_panel_unique' or whatever.
Also please outline how you're dealing with HGNC-joined panel names now.
Some of the forms are fairly self-explanatory but I'd like docstrings at the top of all your functions please. It'll save time for future devs (or you, when you're had 1-2 years to forget everything, then people want an updated version)
___
*[`web/forms.py` line 90 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlbnAh74jHwJjiNezSK:-NlbnAh74jHwJjiNezSL:b-47sx65) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/forms.py#L90)):*
> ```Python
>         return hgnc_id
> 
>     def clean_gene_symbol(self):
> ```

Same as above RE docstrings/descriptive name
___
*[`web/views.py` line 716 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcEudt2xTHVrwzisp6:-NlcEudt2xTHVrwzisp7:b-axnyxg) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L716)):*
> ```Python
>     """
> 
>     if request.method == "GET":
> ```

Do you need to use the atomic transaction wrapper up here? As you're changing things on multiple tables, and need to avoid the transaction failing without roll-back partway through (e.g. you could end up up with History writing for an event that never reaches the db - .save() runs at different times from objects.create() I think)

If yes, double-check other functions that handle user-changes, too.
___
*[`web/views.py` line 846 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcFV6O3JT7pmZyjypg:-NlcFV6O3JT7pmZyjyph:b-3ucek8) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L846)):*
> ```Python
>     - PanelRegion (TODO)
>     - PanelTestMethod (TODO)
>     """
> ```

Add :param: for request. You've missed this in a few spots
___
*[`web/views.py` line 1026 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcF_qj4eRll7mURRiU:-NlcF_qj4eRll7mURRiV:bf1lhrl) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1026)):*
> ```Python
> 
>     Args:
>         gene_id (int): gene id
> ```

Add :param: for request? You've missed this in a few spots
Tell us about the returns too
___
*[`web/views.py` line 1201 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcFv5j0y5DBPdn52aK:-NlcFv5j0y5DBPdn52aL:by41q7n) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1201)):*
> ```Python
> def add_gene(request):
>     """
>     url name "gene_add"
> ```

More detail please
___
*[`web/views.py` line 1385 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcG7toBURZfXN_YWVL:-NlcG7toBURZfXN_YWVM:b-zahhj8) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1385)):*
> ```Python
>     """
>     This page allows file upload (test directory json file)
>     and will insert the data into the database
> ```

Describe the 'force' args behaviour here please (in case you get a future dev on the front-end who hasn't worked with the back-end scripts so much, and isn't familiar)
___
*[`web/templates/web/addition/add_gene.html` line 14 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcJ7EhCCAiOcMUG-WM:-NlcJ7EhCCAiOcMUG-WN:bw600sh) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/addition/add_gene.html#L14)):*
> ```HTML
>                 {% for key, values in errors.items %}
>                 {% for error in values %}
>                 <strong>Beep!</strong> {{ error }}
> ```

Needs changing to something more useful
___
*[`web/templates/web/addition/add_panel.html` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcJA7pA-AGYpZK3V37:-NlcJA7pA-AGYpZK3V38:b-w807aw) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/addition/add_panel.html#L13)):*
> ```HTML
>         {% for key, values in errors.items %}
>         {% for error in values %}
>         <strong>Beep!</strong> {{ error }}
> ```

Needs to be more useful message
___
*[`web/templates/web/info/clinical_indication.html` line 84 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcC8RWEeZ3VGERCqAx:-NlcC8RWEeZ3VGERCqAy:bsqfrag) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/info/clinical_indication.html#L84)):*
> ```HTML
>         <div class="col">
>             <h3>Test Method History</h3>
>             <p class="fs-6 text-muted">all previous modiciations to test method</p>
> ```

Typo: 'modifications'
___
*[`web/templates/web/addition/add_clinical_indication.html` line 13 at r3](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcIfEK8zQoyiaFEbjT:-NlcIfEK8zQoyiaFEbjU:baay2a5) ([raw file](https://github.com/eastgenomics/eris/blob/1b030f5d4c441795b9eada5136ea97de7b03ba80/web/templates/web/addition/add_clinical_indication.html#L13)):*
> ```HTML
>                 {% for key, values in errors.items %}
>                 {% for error in values %}
>                 <strong>Beep!</strong> {{ error }}
> ```

Does this literally print 'Beep!' ? If so it's probably best to print 'Error' instead, before the error message
___
*[`web/templates/web/addition/add_clinical_indication.html` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcIuK_6Gc_dwzROC5r:-NlcIuK_6Gc_dwzROC5s:babsjyw) ([raw file](https://github.com/eastgenomics/eris/blob/42bdaf41021a95d487b87531fe6c67c3eef2d6fe/web/templates/web/addition/add_clinical_indication.html#L24)):*
> ```HTML
>             <!-- end error message -->
>             <!-- success message -->
>             {% if success %}
> ```

Why did you remove the success message? Is there still some easy way for the end user to see whether things worked OK? Thinking about how people might try to double-submit stuff otherwise.


<!-- Sent from Reviewable.io -->

2023-12-14 17:06 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/64)* status: 35 of 36 files reviewed, 12 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`docker-compose.yml` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-Nlbl2OFEhKIF31nY2nl:-NldCOCd6XWbARsFTsZa:b-xrlzb5) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/docker-compose.yml#L38)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Should this path be left in? (E.g. is it a server path or a local one?) Does it need to update based on LOCALHOST status or anything like that?
</blockquote></details>

nope, this is more of a placeholder. The one on dev server will have a different pathway depending on how it is mounted on dev
___
*[`web/forms.py` line 34 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlbmCwK4vfl3nlmujzz:-NldCVtO2zRKMcyYm7fL:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/forms.py#L34)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please add a docstring with a short summary of how these are cleaned? It looks like it's checking for pre-existing panels before it lets you add data - in which case you might want a more descriptive name too, such as 'check_panel_unique' or whatever.
Also please outline how you're dealing with HGNC-joined panel names now.
Some of the forms are fairly self-explanatory but I'd like docstrings at the top of all your functions please. It'll save time for future devs (or you, when you're had 1-2 years to forget everything, then people want an updated version)
</blockquote></details>

done
___
*[`web/forms.py` line 90 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlbnAh74jHwJjiNezSK:-NldDOg65UjAjbIZzVsI:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/forms.py#L90)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Same as above RE docstrings/descriptive name
</blockquote></details>

done
___
*[`web/views.py` line 716 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcEudt2xTHVrwzisp6:-NldHhisAKa9eGiMDXzV:bz67hqw) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L716)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Do you need to use the atomic transaction wrapper up here? As you're changing things on multiple tables, and need to avoid the transaction failing without roll-back partway through (e.g. you could end up up with History writing for an event that never reaches the db - .save() runs at different times from objects.create() I think)

If yes, double-check other functions that handle user-changes, too.
</blockquote></details>

wrapped those parts where it involves multiple db tables
___
*[`web/views.py` line 846 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcFV6O3JT7pmZyjypg:-NldGOMz7dAxRMPiLFMA:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L846)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add :param: for request. You've missed this in a few spots
</blockquote></details>

done
___
*[`web/views.py` line 1026 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcF_qj4eRll7mURRiU:-NldGOsn6PDQweSmjXRS:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1026)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add :param: for request? You've missed this in a few spots
Tell us about the returns too
</blockquote></details>

done
___
*[`web/views.py` line 1201 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcFv5j0y5DBPdn52aK:-NldHllk3iw2vu8399u7:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1201)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

More detail please
</blockquote></details>

done
___
*[`web/views.py` line 1385 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcG7toBURZfXN_YWVL:-NldGUhqC6qyvDmWq-MW:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L1385)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Describe the 'force' args behaviour here please (in case you get a future dev on the front-end who hasn't worked with the back-end scripts so much, and isn't familiar)
</blockquote></details>

done
___
*[`web/templates/web/addition/add_gene.html` line 14 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcJ7EhCCAiOcMUG-WM:-NldHOlD6_SnPcqlCbGj:b-7g26go) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/addition/add_gene.html#L14)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Needs changing to something more useful
</blockquote></details>

the {{error}} is fluid in the sense that it will return any validation error returned from the form validation at the backend
___
*[`web/templates/web/addition/add_panel.html` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcJA7pA-AGYpZK3V37:-NldHa_FEi8Pflj07ASA:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/addition/add_panel.html#L13)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Needs to be more useful message
</blockquote></details>

done
___
*[`web/templates/web/info/clinical_indication.html` line 84 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcC8RWEeZ3VGERCqAx:-NldHf0S48u3P2XWH10Z:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/info/clinical_indication.html#L84)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Typo: 'modifications'
</blockquote></details>

done
___
*[`web/templates/web/addition/add_clinical_indication.html` line 13 at r3](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcIfEK8zQoyiaFEbjT:-NldHNfc-tV3RLONFASV:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/1b030f5d4c441795b9eada5136ea97de7b03ba80/web/templates/web/addition/add_clinical_indication.html#L13)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Does this literally print 'Beep!' ? If so it's probably best to print 'Error' instead, before the error message
</blockquote></details>

done
___
*[`web/templates/web/addition/add_clinical_indication.html` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcIuK_6Gc_dwzROC5r:-NldHIka3XwpaF9B8jCn:bw1h0ai) ([raw file](https://github.com/eastgenomics/eris/blob/42bdaf41021a95d487b87531fe6c67c3eef2d6fe/web/templates/web/addition/add_clinical_indication.html#L24)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Why did you remove the success message? Is there still some easy way for the end user to see whether things worked OK? Thinking about how people might try to double-submit stuff otherwise.
</blockquote></details>

yup now we redirect them to the ci-panel or panel or ci when form is correct


<!-- Sent from Reviewable.io -->

2023-12-19 12:23 UTC, corbin-chris approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/64)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

___
*[`docker-compose.yml` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-Nlbl2OFEhKIF31nY2nl:-Nm0zAZkCDzvnEvMC0La:b4k9wcm) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/docker-compose.yml#L38)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

nope, this is more of a placeholder. The one on dev server will have a different pathway depending on how it is mounted on dev
</blockquote></details>

Done sure, as long as it won't cause issues/wasn't accidental
___
*[`web/views.py` line 716 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcEudt2xTHVrwzisp6:-Nm10n0bB8rKUMuGSIQu:bzbw1s) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/views.py#L716)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

wrapped those parts where it involves multiple db tables
</blockquote></details>

Done looks better now - we'll try to knock it over at integration testing so we'll see then
___
*[`web/templates/web/addition/add_gene.html` line 14 at r2](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcJ7EhCCAiOcMUG-WM:-Nm10VKt0Klfq3oJggfs:bscx0h6) ([raw file](https://github.com/eastgenomics/eris/blob/53e728a5ca7be5109140c7131be2a89951ab27d9/web/templates/web/addition/add_gene.html#L14)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the {{error}} is fluid in the sense that it will return any validation error returned from the form validation at the backend
</blockquote></details>

Done I was referring to the fact that you printed the word Beep here instead of Error, but you fixed that too, so, fine.
___
*[`web/templates/web/addition/add_clinical_indication.html` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eris/64#-NlcIuK_6Gc_dwzROC5r:-Nm10BnG2Ftk9eVJx-mp:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/42bdaf41021a95d487b87531fe6c67c3eef2d6fe/web/templates/web/addition/add_clinical_indication.html#L24)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

yup now we redirect them to the ci-panel or panel or ci when form is correct
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-19 12:23 UTC, merged