IN-387: FrontEnd GenePanel
eastgenomics/eris pull request #67
Opened 2023-12-20 15:07 UTC by JasonLing95

- genepanel page: displaying clinical-indication, their panel and genes linked to the panel
- if superpanel, it will display all genes under all their child panels
- require upload of HGNCs for genepanels generation

```
Found 133 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
.....................Start 2 gene bulk create: 15:07:05
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
....Preparing HGNC files
Start bulk-updating 2 gene symbols: 15:07:05
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 15:07:05
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 15:07:05
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 15:07:05
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 15:07:05
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 15:07:06
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 15:07:06
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 15:07:06
................Start bulk-updating 1 gene symbols: 15:07:06
.Start bulk-updating 2 gene symbols: 15:07:06
.
----------------------------------------------------------------------
Ran 133 tests in 4.248s

OK
Destroying test database for alias 'default'...
```

2023-12-20 15:07 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`requests_app/management/commands/_parse_transcript.py`](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/_parse_transcript.py):

> [Line 379:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/_parse_transcript.py#L379): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 385:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/_parse_transcript.py#L385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

* In the file [`requests_app/management/commands/generate.py`](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/generate.py):

> [Line 65:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/generate.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

* In the file [`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py`](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py):

> [Line 5:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L5): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 35:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 46:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 50:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L50): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 55:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L55): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 68:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_sanity_check_cols_exist.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)



* In the file [`web/views.py`](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py):

> [Line 5:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L5): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1074:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1074): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 1095:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1095): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 1097:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1097): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1119:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1207:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1207): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1232:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1232): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 1292:80](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1292): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2023-12-20 16:54 UTC, corbin-chris requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/67)* status: all files reviewed, 8 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 383 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm73mo1Az_698juuDzX:-Nm73mo1Az_698juuDzY:b-zd5tq9) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/_parse_transcript.py#L383)):*
> ```Python
>     :param: df - a Pandas Dataframe
>     :param: columns - a list of column names to check for
>     :param: filename - file name to be used in error message
> ```

Please remove 'filename' parameter as it isn't needed anymore
___
*[`web/views.py` line 1068 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm74FkJ7GEueN6-9A4g:-Nm74FkJ7GEueN6-9A4h:b-e2j7rg) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1068)):*
> ```Python
> 
> 
> def _parse_excluded_hgncs_from_bytes(file: TemporaryUploadedFile) -> set[str]:
> ```

Add a docstring please - explain why you're looking for "rna" and "mitochondrially encoded" here
I see its usage is commented out though - is this going to be used once you have an upload file?
___
*[`web/views.py` line 1094 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm74tixEwbxgnF25z47:-Nm74tixEwbxgnF25z48:b-a1d202) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1094)):*
> ```Python
>     warnings = []
> 
>     # TODO: hard-coded, will become an upload file in the future
> ```

Is this still a todo? Looks like you're getting your excluded RNAs from file-parsing further down this page.
___
*[`web/views.py` line 1141 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75CEj8JwDK5aKJNET:-Nm75CEj8JwDK5aKJNEU:bzfbn7v) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1141)):*
> ```Python
>             normalize_version(row["panel_id__panel_version"])
>             if row["panel_id__panel_version"]
>             else "1.0",
> ```

Don't default to a version please - display None or "None" instead.
My reasoning is that if there isn't a version, something has probably gone wrong (as it should be added as a mandatory input either at seeding or by the user), and if we mask it it'll cause us trouble.
___
*[`web/views.py` line 1178 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75bVIAY6Z5e5a-PWk:-Nm75bVIAY6Z5e5a-PWl:b-rv5m8i) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1178)):*
> ```Python
>             normalize_version(row["superpanel_id__panel_version"])
>             if row["superpanel_id__panel_version"]
>             else "1.0",
> ```

Same feedback as for regular-panels, RE not defaulting to 1.0 as a display value.
___
*[`web/views.py` line 1199 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75ii7-xuWGgSU7tjg:-Nm75ii7-xuWGgSU7tjh:bs0umy0) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1199)):*
> ```Python
>                     normalize_version(child_panel["panel_id__panel_version"])
>                     if child_panel["panel_id__panel_version"]
>                     else "1.0",
> ```

As before
___
*[`web/views.py` line 1215 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm77RlQ65ZA2HnwFcSH:-Nm77RlQ65ZA2HnwFcSI:btqnw56) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1215)):*
> ```Python
>                 panel_id_to_genes[panel_id].append(GeneClass(gene_id, hgnc_id))
> 
>                 genepanel.hgncs.append(GeneClass(gene_id, hgnc_id))
> ```

Is it possible to write a function and reuse some of the code you used for (regular) panels, when you format the child-panel data here?
___
*[`web/utils/utils.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm78Mep4HK1UxNFG6Nt:-Nm78Mep4HK1UxNFG6Nu:bprym05) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/utils/utils.py#L6)):*
> ```Python
> 
> 
> class ChildPanelClass:
> ```

To make it even clearer could you please name these to something like 'WebChildPanel' 'WebGene' and 'WebGenePanel'?


<!-- Sent from Reviewable.io -->

2023-12-21 10:14 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/67)* status: all files reviewed, 7 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 383 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm73mo1Az_698juuDzX:-NmAn3el5Sq-Qt9s3qEq:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/requests_app/management/commands/_parse_transcript.py#L383)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please remove 'filename' parameter as it isn't needed anymore
</blockquote></details>

done
___
*[`web/views.py` line 1068 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm74FkJ7GEueN6-9A4g:-NmAnlWQA_B2Gqu7OYnF:b-1jlpfa) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1068)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add a docstring please - explain why you're looking for "rna" and "mitochondrially encoded" here
I see its usage is commented out though - is this going to be used once you have an upload file?
</blockquote></details>

done  I removed the one that I don't use from the import. 
___
*[`web/views.py` line 1094 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm74tixEwbxgnF25z47:-NmAnt0W2JuSM2PCdSv6:b-rptv3h) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1094)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is this still a todo? Looks like you're getting your excluded RNAs from file-parsing further down this page.
</blockquote></details>

done yes now it's no longer hard-coded but file upload is available
___
*[`web/views.py` line 1141 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75CEj8JwDK5aKJNET:-NmAo7RC2EbQeVIH24Rb:bqeisgl) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1141)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Don't default to a version please - display None or "None" instead.
My reasoning is that if there isn't a version, something has probably gone wrong (as it should be added as a mandatory input either at seeding or by the user), and if we mask it it'll cause us trouble.
</blockquote></details>

I've defaulted them to None - HGNCs type panel typically have no version.
___
*[`web/views.py` line 1178 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75bVIAY6Z5e5a-PWk:-NmAocPb7FB85uuhgWL9:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1178)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Same feedback as for regular-panels, RE not defaulting to 1.0 as a display value.
</blockquote></details>

done
___
*[`web/views.py` line 1199 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm75ii7-xuWGgSU7tjg:-NmAod0O9KqYXEDXP5-g:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1199)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

As before
</blockquote></details>

done
___
*[`web/views.py` line 1215 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm77RlQ65ZA2HnwFcSH:-NmApcxV6cZEIJ1b95cG:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/views.py#L1215)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is it possible to write a function and reuse some of the code you used for (regular) panels, when you format the child-panel data here?
</blockquote></details>

done
___
*[`web/utils/utils.py` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eris/67#-Nm78Mep4HK1UxNFG6Nt:-NmArVV8-dBIWsiGbXdv:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/33e0e09b66f65a7deda75646e7a0205ba9278346/web/utils/utils.py#L6)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

To make it even clearer could you please name these to something like 'WebChildPanel' 'WebGene' and 'WebGenePanel'?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-21 10:45 UTC, corbin-chris approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)



<!-- Sent from Reviewable.io -->

2023-12-21 10:45 UTC, merged