FrontEnd: generate g2t from frontend
eastgenomics/eris pull request #69
Opened 2024-01-03 13:16 UTC by JasonLing95

2024-01-03 13:16 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`panels_backend/management/commands/_parse_transcript.py`](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/_parse_transcript.py):

> [Line 959:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/_parse_transcript.py#L959): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 993:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/_parse_transcript.py#L993): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1178:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/_parse_transcript.py#L1178): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

* In the file [`panels_backend/management/commands/generate.py`](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/generate.py):

> [Line 422:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_backend/management/commands/generate.py#L422): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)



* In the file [`panels_web/views.py`](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py):

> [Line 1432:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1432): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 1487:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1487): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1523:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1523): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 1565:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1565): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1569:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1569): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1594:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1594): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1597:80](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1597): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2024-01-04 12:59 UTC, corbin-chris requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/69)* status: all files reviewed, 9 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_web/views.py` line 61 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJCawxCM27l6n_CtPv:-NnJCawxCM27l6n_CtPw:bu89f2c) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L61)):*
> ```Python
> def index(request: HttpRequest) -> HttpResponse:
>     """
>     Main page. Display all clinical indications and panels
> ```

Please update this to say that you display clinical indications, panels, Test Directory releases and transcript sources (assuming these get displayed on the final page seen by the user)
___
*[`panels_web/views.py` line 1439 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJNk3p9nOBxGqN5zxs:-NnJNk3p9nOBxGqN5zxt:b-59cnm6) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1439)):*
> ```Python
> 
>     Returns:
>         list of transcripts with clinical context
> ```

Might be worth writing that the keys of the dictionaries in this list, are: hgnc_id, gene_id, transcript, clinical, source, source_id
I wouldn't normally fuss about it, but it makes it easier to see what's happening when you use this in 'ajax_gene_transcripts'
___
*[`panels_web/views.py` line 1487 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKEcF5wMlCE7VJjfO:-NnJKEcF5wMlCE7VJjfP:boqhh4f) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1487)):*
> ```Python
> 
> 
> def ajax_gene_transcripts(request: HttpRequest, reference_genome: str) -> JsonResponse:
> ```

Please give this a docstring explaining what it's for and what it returns. Looks to me like it 
___
*[`panels_web/views.py` line 1508 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJON-xBx9Onqgd1ka2:-NnJON-xBx9Onqgd1ka3:bufa3dp) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1508)):*
> ```Python
>                         "clinical": None,
>                         "source": None,
>                     }
> ```

_giving_transcript_clinical_context returns a list-of-dicts with keys: hgnc_id, gene_id, transcript, clinical, source, source_id
Do you need to add "gene_id": None and "source_id": None to this JsonResponse? Or will the front-end functions still work OK without them?
___
*[`panels_web/views.py` line 1532 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJPQ717TNULPt_SLvv:-NnJPQ717TNULPt_SLvw:b-7a0hy6) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1532)):*
> ```Python
> def genetranscripts(request: HttpRequest) -> HttpResponse:
>     """
>     g2t page where it display gene and their transcripts (clinical and non-clinical)
> ```

Please add a line to mention that this function allows users to generate files and send them directly to a DNAnexus project.
___
*[`panels_web/views.py` line 1539 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKPQ91D56RTCBy5VT:-NnJKPQ91D56RTCBy5VU:b-c1ph3q) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1539)):*
> ```Python
> 
>     For transcript of different TranscriptRelease, this should be viewed under individual
>     gene page which is more detailed
> ```

Add your args/returns in this block please
___
*[`panels_web/views.py` line 1604 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKUsI1SZWbZ9XyMlC:-NnJKUsI1SZWbZ9XyMlD:bpyf239) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1604)):*
> ```Python
> def transcript_source(request: HttpRequest, ts_id: int) -> HttpResponse:
>     """
>     Page to view transcript source information and its releases
> ```

Add args/returns
___
*[`panels_web/templates/web/info/genetranscripts.html` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJPr_SBN2MMhZEJK88:-NnJPr_SBN2MMhZEJK89:b-rpx76m) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/templates/web/info/genetranscripts.html#L4)):*
> ```HTML
> {% load static %}
> 
> <!-- TODO: Revisit this page -->
> ```

Just checking - is this todo still current?
___
*[`panels_web/templates/web/info/genetranscripts.html` line 94 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJV6Np0C3EwpwcnKVv:-NnJV6Np0C3EwpwcnKVw:bzb4cr7) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/templates/web/info/genetranscripts.html#L94)):*
> ```HTML
>             <th scope="col">Transcript</th>
>             <th scope="col">Sources</th>
>             <th scoope="col">Clinical Sources</th>
> ```

Should this be 'Clinical Status' instead of 'Clinical Sources'?


<!-- Sent from Reviewable.io -->

2024-01-05 13:34 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/69)* status: all files reviewed, 9 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`panels_web/views.py` line 61 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJCawxCM27l6n_CtPv:-NnOn4sQ3WjoAepIrB-S:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L61)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please update this to say that you display clinical indications, panels, Test Directory releases and transcript sources (assuming these get displayed on the final page seen by the user)
</blockquote></details>

done
___
*[`panels_web/views.py` line 1439 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJNk3p9nOBxGqN5zxs:-NnOnaAM8UUHv0omtCxd:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1439)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Might be worth writing that the keys of the dictionaries in this list, are: hgnc_id, gene_id, transcript, clinical, source, source_id
I wouldn't normally fuss about it, but it makes it easier to see what's happening when you use this in 'ajax_gene_transcripts'
</blockquote></details>

done
___
*[`panels_web/views.py` line 1487 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKEcF5wMlCE7VJjfO:-NnOnbOD3eUXtVPMRPWH:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1487)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please give this a docstring explaining what it's for and what it returns. Looks to me like it
</blockquote></details>

done
___
*[`panels_web/views.py` line 1508 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJON-xBx9Onqgd1ka2:-NnOo-AB96yEgS4dbP_w:b-i1rgtw) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1508)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

_giving_transcript_clinical_context returns a list-of-dicts with keys: hgnc_id, gene_id, transcript, clinical, source, source_id
Do you need to add "gene_id": None and "source_id": None to this JsonResponse? Or will the front-end functions still work OK without them?
</blockquote></details>

without them is ok since they don't populate the table in the front-end so it wouldn't cause an error
___
*[`panels_web/views.py` line 1532 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJPQ717TNULPt_SLvv:-NnOoRk27fZFUiZl4yX5:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1532)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please add a line to mention that this function allows users to generate files and send them directly to a DNAnexus project.
</blockquote></details>

done
___
*[`panels_web/views.py` line 1539 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKPQ91D56RTCBy5VT:-NnOoVd1EH_ZiUISNMJ_:bfa2q0t) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1539)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add your args/returns in this block please
</blockquote></details>

not sure what to write for args and returns because it doesn't really take any argument on get request. In post request, it doesn't really take anything or return anything other than a success msg if the g2t file got generated successfully on dnanexus
___
*[`panels_web/views.py` line 1604 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJKUsI1SZWbZ9XyMlC:-NnOoxvMCfte9iun9l3U:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/views.py#L1604)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add args/returns
</blockquote></details>

done
___
*[`panels_web/templates/web/info/genetranscripts.html` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJPr_SBN2MMhZEJK88:-NnOp0VeEsKa6YtxXLbY:bkj6u61) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/templates/web/info/genetranscripts.html#L4)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Just checking - is this todo still current?
</blockquote></details>

removed. it's no longer a todo
___
*[`panels_web/templates/web/info/genetranscripts.html` line 94 at r1](https://reviewable.io/reviews/eastgenomics/eris/69#-NnJV6Np0C3EwpwcnKVv:-NnOp5iB86Q0LxQkfqvE:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/072cf627cefb6475dc86d8ed9d3b18ecc915fb90/panels_web/templates/web/info/genetranscripts.html#L94)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Should this be 'Clinical Status' instead of 'Clinical Sources'?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-05 14:23 UTC, corbin-chris approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/69)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-01-05 14:24 UTC, merged