In 435 accept genome patch versions
eastgenomics/eris pull request #83
Opened 2024-01-31 10:40 UTC by corbin-chris

panels_backend is currently set up to only accept ‘GRCh37’ and ‘GRCh38’ at the CLI (or synonyms ‘hg19’ and ‘hg38’, or varied-case versions thereof). However, variant_db often requires specific patches such as ‘GRCh37.p13’ to be named.

Minor changes were made to ensure that panels_backend accepts patch numbers in reference genome names at the CLI (see function ‘_parse_reference_genome’). Tests were changed appropriately.

Ran 138 tests in 4.085s

OK

2024-01-31 10:40 UTC, pep8speaks commented
Hello @corbin-chris! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`panels_backend/management/commands/_parse_transcript.py`](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py):

> [Line 895:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py#L895): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 902:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py#L902): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 903:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py#L903): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

* In the file [`tests/test_panels_backend/test_management/test_commands/test_parse_transcript/test_reference_genome.py`](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/tests/test_panels_backend/test_management/test_commands/test_parse_transcript/test_reference_genome.py):

> [Line 54:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/tests/test_panels_backend/test_management/test_commands/test_parse_transcript/test_reference_genome.py#L54): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 61:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/tests/test_panels_backend/test_management/test_commands/test_parse_transcript/test_reference_genome.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 62:80](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/tests/test_panels_backend/test_management/test_commands/test_parse_transcript/test_reference_genome.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (115 > 79 characters)

2024-01-31 11:44 UTC, JasonLing95 requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/83)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 899 at r1](https://reviewable.io/reviews/eastgenomics/eris/83#-NpUKIs_ArLwOKsR4zJQ:-NpUKIs_ArLwOKsR4zJR:bgwktqy) ([raw file](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py#L899)):*
> ```Python
>         if splits[0] in ["grch37", "grch38"]:
>             if re.match(r"^p\d+$", splits[1]):
>                 return ref_genome.lower()
> ```

why return it as lowercase?


<!-- Sent from Reviewable.io -->

2024-01-31 12:26 UTC, corbin-chris reviewed
Ran 139 tests in 5.568s

OK
Destroying test database for alias 'default'...

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/83#-:-NpUU0IF7MIcqEPAG-4p:bnaxx5r)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 899 at r1](https://reviewable.io/reviews/eastgenomics/eris/83#-NpUKIs_ArLwOKsR4zJQ:-NpUPkhd4YfF-XZ89i0r:b9e3ppt) ([raw file](https://github.com/eastgenomics/eris/blob/b8c8fd27bd0118da71f4f115aa1c1feb7b92555a/panels_backend/management/commands/_parse_transcript.py#L899)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

why return it as lowercase?
</blockquote></details>

Changed it, now ref genomes with patches are formatted more like those without cases.
The .p is now forced to be lower-case.


<!-- Sent from Reviewable.io -->

2024-02-01 09:31 UTC, JasonLing95 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)



<!-- Sent from Reviewable.io -->

2024-02-01 09:31 UTC, merged