Variant db additions
eastgenomics/eris pull request #86
Opened 2024-02-02 13:54 UTC by spaul91

Variant DB interface:

- Interface to VariantDB added
- Docstrings to follow

2024-02-02 13:54 UTC, pep8speaks commented
Hello @spaul91! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`variant_db/management/commands/controller.py`](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py):

> [Line 6:1](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L6): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 17:24](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L17): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`variant_db/management/commands/insert.py`](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py):

> [Line 11:31](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:47](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:61](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:76](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:80](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 11:90](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:30](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:45](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:59](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:74](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:80](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 12:88](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:30](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:45](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:59](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:74](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:80](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 13:88](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 14:30](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 14:45](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 14:59](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 14:74](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 14:80](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 14:88](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:30](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:45](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:59](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:74](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:80](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 15:88](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 16:30](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L16): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 16:45](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L16): [E231](https://duc [...]

2024-02-02 17:04 UTC, corbin-chris requested changes
@spaul91 Please use black to automatically fix the (non-line-length) pep issues: https://pypi.org/project/black/

> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86#-:-Npe5l_O8QY5EJMswHrw:b9iacef)* status: all files reviewed, 13 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/models.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe78b962kucKYvKeD9:-Npe78b962kucKYvKeDA:b6n8yir) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L142)):*
> ```Python
>     numerical_name = models.IntegerField(verbose_name="numeric index")
> 
>     type = models.TextField(verbose_name="chromosome type")
> ```

Could you please rename type here to chrom_type or similar? This is just because type shadows a built-in.
Do you know if the 'type' gets used, actually? In your fixtures they're all type 'chromosome' which looks redundant. Is it maybe supposed to store the values "autosome"/"sex chromosome"/"mitochondria" or something like that which might be ClinVar relevant?
___
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-Npe7vT10JxG7HiQ2-ao:b-e7881q) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
> ```Python
> class InterpretationPanel(models.Model):
>     """
>     docs
> ```

Please fill in docstrings soon
___
*[`variant_db/fixtures/chromosome.yaml` line 148 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe8xjn8jl2IA1xuU2l:-Npe8xjn8jl2IA1xuU2m:b8ut3t1) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/fixtures/chromosome.yaml#L148)):*
> ```YAML
>   pk: 25
>   fields:
>     name: M
> ```

We don't currently support mitochondrial testing in Eris panels (or at least, we don't store transcripts of mitochondrial origin) - do you know if we're likely to need chromosome M for variant DB purposes? Asking as we might need to adjust scope of variant_db or panels accordingly
___
*[`variant_db/management/commands/controller.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeAv-X2NY629639cRv:-NpeAv-X2NY629639cRw:bws1jzc) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L8)):*
> ```Python
> def upload(workbook: str) -> None:
>     """
>     The controller function which uploads a user-provided list of variant files
> ```

Slight correction to docstring here - it looks like this uploads variants from a single file, rather than from a list of multiple files.
___
*[`variant_db/management/commands/insert.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeErRa3NAFtp4xWVXl:-NpeErRa3NAFtp4xWVXm:bx3hj0g) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L23)):*
> ```Python
> def insert_row(row_dict: dict) -> None:
>     """
>     Function to import stuff into DB
> ```

Please put 'a workbook row' instead of 'stuff' 
___
*[`variant_db/management/commands/insert.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeFCgn9y_SdAhfk1g5:-NpeFCgn9y_SdAhfk1g6:b-ag8cxd) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L36)):*
> ```Python
>     clinical_significance_description = insert_into_table(ClinicalSignificanceDescription, **subset_row(row_dict, "category"))
>     assay_method = insert_into_table(AssayMethod, 
>                                      names_to={"assay_method": "name"}, 
> ```

There are some trailing whitespaces here, black reformatting should fix it
___
*[`variant_db/management/commands/insert.py` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeFN0XAoVYJIbjnuZ6:-NpeFN0XAoVYJIbjnuZ7:bnn2ouz) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L95)):*
> ```Python
> 
> 
> def insert_into_table(model_class: models.Model, names_to: dict=None, **kwargs) -> models.Model:
> ```

I'd definitely like a more in-depth docstring on this one please - primarily to make it clear that 'names_to' is there to convert keys where the parsed rows don't already match up with the models.
___
*[`variant_db/management/commands/insert.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeHUg30vOwxunGLlFv:-NpeHUg30vOwxunGLlFw:b-h82pep) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L106)):*
> ```Python
> def get_or_create(model_class, **row):
>     inst, _ = model_class.objects.get_or_create(**row)
>     return inst
> ```

The get_or_create wrapper here might be a bit redundant, could you just act on model_class and **kwargs in insert_into_table instead? It also saves me having to mock out get_or_create constantly in unit testing. I might be missing something
___
*[`variant_db/management/commands/test.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeI8eN4eSsHKnu5KJO:-NpeI8eN4eSsHKnu5KJP:b-q9a5cz) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/test.py#L5)):*
> ```Python
> wb_dict = workbook.read_workbook("misc/sample_new_format_SP.csv")
> print(wb_dict[0])
> insert.insert_row(wb_dict[0])
> ```

It might be worth adding this to gitignore and removing it from the PR - as it's not set up like a formal test, but is more like a simplified version of the CLI that won't be used later.
___
*[`variant_db/management/commands/upload.py` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeJ4aQ5ykxzoMn9uP0:-NpeJ4aQ5ykxzoMn9uP1:b-y26367) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L34)):*
> ```Python
>         """
>         if options["command"] == "variants":
>             for workbook in options["workbooks"]:
> ```

Could you please add back validation for the paths to the workbooks?
Also, please make sure the handle function is wrapped in a decorator specifying that this is an atomic transaction. This ensures that if there's a database error halfway through, every db change will be rolled back.
Otherwise you might end up in a situation where some workbooks get added to the database, and some don't. Or half the variants in a single workbook get added, and the other half don't
You're just doing get_or_creates now so it's less important right now - but when we eventually add more complex aspects such as sanity checking (to stop us double-submitting things to ClinVar) it'll end up being vital.
___
*[`variant_db/management/commands/upload.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeK5YF37P7mcLhqne0:-NpeK5YF37P7mcLhqne1:by4qrcm) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L37)):*
> ```Python
>                 upload(workbook)
>         else:
>             exit(1)
> ```

Print an error message to tell the person that they need the 'variants' command before exiting please.
___
*[`variant_db/management/commands/workbook.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npeib-X4fcS-zU7-kLK:-Npeib-YDz_snWWDTsCt:b9gp3fp) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L30)):*
> ```Python
> def validate_workbook(workbook: pd.DataFrame) -> pd.DataFrame:
>     """
>     Validate workbook (TODO)
> ```

Please delete the vali [...]

2024-02-05 11:09 UTC, spaul91 commented
*[`variant_db/management/commands/upload.py` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeJ4aQ5ykxzoMn9uP0:-NpswcyF7BrEdPRu16mH:b9owo21) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L34)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please add back validation for the paths to the workbooks?
Also, please make sure the handle function is wrapped in a decorator specifying that this is an atomic transaction. This ensures that if there's a database error halfway through, every db change will be rolled back.
Otherwise you might end up in a situation where some workbooks get added to the database, and some don't. Or half the variants in a single workbook get added, and the other half don't
You're just doing get_or_creates now so it's less important right now - but when we eventually add more complex aspects such as sanity checking (to stop us double-submitting things to ClinVar) it'll end up being vital.
</blockquote></details>

On path validation - I'd rather leave that to Python. The way things are now, if a file isn't found, a `FileNotFound` exception will be raised, and I don't think it needs to be more complicated than that. Additionally, submitting whole directories sounds like overkill and, to me, is (slightly) more difficult to reason about than when you're working with submitting files directly.

On atomic transactions - yes, I agree. Sorry, new to Django and didn't know where to put this. I'll find a way to wrap our transactions with this decorator.


<!-- Sent from Reviewable.io -->

2024-02-05 11:11 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @corbin-chris)

___
*[`variant_db/management/commands/test.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeI8eN4eSsHKnu5KJO:-NpswW3l0KTdy98M65qH:bcd1vzf) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/test.py#L5)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It might be worth adding this to gitignore and removing it from the PR - as it's not set up like a formal test, but is more like a simplified version of the CLI that won't be used later.
</blockquote></details>

didn't mean to commit this sorry, will remove.
___
*[`variant_db/management/commands/upload.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeK5YF37P7mcLhqne0:-NpsxYFo9ay_uqEghAyY:b-d7bhn0) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L37)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Print an error message to tell the person that they need the 'variants' command before exiting please.
</blockquote></details>

will do
___
*[`variant_db/management/commands/workbook.py` line 38 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npejo1J7SoJvrOXuUB4:-Npsxl335IGo5XnbKkoO:b704wmd) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L38)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Can you try df.to_dict('records') instead?: http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict

If you already tried this and it causes casting to the wrong data type, please ignore me. Though there's a one-line workaround for that apparently: https://github.com/pandas-dev/pandas/issues/12859#issuecomment-208319535
</blockquote></details>

Why to records?


<!-- Sent from Reviewable.io -->

2024-02-05 11:12 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @corbin-chris)

___
*[`variant_db/management/commands/workbook.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npeib-X4fcS-zU7-kLK:-Npsxw7sB5sst0T6anzj:bih5kfc) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L30)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please delete the validate_workbook function and its call - it's a placeholder that didn't end up needing to be used
</blockquote></details>

Agreed, will do


<!-- Sent from Reviewable.io -->

2024-02-05 11:19 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @corbin-chris)

___
*[`variant_db/models.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe78b962kucKYvKeD9:-NpszSOd5szrMJ56e1qI:b-fknrt4) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L142)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please rename type here to chrom_type or similar? This is just because type shadows a built-in.
Do you know if the 'type' gets used, actually? In your fixtures they're all type 'chromosome' which looks redundant. Is it maybe supposed to store the values "autosome"/"sex chromosome"/"mitochondria" or something like that which might be ClinVar relevant?
</blockquote></details>

To be honest, I agree that `type` isn't descriptive at all, but I don't know what it's for in the first place. I'll go check the ClinVar docs and update this discussion when I find out.
___
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-NpszE0iANHDOCubrBON:by3tme7) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please fill in docstrings soon
</blockquote></details>

I missed this sorry, will update
___
*[`variant_db/fixtures/chromosome.yaml` line 148 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe8xjn8jl2IA1xuU2l:-Npsz8ytC8qolMx_VIha:b-t10gdj) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/fixtures/chromosome.yaml#L148)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

We don't currently support mitochondrial testing in Eris panels (or at least, we don't store transcripts of mitochondrial origin) - do you know if we're likely to need chromosome M for variant DB purposes? Asking as we might need to adjust scope of variant_db or panels accordingly
</blockquote></details>

No idea, didn't think too hard about it when I threw it in. Can remove
___
*[`variant_db/management/commands/controller.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeAv-X2NY629639cRv:-NpsyzxY8Wv3D67Kkp-U:bkhxn7x) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L8)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Slight correction to docstring here - it looks like this uploads variants from a single file, rather than from a list of multiple files.
</blockquote></details>

Which part, sorry? It reads as intended to me
___
*[`variant_db/management/commands/insert.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeErRa3NAFtp4xWVXl:-NpsymLiBOxex30n6V3R:be4mfut) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L23)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please put 'a workbook row' instead of 'stuff'
</blockquote></details>

It doesn't say "stuff"? Maybe this is from a previous commit
___
*[`variant_db/management/commands/insert.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeFCgn9y_SdAhfk1g5:-Npsyl4Q9PXEHsd5NEAQ:bebrt1w) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L36)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

There are some trailing whitespaces here, black reformatting should fix it
</blockquote></details>

Will do
___
*[`variant_db/management/commands/insert.py` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeFN0XAoVYJIbjnuZ6:-Npsyg6zD3gc3evOBVMo:b-hfghm4) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L95)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I'd definitely like a more in-depth docstring on this one please - primarily to make it clear that 'names_to' is there to convert keys where the parsed rows don't already match up with the models.
</blockquote></details>

Sounds good
___
*[`variant_db/management/commands/insert.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeHUg30vOwxunGLlFv:-Npsy5Jh90kriWKVAYi2:b-t5oefm) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L106)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

The get_or_create wrapper here might be a bit redundant, could you just act on model_class and **kwargs in insert_into_table instead? It also saves me having to mock out get_or_create constantly in unit testing. I might be missing something
</blockquote></details>

Since `insert_into_table` is doing more than one thing, I wanted to atomise each action by making single functions for each. What would be the difference made in unit testing if the interface to `insert_into_table` doesn't change? You'd be submitting the same thing anyway, right?


<!-- Sent from Reviewable.io -->

2024-02-05 11:22 UTC, spaul91 commented
*[`variant_db/fixtures/chromosome.yaml` line 148 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe8xjn8jl2IA1xuU2l:-Npt-1-X-K0m6W0oBqJp:befyy4r) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/fixtures/chromosome.yaml#L148)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

No idea, didn't think too hard about it when I threw it in. Can remove
</blockquote></details>

Just for info, these are the chromosome names ClinVar accepts:

`Allowed values: "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y", "MT"`


<!-- Sent from Reviewable.io -->

2024-02-05 11:24 UTC, spaul91 commented
*[`variant_db/models.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe78b962kucKYvKeD9:-Npt-bCv7Bp-yDaQG-nt:bgmn166) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L142)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

To be honest, I agree that `type` isn't descriptive at all, but I don't know what it's for in the first place. I'll go check the ClinVar docs and update this discussion when I find out.
</blockquote></details>

I couldn't find an entry for chromosome type in the ClinVar submission API... Need Wook


<!-- Sent from Reviewable.io -->

2024-02-05 11:57 UTC, spaul91 commented
*[`variant_db/management/commands/upload.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeK5YF37P7mcLhqne0:-Npt7Ed68LDYSQu0nma0:b-2suqle) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L37)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Oh wait sorry - Django does this by default anyway, so no extra code needed on this


<!-- Sent from Reviewable.io -->

2024-02-05 12:42 UTC, corbin-chris requested changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/fixtures/chromosome.yaml` line 148 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe8xjn8jl2IA1xuU2l:-NptEIjx9CBQfX9Dx7YD:b-nzy6wz) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/fixtures/chromosome.yaml#L148)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Just for info, these are the chromosome names ClinVar accepts:

`Allowed values: "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y", "MT"`
</blockquote></details>

Sure - probably doesn't hurt to have MT in the fixtures
___
*[`variant_db/management/commands/controller.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeAv-X2NY629639cRv:-NptEnj9-n8ITBxGPZh6:b8h4icm) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L8)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Which part, sorry? It reads as intended to me
</blockquote></details>

'upload()' takes **one single workbook**, not a list of workbooks.
So the docstring should say 'uploads a user-provided variant file' rather than 'list of variant files'
The iterating over each file in a list, happens inside handle() not inside upload()
___
*[`variant_db/management/commands/workbook.py` line 38 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npejo1J7SoJvrOXuUB4:-NptGBMdCnKj1VPglJLZ:b4uekfm) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L38)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Why to records?
</blockquote></details>

Because, I think, it'll turn your df straight into the 'list of dictionaries' format. This will replace _row_dict() and probably make _pivot_df_as_row_dict() redundant too.
Basically it turns your df straight into this format:
[
{"col_1": value_1_from_first_row, "col_2": value_2_from_first_row, "col_3": value_3_from_first_row},
{"col_1": value_1_from_second_row, "col_2": value_2_from_second_row, "col_3": value_3_from_second_row}
]


<!-- Sent from Reviewable.io -->

2024-02-05 13:11 UTC, corbin-chris requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 38 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npejo1J7SoJvrOXuUB4:-NptO9mz8qtkvGi6-v76:b-mpbcge) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L38)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Ah right, I thought `to_records` converted to tuples. Will go check and get back to you, thanks for spotting this
</blockquote></details>

It's 'records' not 'to_records' - in case that's a different thing.


<!-- Sent from Reviewable.io -->

2024-02-05 15:58 UTC, corbin-chris reviewed
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 10 of 11 files reviewed, 13 unresolved discussions (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-07 10:29 UTC, corbin-chris reviewed
> Reviewed 1 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 13 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/models.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe78b962kucKYvKeD9:-Nq25UoI6RXLH9MFAMBG:bo5xpc) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L142)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I couldn't find an entry for chromosome type in the ClinVar submission API... Need Wook
</blockquote></details>

Done you've since fixed this
___
*[`variant_db/management/commands/insert.py` line 106 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeHUg30vOwxunGLlFv:-Nq25j52Bl_T-8SWa0Ud:bp7l0g4) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L106)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Since `insert_into_table` is doing more than one thing, I wanted to atomise each action by making single functions for each. What would be the difference made in unit testing if the interface to `insert_into_table` doesn't change? You'd be submitting the same thing anyway, right?
</blockquote></details>

Done as you've since fixed this
___
*[`variant_db/management/commands/upload.py` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeJ4aQ5ykxzoMn9uP0:-Nq25pyEAEIHZSEyvG7A:b-qb16nm) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L34)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

On path validation - I'd rather leave that to Python. The way things are now, if a file isn't found, a `FileNotFound` exception will be raised, and I don't think it needs to be more complicated than that. Additionally, submitting whole directories sounds like overkill and, to me, is (slightly) more difficult to reason about than when you're working with submitting files directly.

On atomic transactions - yes, I agree. Sorry, new to Django and didn't know where to put this. I'll find a way to wrap our transactions with this decorator.
</blockquote></details>

Done we've since discussed atomic decorators (though I think you might have put them on a different branch for the time being)
___
*[`variant_db/management/commands/upload.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeK5YF37P7mcLhqne0:-Nq25w2V0X3tHLeTT_YE:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/upload.py#L37)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Oh wait sorry - Django does this by default anyway, so no extra code needed on this
</blockquote></details>

done
___
*[`variant_db/management/commands/test.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeI8eN4eSsHKnu5KJO:-Nq26Ccs6J_XDuwA6S3Z:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/test.py#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

didn't mean to commit this sorry, will remove.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-13 15:02 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 18 of 22 files reviewed, 6 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-NptIND66DstRod68vIq:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I missed this sorry, will update
</blockquote></details>

Done.
___
*[`variant_db/fixtures/chromosome.yaml` line 148 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe8xjn8jl2IA1xuU2l:-NptIIhA0M8VwFdHLHWu:b-4n6a3x) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/fixtures/chromosome.yaml#L148)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Sure - probably doesn't hurt to have MT in the fixtures
</blockquote></details>

Thanks, closing
___
*[`variant_db/management/commands/controller.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeAv-X2NY629639cRv:-NqXsWM03GS38yi_TaU9:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/controller.py#L8)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

ohhhhhhh yeah I see. Sorry, you're right. Will update
</blockquote></details>

Done.
___
*[`variant_db/management/commands/insert.py` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-NpeFN0XAoVYJIbjnuZ6:-NqXuAY28qRNP-x_QDkF:bjoz8ur) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/management/commands/insert.py#L95)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

I went back to read the docstrings - `names_to` is an argument of `_insert_into_row`, where this is documented in detail. Closing discussion
___
*[`variant_db/management/commands/insert.py` line 224 at r13](https://reviewable.io/reviews/eastgenomics/eris/86#-NqCPZo42oEfffVDqrM-:-NqXuTeS1U4DlIkUf0BM:b-vk0hzu) ([raw file](https://github.com/eastgenomics/eris/blob/f1b037bb48b858e0e3f7d6e25a5f8cf4fd23ec2d/variant_db/management/commands/insert.py#L224)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Need to discuss this - we probably want a TypeError here to stop everything (and thus trigger rollback of database changes) as I think it would mean the input from the CSV has something wrong with it, in which case, that either needs attending to or we've made a coding error. It should probably also log.
More info: https://stackoverflow.com/questions/21553327/why-is-except-pass-a-bad-programming-practice
</blockquote></details>

I think I've been a bit unclear about why this is here. The step that calls `_rename_key` expects a `dict` object from the `names_to` argument. However, this is also allowed to be `None` in case the developer doesn't want to use that argument. The `TypeError` is ignored in the event that `names_to = None`, which is not an error.

It's a bit confusing to be honest, it took me a bit to realise why I'd done it, so I'll change it to an `if` statement so the intent is clearer.

By the way - the "bad practice" discussed in your link is the use of `except` without a specific error, *not* the practice of ignoring certain types of errors with (e.g.) `except SomeError: pass`. My code here is bad because it isn't immediately obvious what it does, and not because I've used a `try-except` clause incorrectly.
___
*[`variant_db/management/commands/upload.py` line 20 at r13](https://reviewable.io/reviews/eastgenomics/eris/86#-NqCTJCO2_2Jz0eosNKu:-NqXy5Kn6_XPhMQsm9EZ:b-p0cwvw) ([raw file](https://github.com/eastgenomics/eris/blob/f1b037bb48b858e0e3f7d6e25a5f8cf4fd23ec2d/variant_db/management/commands/upload.py#L20)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Minor but you might want to use a TimedRotatingFileHandler
https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler
This will make sure that your logs get split into different files on a daily (or weekly, or monthly, e.t.c.) basis, and that might make it easier to delete/archive logs once they're old enough to not be likely to be informative anymore.
Logs like to pile up!!
</blockquote></details>

Thanks, will consider for a future release. I'd rather focus on other things for now
___
*[`variant_db/management/commands/workbook.py` line 30 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npeib-X4fcS-zU7-kLK:-NptIaXp1pr41jF6mEKB:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L30)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Agreed, will do
</blockquote></details>

Done.
___
*[`variant_db/management/commands/workbook.py` line 38 at r4](https://reviewable.io/reviews/eastgenomics/eris/86#-Npejo1J7SoJvrOXuUB4:-NqXyrt58MB_cXVGrD-V:b7l2d3t) ([raw file](https://github.com/eastgenomics/eris/blob/49c16faea08dbb10ac3f0b3da16a1ff257fd2d75/variant_db/management/commands/workbook.py#L38)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It's 'records' not 'to_records' - in case that's a different thing.
</blockquote></details>

Reviewable isn't showing this for some reason, but line 24 is now `wb_records = wb_df.to_dict(orient="records")`, so this is done
___
*[`variant_db/management/commands/workbook.py` line 7 at r13](https://reviewable.io/reviews/eastgenomics/eris/86#-NqCRuu38QQj9eWWcsny:-NqXykkj6BotZBK0rFwQ:b-x1f5u) ([raw file](https://github.com/eastgenomics/eris/blob/f1b037bb48b858e0e3f7d6e25a5f8cf4fd23ec2d/variant_db/management/commands/workbook.py#L7)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Think this doesn't get used in workbook.py (it's used in some other scripts instead), so the import can be removed
</blockquote></details>

Thanks, removed


<!-- Sent from Reviewable.io -->

2024-02-13 15:12 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 224 at r13](https://reviewable.io/reviews/eastgenomics/eris/86#-NqCPZo42oEfffVDqrM-:-NqY0EjX4H-X0zxgJuWV:bc9eu2r) ([raw file](https://github.com/eastgenomics/eris/blob/f1b037bb48b858e0e3f7d6e25a5f8cf4fd23ec2d/variant_db/management/commands/insert.py#L224)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I think I've been a bit unclear about why this is here. The step that calls `_rename_key` expects a `dict` object from the `names_to` argument. However, this is also allowed to be `None` in case the developer doesn't want to use that argument. The `TypeError` is ignored in the event that `names_to = None`, which is not an error.

It's a bit confusing to be honest, it took me a bit to realise why I'd done it, so I'll change it to an `if` statement so the intent is clearer.

By the way - the "bad practice" discussed in your link is the use of `except` without a specific error, *not* the practice of ignoring certain types of errors with (e.g.) `except SomeError: pass`. My code here is bad because it isn't immediately obvious what it does, and not because I've used a `try-except` clause incorrectly.
</blockquote></details>

Updated to if statement, which is far easier to understand. It's still unclear what possessed me to use a try-catch block in the first place.


<!-- Sent from Reviewable.io -->

2024-02-14 09:32 UTC, jethror1 requested changes
> Reviewed 1 of 7 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 19 of 22 files reviewed, 14 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/controller.py` line 4 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-Nqasl8vEjdhcc8WOwyF:-Nqasl8vEjdhcc8WOwyG:b-8ua8r8) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/controller.py#L4)):*
> ```Python
> import pandas as pd
> from django.db import transaction
> from .insert import *
> ```

I'm not sure as to what functions are in `insert`, but I'd generally avoid doing `import *` unless you really want everything importing. It increases the likelihood of collisions in the namespace, is inefficient if you had a large amount to import but didn't need to use everything and makes the code more ambiguous by not having the origin of the method (i.e having its own namespace such as `insert.method_1` vs just having `method_1`). If you do just want to use one or two methods then having `from .insert import method_1, method_2` makes it clearer to understand provenance.



_Code quote:_
```Python
from .insert import *
```
___
*[`variant_db/management/commands/controller.py` line 6 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-Nqatxyn-_szQkQO7MQP:-Nqatxyn-_szQkQO7MQQ:boruskf) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/controller.py#L6)):*
> ```Python
> from .insert import *
> from .workbook import read_workbook
> from .insert import insert_row
> ```

seems redundant given the `import *` above



_Code quote:_
```Python
from .insert import insert_row
```
___
*[`variant_db/management/commands/insert.py` line 188 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqaudpN0vZV41sOnRu7:-NqaudpN0vZV41sOnRu8:b-rnsg65) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/insert.py#L188)):*
> ```Python
> 
> 
> def keep_count_of_truth(f):
> ```

could the variable name be more descriptive? what is `f` meant to be?



_Code quote:_
```Python
f
```
___
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-NqavO9YEVvtbBHheFf8:b-nru5d4) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
> ```Python
> 
>     :param: workbook: path to workbook file
>     """
> ```

return missing from docstring
___
*[`variant_db/management/commands/workbook.py` line 45 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-Nqavy0m2jW-X4qhzcQt:-Nqavy0m2jW-X4qhzcQu:bcyfypq) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L45)):*
> ```Python
>     """
>     Replaces whitespace with an underscore (except fields ending with "ID")
>     """
> ```

docstring doesn't match what is happening, since you always replace space with an underscore



_Code quote:_
```Python
    """
    Replaces whitespace with an underscore (except fields ending with "ID")
    """
```
___
*[`variant_db/management/commands/workbook.py` line 62 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawPSmA7wzRKTKkwbC:-NqawPSmA7wzRKTKkwbD:b2wrg8j) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L62)):*
> ```Python
> 
> def _convert_name_to_lowercase(
>     column_header: str, exclude: Tuple[str] = ("verdict", "evidence", "ACGS")
> ```

since only ACGS is not lowercase, can `exclude` just be ACGS?



_Code quote:_
```Python
"verdict", "evidence", "ACGS"
```
___
*[`variant_db/management/commands/workbook.py` line 76 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawcFS5YpXqfGxoEYb:-NqawcFTEJ1adg83KhVu:b3v3p03) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L76)):*
> ```Python
>     """
>     Splits up the "panels" field into single panels (";"-separated), where each panel is a dict with `panel_name` and `panel_version`
>     """
> ```

since this input/output is more complex than the other simple methods with single strings etc can you add to the docstring



_Code quote:_
```Python
"""
```
___
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqawvUY7gCBpUeBd-he:b-guznpi) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
> ```Python
>     Splits a single panel string into "name" and "version" components, returning a dict
>     """
>     split_panel = panel.split("_")
> ```

are we certain panel strings will _always_ have a single underscore? should we validate here with regex the parts are as expected? 



_Code quote:_
```Python
split_panel = panel.split("_")
```


<!-- Sent from Reviewable.io -->

2024-02-14 14:38 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 188 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqaudpN0vZV41sOnRu7:-Nqc2Ku-7rlzshOqZcNF:b-mxb8rw) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/insert.py#L188)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could the variable name be more descriptive? what is `f` meant to be?
</blockquote></details>

I though `f` was a common convention in decorators for any arbitrary function? I could rename it to `func`...


<!-- Sent from Reviewable.io -->

2024-02-14 15:26 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 76 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawcFS5YpXqfGxoEYb:-NqcDMFO5CIGzzet9KA4:b9dg3aa) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L76)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since this input/output is more complex than the other simple methods with single strings etc can you add to the docstring
</blockquote></details>

Add what to the docstring, sorry? The code quote is empty


<!-- Sent from Reviewable.io -->

2024-02-14 15:29 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqcDTFe-6YaYZoEnI9H:b-6uvev) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are we certain panel strings will _always_ have a single underscore? should we validate here with regex the parts are as expected?
</blockquote></details>

I can only go from the example I've been given, I don't actually know what all panel strings will possibly look like. Some may not even have a version. A regex might be useful to validate, but what do we do with the string if that fails?


<!-- Sent from Reviewable.io -->

2024-02-14 15:35 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-NqcFRT4AwCDm0dmVz0j:ba8h41x) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

All of the docstrings across Eris are missing returns. We could either add returns to all docstrings across the repo, or leave this one blank. @corbin-chris thoughts?
</blockquote></details>

(By "Eris" I mean "Eris+VariantDB")


<!-- Sent from Reviewable.io -->

2024-02-14 15:36 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 62 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawPSmA7wzRKTKkwbC:-NqcFXQlBCdSAcpcMYdP:b-r5k7sc) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L62)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since only ACGS is not lowercase, can `exclude` just be ACGS?
</blockquote></details>

No, because those are search terms so anything with "verdict" or "evidence" needs to be skipped. I don't remember why ACGS is there at all actually, I think it was a placeholder...


<!-- Sent from Reviewable.io -->

2024-02-14 15:37 UTC, spaul91 commented
*[`variant_db/management/commands/controller.py` line 4 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-Nqasl8vEjdhcc8WOwyF:-NqcF0PI3wA5vOxMt0EP:bog0amw) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/controller.py#L4)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm not sure as to what functions are in `insert`, but I'd generally avoid doing `import *` unless you really want everything importing. It increases the likelihood of collisions in the namespace, is inefficient if you had a large amount to import but didn't need to use everything and makes the code more ambiguous by not having the origin of the method (i.e having its own namespace such as `insert.method_1` vs just having `method_1`). If you do just want to use one or two methods then having `from .insert import method_1, method_2` makes it clearer to understand provenance.
</blockquote></details>

Removed, thanks


<!-- Sent from Reviewable.io -->

2024-02-14 15:37 UTC, spaul91 commented
*[`variant_db/management/commands/controller.py` line 6 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-Nqatxyn-_szQkQO7MQP:-NqcF3TuCcSZgkYXM8NB:b-34vmyd) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/controller.py#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

seems redundant given the `import *` above
</blockquote></details>

See above


<!-- Sent from Reviewable.io -->

2024-02-14 16:18 UTC, jethror1 requested changes
> Reviewed 54 of 59 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 66 of 71 files reviewed, 11 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py` line 94 at r18](https://reviewable.io/reviews/eastgenomics/eris/86#-NqcM_VM6veBGB2fwmqR:-NqcM_VM6veBGB2fwmqS:b-p3yh4n) ([raw file](https://github.com/eastgenomics/eris/blob/b145932c28b3a0d83f7faae5d687d0319f5b2201/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L94)):*
> ```Python
>         assert retrieved_entry.name == "NHS Foundation Trust"
> 
>     # TODO: make sure the try/except is hit IF we decide to keep it
> ```

did we decide? is this needed?



_Code quote:_
```Python
 # TODO: make sure the try/except is hit IF we decide to keep it
```
___
*[`variant_db/management/commands/workbook.py` line 62 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawPSmA7wzRKTKkwbC:-NqcP6dmCtHJjXuN9pwF:b7kbsza) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L62)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

No, because those are search terms so anything with "verdict" or "evidence" needs to be skipped. I don't remember why ACGS is there at all actually, I think it was a placeholder...
</blockquote></details>

are these from Wins parser script? can you check with her if ACGS is valid / meant to be handled here?
___
*[`variant_db/management/commands/workbook.py` line 76 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawcFS5YpXqfGxoEYb:-NqcOF3a-bXU8t5sou6a:b-oft3gc) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L76)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Add what to the docstring, sorry? The code quote is empty
</blockquote></details>

sorry I meant to add an example structure of the list of dicts to the docstring / add your param like we discussed in Slack
___
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqcNQD4EI7cSAnLTyoH:b-bgou5i) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
good question, I also don't know exactly what we will get here, assuming its from the panel string from the workbook split up and not HGNC IDs, it will be as it is in genepanels (which eventually will come from Eris which is all wonderfully circular).

My main question here is if we got something different, you would end up like this:
```
>>> s = "someRandomName"
>>> split_panel = s.split("_")
>>> {"name": split_panel[0], "version": split_panel[-1]}
{'name': 'someRandomName', 'version': 'someRandomName'}
```

so to me, I'd validate with regex for format and raise an error instead of continuing. @corbin-chris thoughts since you probably know better than me?


<!-- Sent from Reviewable.io -->

2024-02-14 17:05 UTC, corbin-chris requested changes
> Reviewed 3 of 59 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 7 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-NqcUPoA0QjTMc2E3OE5:b-6t6g49) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you push it? Still not showing for me in Reviewable
___
*[`variant_db/management/commands/insert.py` line 201 at r18](https://reviewable.io/reviews/eastgenomics/eris/86#-NqcUryKE9WjcHbV4bzk:-NqcUryKE9WjcHbV4bzl:b-ng8hzu) ([raw file](https://github.com/eastgenomics/eris/blob/b145932c28b3a0d83f7faae5d687d0319f5b2201/variant_db/management/commands/insert.py#L201)):*
> ```Python
> 
> 
> # See docstring in `keep_count_of_truth` for why these are here
> ```

I think 'keep_count_of_truth' was renamed to 'store_bools', could you please edit this accordingly?
___
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-NqcWPSy4a3nFwLJsEPx:b-l3q2mw) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

(By "Eris" I mean "Eris+VariantDB")
</blockquote></details>

Might be best to add the returns - let me know if you want to split this work between us to speed it up @spaul91 
This would also make it more like Eris-panels which is in the same repo
___
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqcX4St844738eEcs9u:b-vsrkj1) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

good question, I also don't know exactly what we will get here, assuming its from the panel string from the workbook split up and not HGNC IDs, it will be as it is in genepanels (which eventually will come from Eris which is all wonderfully circular).

My main question here is if we got something different, you would end up like this:
```
>>> s = "someRandomName"
>>> split_panel = s.split("_")
>>> {"name": split_panel[0], "version": split_panel[-1]}
{'name': 'someRandomName', 'version': 'someRandomName'}
```

so to me, I'd validate with regex for format and raise an error instead of continuing. @corbin-chris thoughts since you probably know better than me?
</blockquote></details>

The panel names should always have exactly 1 underscore in them, at least if you get them from the currently-in-development version of Eris Panels. All panels have a version now (even TD and custom panels) and when Eris outputs files such as the 'genepanel' file, it programmatically joins the panel name to the version with an underscore, so it's hard to mess it up.
You can add custom panels through the web interface for Eris Panels, but you are blocked from putting underscores in them!
The only way you'd get a second underscore in a panel name is if PanelApp or TD decided to do this to us...
You can see the 'genepanel and g2t output specification' file in the IN Confluence for details.

If you want to be totally sure things are fine:
- If a split fails due to a lack of underscore, it should be a stop event
- If splitting produces more than 2 items in the resulting list, it should also throw an error and stop
- The [-1] position in the split will be the version, this should only contain numbers and full-stop - you can regex this if you like.
- The [0] position in the split could contain a wide variety of characters - I personally wouldn't try to regex this.


<!-- Sent from Reviewable.io -->

2024-02-15 10:20 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: all files reviewed, 7 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqgFva70muVHBz_69Su:b-wkhn5r) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

The panel names should always have exactly 1 underscore in them, at least if you get them from the currently-in-development version of Eris Panels. All panels have a version now (even TD and custom panels) and when Eris outputs files such as the 'genepanel' file, it programmatically joins the panel name to the version with an underscore, so it's hard to mess it up.
You can add custom panels through the web interface for Eris Panels, but you are blocked from putting underscores in them!
The only way you'd get a second underscore in a panel name is if PanelApp or TD decided to do this to us...
You can see the 'genepanel and g2t output specification' file in the IN Confluence for details.

If you want to be totally sure things are fine:
- If a split fails due to a lack of underscore, it should be a stop event
- If splitting produces more than 2 items in the resulting list, it should also throw an error and stop
- The [-1] position in the split will be the version, this should only contain numbers and full-stop - you can regex this if you like.
- The [0] position in the split could contain a wide variety of characters - I personally wouldn't try to regex this.
</blockquote></details>

something like `assert re.match(r"^.+_[\d]+\.[\d]$"), f"invalid panel name: {panel}"` would be a sensible check I think


<!-- Sent from Reviewable.io -->

2024-02-15 12:22 UTC, jethror1 reviewed
> Reviewed 2 of 11 files at r1, 1 of 2 files at r3, 1 of 8 files at r5, 1 of 7 files at r12, 1 of 2 files at r18, 55 of 57 files at r19.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 69 of 72 files reviewed, 7 unresolved discussions (waiting on @corbin-chris and @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-15 12:29 UTC, jethror1 requested changes
> Reviewed 1 of 57 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 70 of 72 files reviewed, 9 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`panels_backend/management/commands/_queries.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjI2s3jg_H4I60zI5:-NqgjI2s3jg_H4I60zI6:bpqgkh5) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/panels_backend/management/commands/_queries.py#L156)):*
> ```Python
>             print(
>                 f"Clinical indication panel {cip_instance.id} link set to inactive."
>             )
> ```

looks like print duplicated here @corbin-chris 



_Code quote:_
```Python
            print(
                f"Clinical indication panel {cip_instance.id} link set to inactive."
            )
```
___
*[`variant_db/file_uploader.py` line 0 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjN9o6_6J5bb9IbXh:-NqgjN9o6_6J5bb9IbXi:b4l1i0j) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/variant_db/file_uploader.py#L0)):*
was this meant to be deleted @spaul91 @corbin-chris ?


<!-- Sent from Reviewable.io -->

2024-02-15 12:33 UTC, corbin-chris reviewed
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 71 of 72 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[`panels_backend/management/commands/_queries.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjI2s3jg_H4I60zI5:-Nqgk33N8zXS0k_PT25j:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/panels_backend/management/commands/_queries.py#L156)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

looks like print duplicated here @corbin-chris
</blockquote></details>

Done
___
*[`variant_db/file_uploader.py` line  at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjN9o6_6J5bb9IbXh:-NqgkB9t81RuthQuchFG:bk4c4mf) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/variant_db/file_uploader.py#L)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

was this meant to be deleted @spaul91 @corbin-chris ?
</blockquote></details>

Yes, it was a placeholder Python script I made to get @spaul91 started but she didn't need it. It only contained pseudocode.
___
*[`variant_db/management/commands/upload.py` line 20 at r13](https://reviewable.io/reviews/eastgenomics/eris/86#-NqCTJCO2_2Jz0eosNKu:-NqgkSNt0R1IaMW82Z3V:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/f1b037bb48b858e0e3f7d6e25a5f8cf4fd23ec2d/variant_db/management/commands/upload.py#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Thanks, will consider for a future release. I'd rather focus on other things for now
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-16 13:46 UTC, spaul91 commented
*[`tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py` line 94 at r18](https://reviewable.io/reviews/eastgenomics/eris/86#-NqcM_VM6veBGB2fwmqR:-Nqm9X7VAW6Sjaj_8yfc:bvbftl9) ([raw file](https://github.com/eastgenomics/eris/blob/b145932c28b3a0d83f7faae5d687d0319f5b2201/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L94)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

did we decide? is this needed?
</blockquote></details>

If this is about what I think it is, then yes it's gone. I'll remove the comment.


<!-- Sent from Reviewable.io -->

2024-02-16 13:46 UTC, spaul91 commented
*[`variant_db/file_uploader.py` line  at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjN9o6_6J5bb9IbXh:-Nqm9j8I71rHPTfG14q-:b-f9u2tm) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/variant_db/file_uploader.py#L)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Yes, it was a placeholder Python script I made to get @spaul91 started but she didn't need it. It only contained pseudocode.
</blockquote></details>

Marking as resolved


<!-- Sent from Reviewable.io -->

2024-02-16 13:51 UTC, spaul91 commented
*[`panels_backend/management/commands/_queries.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjI2s3jg_H4I60zI5:-NqmAuDw2MYYaF9UpGS2:b6ax0i4) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/panels_backend/management/commands/_queries.py#L156)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

@corbin-chris please push the change, reviewable still shows the duplication


<!-- Sent from Reviewable.io -->

2024-02-16 13:52 UTC, spaul91 commented
*[`tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py` line 94 at r18](https://reviewable.io/reviews/eastgenomics/eris/86#-NqcM_VM6veBGB2fwmqR:-NqmB3jPBovmKP4hOpKI:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/b145932c28b3a0d83f7faae5d687d0319f5b2201/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L94)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

If this is about what I think it is, then yes it's gone. I'll remove the comment.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-16 13:53 UTC, spaul91 commented
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-NqmBIQm8IYq6tnw5WkQ:b-i3k4bk) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Did you push it? Still not showing for me in Reviewable
</blockquote></details>

Docstrings were updated for most other functions. Why does this docstring need to be any more than what it is currently?


<!-- Sent from Reviewable.io -->

2024-02-16 13:54 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 201 at r18](https://reviewable.io/reviews/eastgenomics/eris/86#-NqcUryKE9WjcHbV4bzk:-NqmBaQw6hsWy6_-bl_X:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/b145932c28b3a0d83f7faae5d687d0319f5b2201/variant_db/management/commands/insert.py#L201)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I think 'keep_count_of_truth' was renamed to 'store_bools', could you please edit this accordingly?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 13:55 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-NqmBfab-YNInDqv6B8r:bevbhju) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Might be best to add the returns - let me know if you want to split this work between us to speed it up @spaul91 
This would also make it more like Eris-panels which is in the same repo
</blockquote></details>

Actually can we make this a todo for later please? It's high-effort with low payoff given the timelines


<!-- Sent from Reviewable.io -->

2024-02-16 14:40 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 76 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawcFS5YpXqfGxoEYb:-NqmLq8XDaJ4do4SmkuL:b-3p8vle) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L76)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

sorry I meant to add an example structure of the list of dicts to the docstring / add your param like we discussed in Slack
</blockquote></details>

Sorry, could you remind me? The input is the result of calling `df.to_dict(orient="records")`, so an example would be quite large even for a single row...

As this is an internal function, should this be documented any further than it already is?


<!-- Sent from Reviewable.io -->

2024-02-16 14:47 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 76 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawcFS5YpXqfGxoEYb:-NqmNg3W5boeBZdvTZ8V:bq8x7dj) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L76)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Sorry, could you remind me? The input is the result of calling `df.to_dict(orient="records")`, so an example would be quite large even for a single row...

As this is an internal function, should this be documented any further than it already is?
</blockquote></details>

I've tried to expand on the docstring as suggested


<!-- Sent from Reviewable.io -->

2024-02-16 14:51 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 86 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawvUY7gCBpUeBd-hd:-NqmFgll9HdAKXuVw84u:b-lgaa5o) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L86)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

something like `assert re.match(r"^.+_[\d]+\.[\d]$"), f"invalid panel name: {panel}"` would be a sensible check I think
</blockquote></details>

thank you both, this is great. I've added the assertion.


<!-- Sent from Reviewable.io -->

2024-02-16 14:52 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 62 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqawPSmA7wzRKTKkwbC:-NqmOpXmDHR_2ltWY5yM:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L62)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are these from Wins parser script? can you check with her if ACGS is valid / meant to be handled here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 15:35 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 68 of 72 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[`panels_backend/management/commands/_queries.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjI2s3jg_H4I60zI5:-NqmXXG1DLbaF_iNuuqC:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/panels_backend/management/commands/_queries.py#L156)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

@corbin-chris please push the change, reviewable still shows the duplication
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-16 15:37 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: 68 of 72 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @spaul91)

___
*[`variant_db/models.py` line 439 at r1](https://reviewable.io/reviews/eastgenomics/eris/86#-Npe7vT10JxG7HiQ2-an:-NqmYoqI9U8Eg1Yu2JHq:b-is1l13) ([raw file](https://github.com/eastgenomics/eris/blob/ddf286e90bad2ccae9e17982426ece57fdc56b6d/variant_db/models.py#L439)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Docstrings were updated for most other functions. Why does this docstring need to be any more than what it is currently?
</blockquote></details>

Done  whatever
___
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-NqmZ04R61PPRaPbjfUN:bmhp5j7) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Actually can we make this a todo for later please? It's high-effort with low payoff given the timelines
</blockquote></details>

Done OK but please make a story for VarDB version 2 in Jira (if one doesn't exist already) and add it as a task/ticket/whatever on there. We'll not remember otherwise.


<!-- Sent from Reviewable.io -->

2024-02-19 12:48 UTC, spaul91 commented
*[`panels_backend/management/commands/_queries.py` line 156 at r20](https://reviewable.io/reviews/eastgenomics/eris/86#-NqgjI2s3jg_H4I60zI5:-Nr0PKPy6Gp75aIYchSW:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/336a1e0a999fc46b9da16d0db1497535526bfaea/panels_backend/management/commands/_queries.py#L156)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-19 13:13 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 20 at r16](https://reviewable.io/reviews/eastgenomics/eris/86#-NqavO9YEVvtbBHheFf7:-Nr0Uxfg3LqRgGrMeCRX:b8c7qdi) ([raw file](https://github.com/eastgenomics/eris/blob/fbd4fde851f4c6d448d676070380be21609aada0/variant_db/management/commands/workbook.py#L20)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done OK but please make a story for VarDB version 2 in Jira (if one doesn't exist already) and add it as a task/ticket/whatever on there. We'll not remember otherwise.
</blockquote></details>

https://cuhbioinformatics.atlassian.net/browse/IN-464


<!-- Sent from Reviewable.io -->

2024-02-19 14:22 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86#-:-Nr0jggl6pWGZvGK5syX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-19 14:22 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-19 14:22 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-19 14:29 UTC, corbin-chris approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-19 14:30 UTC, merged