Variant db additions
eastgenomics/eris pull request #93
Opened 2024-02-20 16:39 UTC by spaul91

Hopefully this should be the last PR `variant_db_additions` needs. Changes:

- modified `_insert_into_table` behaviour to allow both "get"-only and "get or create" behaviour (+ related test cases)
- made `Panel` and `Chromosome` tables read-only (from the perspective of `insert_into_table`); it'll now raise `django.core.exceptions.ObjectDoesNotExist` in the event of missing Panel or Chromosome data, which is what we want (+ related test cases)
- added `null=True/False` declarations to most tables (as discussed with @woook)

Unit test outcome passes for all cases:

```
(.venv) pauls4@pauls4-ThinkPad-T590:~/workspace/development/eris$ python manage.py test tests
Found 159 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...........................Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
......................Start 2 gene bulk create: 16:30:21
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
.....Preparing HGNC files
Start bulk-updating 2 gene symbols: 16:30:22
Start bulk-updating 2 gene symbols: 16:30:22
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 16:30:22
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 16:30:22
Start bulk-updating 2 gene symbols: 16:30:22
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 16:30:22
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 16:30:22
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 16:30:22
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 16:30:22
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 16:30:22
...................Start bulk-updating 1 gene symbols: 16:30:22
Start bulk-updating 1 gene symbols: 16:30:22
.Start bulk-updating 2 gene symbols: 16:30:22
Start bulk-updating 2 gene symbols: 16:30:22
....................
----------------------------------------------------------------------
Ran 159 tests in 8.968s

OK
Destroying test database for alias 'default'...
```

Thanks,

Sophie

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eris/93)

2024-02-20 16:39 UTC, pep8speaks commented
Hello @spaul91! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py`](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py):

> [Line 40:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 56:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L56): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 94:1](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L94): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 96:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L96): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 110:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 116:1](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L116): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 120:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L120): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 126:47](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L126): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py`](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py):

> [Line 18:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 20:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 79:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 83:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L83): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 84:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 86:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 92:1](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L92): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 95:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 97:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 100:63](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L100): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 103:80](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L103): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 104:59](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L104): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`variant_db/management/commands/controller.py`](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/controller.py):

> [Line 20:24](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/controller.py#L20): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`variant_db/management/commands/insert.py`](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/insert.py):

> [Line 278:20](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/insert.py#L278): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`variant_db/management/commands/workbook.py`](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/workbook.py):

> [Line 126:27](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/workbook.py#L126): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 126:29](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/workbook.py#L126): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 126:44](https://github.com/eastgenomics/eris/blob/3d9277d475d13cb407a2667b23365a3d720c0c22/variant_db/management/commands/workbo [...]

2024-02-21 12:27 UTC, corbin-chris requested changes
> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 8 unresolved discussions (waiting on @spaul91)

___
*[`tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAZGKi70dVC_w2JTPb:-NrAZGKi70dVC_w2JTPc:b-1uttzn) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/tests/test_variant_db/test_management/test_commands/test_inserts/test_insert_into_table.py#L105)):*
> ```Python
>         Insert a row of valid `Chromosome` data to be referenced
>         """
>         _, _ = Chromosome.objects.get_or_create(
> ```

Suggestion rather than 'must do' - sometimes it's handy to assign your set-up data to an object like so:
self.chrom, _ = Chromosome.objects.get_or_create(

Then later on instead of comparing to a string:
assert query_result.name = "1"

You can compare to the retained object:
assert query_result.name == self.chrom.name

This is handy if you want to change your set-up data in future, for whatever reason
___
*[`variant_db/models.py` line 151 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYePt9U0xYDTgJWpb:-NrAYePt9U0xYDTgJWpc:b-wu96gq) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L151)):*
> ```Python
> 
>     source = models.TextField(
>         verbose_name="chromosome source (i.e. RefSeq, Assembly, Genbank etc.)"  # automatic
> ```

Sorry, what do you mean by automatic here?
___
*[`variant_db/models.py` line 257 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYrCxBCRfsU7PPLuW:-NrAYrCxBCRfsU7PPLuX:byvhnq9) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L257)):*
> ```Python
>     """
>     The name of the Institution where the interpretation was carried out
>     Generally smaller than an Organization. For example, a hospital which is part of a GLH would be an Institution.
> ```

I think I wrote this (and the Organization description too) - could you please double-check they aren't the wrong way around, as stuff has changed since I worked on this?
___
*[`variant_db/management/commands/insert.py` line 174 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAXONF3dufbEVc-Vzu:-NrAXONF3dufbEVc-Vzv:bn76mys) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L174)):*
> ```Python
>         _get_or_create(
>             Panel,
>             method="GET",
> ```

String comparison is case-sensitive - you assert in ("get", "create") in _get_or_create. Correct the case and/or convert everything to lower within _get_or_create. 
___
*[`variant_db/management/commands/insert.py` line 248 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAUxFX6-_Jrz16TMAj:-NrAUxFX6-_Jrz16TMAk:b-u8hb32) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L248)):*
> ```Python
> 
> @store_bools
> def _get_or_create(
> ```

Please name this helper function something other than _get_or_create. There's a Django 'get_or_create' so it's confusing.

I also considered asking you to split this into two functions for readability, even though 'names_to' would then be repeated. But I've changed my mind as perhaps having this all be one function would be more future-proof: if we ever move towards using config files, you'd be able to store an expected column alongside its relevant table and whether it should be 'insert' or 'get'.
___
*[`variant_db/management/commands/insert.py` line 254 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAWb6N4taZYwzTLkNJ:-NrAWb6N4taZYwzTLkNK:b-4lkypc) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L254)):*
> ```Python
>     Inserts a row of data into a table, given the model
> 
>     :param: model_class: The model class to insert data into
> ```

Please add a :param: line for method too
___
*[`variant_db/management/commands/insert.py` line 259 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAX4W_7Crt4PvtjSrJ:-NrAX4W_7Crt4PvtjSrK:bw9toy7) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L259)):*
> ```Python
>     :kwargs: named arguments to pass in to model for import
>     """
>     assert method in ("get", "insert")
> ```

I've seen you pass upper-case GET to _get_or_create elsewhere in the code
Maybe convert everything to lower first to make it less-likely to snag on something like that:



_Code snippet:_
```Python
assert method.lower() in ("get", "insert")
```
___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrA_LPb2X21P1rhsz7u:b-u3aj0h) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
> ```Python
>     """
>     assert re.match(
>         string=panel, pattern=r"^.+_[\d](\.[\d]){1,}"
> ```

Do you have unit tests specifically to cover 'realistic-looking' potential panel names?
You have a lot with random words but you might want test that this works on e.g.
"A realistic panel name_3.2"
And works (or fails out if you expect that for older panel naming conventions) on:
"A realistic panel name_SG_panel_3.2"


<!-- Sent from Reviewable.io -->

2024-02-21 12:37 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 174 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAXONF3dufbEVc-Vzu:-NrAehs9AWTklQrfgxKi:b-yoa6pd) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L174)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

String comparison is case-sensitive - you assert in ("get", "create") in _get_or_create. Correct the case and/or convert everything to lower within _get_or_create.
</blockquote></details>

That was a typo, good catch thanks


<!-- Sent from Reviewable.io -->

2024-02-21 12:37 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 248 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAUxFX6-_Jrz16TMAj:-NrAesEJ1Chck87fKaTJ:b-yltzfr) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L248)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please name this helper function something other than _get_or_create. There's a Django 'get_or_create' so it's confusing.

I also considered asking you to split this into two functions for readability, even though 'names_to' would then be repeated. But I've changed my mind as perhaps having this all be one function would be more future-proof: if we ever move towards using config files, you'd be able to store an expected column alongside its relevant table and whether it should be 'insert' or 'get'.
</blockquote></details>

Isn't this the whole point of namespaces? Please suggest a name if you'd like it to be changed


<!-- Sent from Reviewable.io -->

2024-02-21 12:38 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 259 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAX4W_7Crt4PvtjSrJ:-NrAf3tA1xkR_mvWs0ps:b-r3lnhm) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L259)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I've seen you pass upper-case GET to _get_or_create elsewhere in the code
Maybe convert everything to lower first to make it less-likely to snag on something like that:
</blockquote></details>

CTRL+R time


<!-- Sent from Reviewable.io -->

2024-02-21 12:38 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrAf8e2Eo1lMcPfAprk:b-5znu4) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Do you have unit tests specifically to cover 'realistic-looking' potential panel names?
You have a lot with random words but you might want test that this works on e.g.
"A realistic panel name_3.2"
And works (or fails out if you expect that for older panel naming conventions) on:
"A realistic panel name_SG_panel_3.2"
</blockquote></details>

I don't have any panel names that come to mind. Please suggest some


<!-- Sent from Reviewable.io -->

2024-02-21 12:49 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 174 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAXONF3dufbEVc-Vzu:-NrAhiJ_4uFUsgg1dLel:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L174)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

That was a typo, good catch thanks
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-21 12:49 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 259 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAX4W_7Crt4PvtjSrJ:-NrAhm_i5WGsh_C6X6vk:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L259)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

CTRL+R time
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-22 09:51 UTC, corbin-chris requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/models.py` line 151 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYePt9U0xYDTgJWpb:-NrFB_P0D4xrxWYNU2e-:b-pyppu7) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L151)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Probably not a good thing to call it. It's pre-populated, I mean
</blockquote></details>

Do you mean they arrive already-populated from the workbook-parser? Or do you mean that they fill from fixtures files? If yes, please put words to that effect instead of 'automatic'. 
When writing docstrings, I try to keep in mind that my audience is a new-to-the-GLH coder who has been put on v5 of this code, years from now, possibly after some staff change teams or leave.
___
*[`variant_db/models.py` line 257 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYrCxBCRfsU7PPLuW:-NrFAmsjD8mQTAEu_Wi5:b-vghsuo) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L257)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

What's changed?
</blockquote></details>

Win's workbook has changed lots in the last few weeks. We get Organization and Institution from her (see snippet) and I believe she hard-codes them right now. Please check that her understanding of what an Institution and Organization are, match what I wrote in the docstrings, and change them if not.



_Code snippet:_
```Python
organisation = _insert_into_table(
        Organization,
        names_to={"organisation": "name"},
        **_subset_row(row_dict, "organisation"),
    )
```
___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrFDFSG7qXOLZl78LxK:b-o2l6cu) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I don't have any panel names that come to mind. Please suggest some
</blockquote></details>

Lucky you, they're publicly available: https://nhsgms-panelapp.genomicsengland.co.uk/panels 
Spaces, dashes and brackets may occur. Maybe some other characters too.


<!-- Sent from Reviewable.io -->

2024-02-22 12:35 UTC, corbin-chris reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 5 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/management/commands/insert.py` line 248 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAUxFX6-_Jrz16TMAj:-NrFnwFTEGGn8QcsOb3P:b-qj28sf) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L248)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Isn't this the whole point of namespaces? Please suggest a name if you'd like it to be changed
</blockquote></details>

Done I'll let this slide, but if it confuses people in the future I'll change it. 


<!-- Sent from Reviewable.io -->

2024-02-22 12:46 UTC, spaul91 commented
*[`variant_db/models.py` line 257 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYrCxBCRfsU7PPLuW:-NrFq_fTAIUQuqL_EWWq:bv6kv02) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L257)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Win's workbook has changed lots in the last few weeks. We get Organization and Institution from her (see snippet) and I believe she hard-codes them right now. Please check that her understanding of what an Institution and Organization are, match what I wrote in the docstrings, and change them if not.
</blockquote></details>

I've just asked in Slack, but seems ok to me currently...


<!-- Sent from Reviewable.io -->

2024-02-22 12:49 UTC, spaul91 commented
*[`variant_db/management/commands/insert.py` line 254 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAWb6N4taZYwzTLkNJ:-NrFrG3yCWbzMNRh1Am5:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/insert.py#L254)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please add a :param: line for method too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 14:59 UTC, jethror1 approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-Nrf0ceG3LbTxZ6m-GBn:b-n6qoix) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

A couple of things:

1 - I honestly don't see the issue with using names you're not going to see (even if they seem abstract), as long as they conform to the format you expect. `pepperoni_pizza_1.0` isn't testing our ability to determine what a panel is, it's testing that we can accept strings that follow the `<string_data>_<numeric_data>` format, and given that's the format we need panels in, I'd say it's a perfectly acceptable test as things stand. Your example (realisticpanelname_SG_panel_3.2) would pass this test too.
2 - I think it's fair of me to ask you to provide me with examples, given that you're the one who's asking me to change the test (that I still don't fully agree with - see point 1), and to prevent us going around in circles with this PR if I pick the "wrong" panel, for whatever reason. I'd appreciate your help, since you know more about how panels are formatted than I do.
</blockquote></details>

I agree that some sub tests with 'real world' examples with some malformed ones might be a good idea to try catch edge cases and ensure you actually raise your AssertionError when you expect to (especially when having regex patterns to sense check you catch things like). 

Using the genepanels file (since this has all the current panel names I think), we can get any that look "weird" (i.e. non alphanumeric, removing common characters such as underscores etc):

```
$ panels=$(dx cat file-GVx0vkQ433Gvq63k1Kj4Y562 | cut -f2 | sort | uniq)

$ echo "$panels" | grep -Pwv '^[A-Za-z0-9\.\_\-\s]+$' | grep -v "^HGNC"
Adult onset dystonia, chorea or related movement disorder_3.0
Childhood onset dystonia, chorea or related movement disorder_3.0
Familial chylomicronaemia syndrome (FCS)_3.0
Familial hypercholesterolaemia (GMS)_2.0
Hypogonadotropic hypogonadism (GMS)_3.0
Inherited MMR deficiency (Lynch syndrome)_1.2
Inherited ovarian cancer (without breast cancer)_4.0
Inherited predisposition to acute myeloid leukaemia (AML)_3.0
Mitochondrial liver disease, including transient infantile liver failure_1.9
Pyruvate dehydrogenase (PDH) deficiency_1.2
Thoracic aortic aneurysm or dissection (GMS)_3.0
```

and for a bonus, here's all the non alphanumeric characters in that file (for now, until the fancy putting in weird symbols):
```
$ echo "$panels" | sed 's/[a-zA-Z0-9]//g' | grep -o . | sort | uniq
(
)
,
-
.
:
_
```

Some examples based off real test names you might want to try test out might be things like if they add a bonus minor version (`Thrombocythaemia_1.1.1`),  if they add something after (`Thrombocythaemia_1.1.1_v2`) if they chuck some other numbers in the panel name (`Stickler 2 syndrome_1.2.3`), missing underscore ('Structural eye disease-3.0'). 

Given your regex above, here's what an inverse match leaves you with:
```
$ echo "$panels" | grep -Pwv "^.+_[\d](\.[\d]){1,}"
Cerebral malformation_10.1
Childhood onset leukodystrophy_14.2
Hereditary ataxia and cerebellar anomalies - childhood onset_12.1
Hereditary systemic amyloidosis_1.18
HGNC:1100_SG_panel
HGNC:1101_SG_panel
HGNC:16627_SG_panel
HGNC:26144_SG_panel
HGNC:795_SG_panel
HGNC:9820_SG_panel
HGNC:9823_SG_panel
Hypotonic infant_25.1
Other rare neuromuscular disorders_19.1
Paediatric disorders_35.2
Polycystic liver disease_1.26
Sudden unexplained death or survivors of a cardiac event_19.6
```

So it does look like panel versions > 10.x will not pass your assertion, is that what you would expect?


<!-- Sent from Reviewable.io -->

2024-02-27 14:59 UTC, jethror1 requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-27 15:13 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-Nrf6PPjDa6gVxBtWzi8:b-nfpwsg) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I agree that some sub tests with 'real world' examples with some malformed ones might be a good idea to try catch edge cases and ensure you actually raise your AssertionError when you expect to (especially when having regex patterns to sense check you catch things like). 

Using the genepanels file (since this has all the current panel names I think), we can get any that look "weird" (i.e. non alphanumeric, removing common characters such as underscores etc):

```
$ panels=$(dx cat file-GVx0vkQ433Gvq63k1Kj4Y562 | cut -f2 | sort | uniq)

$ echo "$panels" | grep -Pwv '^[A-Za-z0-9\.\_\-\s]+$' | grep -v "^HGNC"
Adult onset dystonia, chorea or related movement disorder_3.0
Childhood onset dystonia, chorea or related movement disorder_3.0
Familial chylomicronaemia syndrome (FCS)_3.0
Familial hypercholesterolaemia (GMS)_2.0
Hypogonadotropic hypogonadism (GMS)_3.0
Inherited MMR deficiency (Lynch syndrome)_1.2
Inherited ovarian cancer (without breast cancer)_4.0
Inherited predisposition to acute myeloid leukaemia (AML)_3.0
Mitochondrial liver disease, including transient infantile liver failure_1.9
Pyruvate dehydrogenase (PDH) deficiency_1.2
Thoracic aortic aneurysm or dissection (GMS)_3.0
```

and for a bonus, here's all the non alphanumeric characters in that file (for now, until the fancy putting in weird symbols):
```
$ echo "$panels" | sed 's/[a-zA-Z0-9]//g' | grep -o . | sort | uniq
(
)
,
-
.
:
_
```

Some examples based off real test names you might want to try test out might be things like if they add a bonus minor version (`Thrombocythaemia_1.1.1`),  if they add something after (`Thrombocythaemia_1.1.1_v2`) if they chuck some other numbers in the panel name (`Stickler 2 syndrome_1.2.3`), missing underscore ('Structural eye disease-3.0'). 

Given your regex above, here's what an inverse match leaves you with:
```
$ echo "$panels" | grep -Pwv "^.+_[\d](\.[\d]){1,}"
Cerebral malformation_10.1
Childhood onset leukodystrophy_14.2
Hereditary ataxia and cerebellar anomalies - childhood onset_12.1
Hereditary systemic amyloidosis_1.18
HGNC:1100_SG_panel
HGNC:1101_SG_panel
HGNC:16627_SG_panel
HGNC:26144_SG_panel
HGNC:795_SG_panel
HGNC:9820_SG_panel
HGNC:9823_SG_panel
Hypotonic infant_25.1
Other rare neuromuscular disorders_19.1
Paediatric disorders_35.2
Polycystic liver disease_1.26
Sudden unexplained death or survivors of a cardiac event_19.6
```

So it does look like panel versions > 10.x will not pass your assertion, is that what you would expect?
</blockquote></details>

also this is an ideal scenario for using subtests, I'd consider having a test of valid panel names you would expect to pass, and a set of ones you would expect to raise an AssertionError and test they get caught, then its easy to add a load of example ones in.  You could even just store all the current valid panel names in a file in your test data, and use that with your test of valid names, then you know you've tested it on all panel names.

docs on subtests if you've not looked at them before: https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests


<!-- Sent from Reviewable.io -->

2024-02-28 09:39 UTC, corbin-chris reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 2 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/models.py` line 257 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYrCxBCRfsU7PPLuW:-NrGZqKE6Dm6HFSFDXnk:b-nq3y44) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L257)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I've just asked in Slack, but seems ok to me currently...
</blockquote></details>

I think that ID column is coming soon - we can make that be a new PR if wanted.


<!-- Sent from Reviewable.io -->

2024-02-28 10:02 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-Nrj2lKJ7wBtH3EJeGUA:b-1n40li) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

also this is an ideal scenario for using subtests, I'd consider having a test of valid panel names you would expect to pass, and a set of ones you would expect to raise an AssertionError and test they get caught, then its easy to add a load of example ones in.  You could even just store all the current valid panel names in a file in your test data, and use that with your test of valid names, then you know you've tested it on all panel names.

docs on subtests if you've not looked at them before: https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests
</blockquote></details>

Thank you Jethro, this has clarified a lot for me. Panel parsing is a much trickier subject than we (I) gave it credit for initially, and I (still) don't know what the exact requirements for it are, other than to store the first and last fields of each panel into <name> and <version>, using underscores as the split character. The regex isn't there to parse the panels, but to make sure they conform to the `<stuff>_<version>` format, so the script will break if it runs into the odd edge cases you mention (like the `panel-v3.0` example). That'll give us a chance to ~~cry~~ fix any problems with the panel and resubmit.

That said, you've raised a number of problems with the regex I've implemented which I'm only noticing now (like versions >v10), so thank you for that - I'll go work on it, I think I have something provisionally that satisfies everything in the panels file now, at least:

```
echo "$panels" | grep -Pwv '^.+_v?(\d+\.?)+$' | cut -f2 | sort | uniq

HGNC:1100_SG_panel
HGNC:1101_SG_panel
HGNC:16627_SG_panel
HGNC:26144_SG_panel
HGNC:795_SG_panel
HGNC:9820_SG_panel
HGNC:9823_SG_panel
```

I'm guessing we'll want to ignore these?

Reformatting panels to make sure they conform to the interface really feels like it should be a responsibility of the parsing script upstream, not variant DB...


<!-- Sent from Reviewable.io -->

2024-02-28 10:13 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrjBRIbEVahr3h6G4G3:bqqu09a) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Thank you Jethro, this has clarified a lot for me. Panel parsing is a much trickier subject than we (I) gave it credit for initially, and I (still) don't know what the exact requirements for it are, other than to store the first and last fields of each panel into <name> and <version>, using underscores as the split character. The regex isn't there to parse the panels, but to make sure they conform to the `<stuff>_<version>` format, so the script will break if it runs into the odd edge cases you mention (like the `panel-v3.0` example). That'll give us a chance to ~~cry~~ fix any problems with the panel and resubmit.

That said, you've raised a number of problems with the regex I've implemented which I'm only noticing now (like versions >v10), so thank you for that - I'll go work on it, I think I have something provisionally that satisfies everything in the panels file now, at least:

```
echo "$panels" | grep -Pwv '^.+_v?(\d+\.?)+$' | cut -f2 | sort | uniq

HGNC:1100_SG_panel
HGNC:1101_SG_panel
HGNC:16627_SG_panel
HGNC:26144_SG_panel
HGNC:795_SG_panel
HGNC:9820_SG_panel
HGNC:9823_SG_panel
```

I'm guessing we'll want to ignore these?

Reformatting panels to make sure they conform to the interface really feels like it should be a responsibility of the parsing script upstream, not variant DB...
</blockquote></details>

Just reimplemented the regex. The script breaks if versionless SG panels are present which I think is ok? The problem is that the parsing behaviour (take first and last fields, which is what I was told to do) would trip up with these:

```
 'CUH_Inherited Stroke_1.0',
 'CUH_INSR_1.0',
```

It'd store the panel name as CUH v1.0, which doesn't sound right.

Why are we splitting on underscores again? Just so we can exclude the `SG` token?


<!-- Sent from Reviewable.io -->

2024-02-28 10:17 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrjCe-_5Ljhgqy-Xt49:b-hx03jj) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Just reimplemented the regex. The script breaks if versionless SG panels are present which I think is ok? The problem is that the parsing behaviour (take first and last fields, which is what I was told to do) would trip up with these:

```
 'CUH_Inherited Stroke_1.0',
 'CUH_INSR_1.0',
```

It'd store the panel name as CUH v1.0, which doesn't sound right.

Why are we splitting on underscores again? Just so we can exclude the `SG` token?
</blockquote></details>

Sorry, splitting on underscores is correct. It's the storage of field 1 (exclusively) as <panel name> that's causing the issue here


<!-- Sent from Reviewable.io -->

2024-02-28 16:13 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrkRfkRBcm-SSp3UhH0:b-tr4wxd) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
SG panels - these I _think_ aren't an issue in Eris.

To handle major version of panel >9 I think you want a `+` after your initial `_[\d]`: `^.+_[\d]+(\.[\d]){1,}$` (i.e. to match `_12.1`)

Also note that I think you want to add a trailing `$` to ensure `re.match` matches the full string, else something like this will pass:
```
>>> s="CUH_Inherited Stroke_1.0foo"
>>> assert re.match(r'^.+_[\d]+(\.[\d]){1,}', s)
>>> panel, version = s.rsplit('_', 1)
>>> panel
'CUH_Inherited Stroke'
>>> version
'1.0foo'
```

where as with the `$` you correctly get an AssertionError (or in Python land you can do `re.fullmatch` to not need to remember if you're wanting to match the full string and not a potential substring):
```
>>> assert re.match(r'^.+_[\d]+(\.[\d]){1,}$', s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

>>> assert re.fullmatch(r'.+_[\d]+(\.[\d]){1,}', s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

To handle the splitting where there's more than one underscore, `rsplit` should sort this after you've validated with regex:
```
>>> s="CUH_Inherited Stroke_1.0"
>>> panel, version = s.rsplit('_', 1)
>>> panel
'CUH_Inherited Stroke'
>>> version
'1.0'
```

Does this answer all your issues?


<!-- Sent from Reviewable.io -->

2024-02-28 16:52 UTC, jethror1 approved these changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @spaul91)

___
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-NrkcFy76Ve7EmlrfESH:bun4jdv) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

That's great, thank you. I'd already reworked the regex to `^.+_v?(\d+\.?)+$`, which can generalise to any format of version it finds:

```
In [1]: import re

In [2]: pattern = re.compile("^.+_v?(\d+\.?)+$")

In [3]: re.match(pattern, "CUH_Inherited stroke_1.0") or print("
   ...: sorry, nothing")
Out[3]: <re.Match object; span=(0, 24), match='CUH_Inherited stroke_1.0'>

In [4]: re.match(pattern, "CUH_Inherited stroke_v1.15.3.12") or
   ...: print("sorry, nothing")
Out[4]: <re.Match object; span=(0, 31), match='CUH_Inherited stroke_v1.15.3.12'>

In [5]: re.match(pattern, "CUH_Inherited stroke_v1.0foo") or pri
   ...: nt("sorry, nothing")
sorry, nothing

In [6]: re.match(pattern, "CUH_Inherited stroke_v2") or print("s
   ...: orry, nothing")
Out[6]: <re.Match object; span=(0, 23), match='CUH_Inherited stroke_v2'>

In [7]: re.match(pattern, "CUH_Inherited stroke_") or print("sor
   ...: ry, nothing")
sorry, nothing
```

`rsplit` is a really useful suggestion too, thank you :) will implement
</blockquote></details>

ahh I don't think reviewable refreshed with changes then :sadpanda:


<!-- Sent from Reviewable.io -->

2024-02-28 17:03 UTC, spaul91 commented
*[`variant_db/management/commands/workbook.py` line 128 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrA_LPb2X21P1rhsz7t:-Nrke_5o2IY1-Sjn7Tv3:bvaqf8p) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/management/commands/workbook.py#L128)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

ahh I don't think reviewable refreshed with changes then :sadpanda:
</blockquote></details>

I didn't push the changes sorry. Changes implemented and pushed now!


<!-- Sent from Reviewable.io -->

2024-02-28 17:04 UTC, spaul91 commented
*[`variant_db/models.py` line 257 at r2](https://reviewable.io/reviews/eastgenomics/eris/93#-NrAYrCxBCRfsU7PPLuW:-Nrkf7I682XDuOEnttVa:b-yzela8) ([raw file](https://github.com/eastgenomics/eris/blob/d40673b5b4a9058fcaf83eedba5e2dbec205ccb3/variant_db/models.py#L257)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I think that ID column is coming soon - we can make that be a new PR if wanted.
</blockquote></details>

I like that idea. Closing


<!-- Sent from Reviewable.io -->

2024-02-28 17:07 UTC, jethror1 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-28 17:15 UTC, corbin-chris approved these changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/93)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2024-02-28 17:15 UTC, merged