In 470 unit test utils
eastgenomics/eris pull request #95
Opened 2024-02-26 16:16 UTC by corbin-chris

Added unit tests for the 3 functions in utils.py
I also made some slight changes to normalize_version, which was stripping right-hand zeroes during a float conversion step. This was turning valid panel versions such as 5.10 into 5.1, which would have been confusing when displayed to users.

Ran 159 tests in 5.209s

OK
Destroying test database for alias 'default'...

2024-02-26 16:16 UTC, pep8speaks commented
Hello @corbin-chris! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`tests/test_panels_backend/test_management/test_commands/test_utils/test_parse_excluded_hgncs_from_file.py`](https://github.com/eastgenomics/eris/blob/be1045539e4293bd6b5787eace677416e60cd9b3/tests/test_panels_backend/test_management/test_commands/test_utils/test_parse_excluded_hgncs_from_file.py):

> [Line 32:80](https://github.com/eastgenomics/eris/blob/be1045539e4293bd6b5787eace677416e60cd9b3/tests/test_panels_backend/test_management/test_commands/test_utils/test_parse_excluded_hgncs_from_file.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 79 characters)
> [Line 35:80](https://github.com/eastgenomics/eris/blob/be1045539e4293bd6b5787eace677416e60cd9b3/tests/test_panels_backend/test_management/test_commands/test_utils/test_parse_excluded_hgncs_from_file.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)

2024-02-27 09:16 UTC, JasonLing95 requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/95)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/utils.py` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eris/95#-NrdpsMiATLY7-Ukl9pi:-NrdpsMj04m5ANWubqNA:bjcksl1) ([raw file](https://github.com/eastgenomics/eris/blob/6f127a7a93e0d41f0fbe52aaf4721bf77a1a2c41/panels_backend/management/commands/utils.py#L13)):*
> ```Python
> 
> 
> def normalize_version(padded_version: str) -> str | float:
> ```

this function return a string
___
*[`panels_backend/management/commands/utils.py` line 20 at r2](https://reviewable.io/reviews/eastgenomics/eris/95#-NrdpwCe8NqeH73tbuQC:-NrdpwCe8NqeH73tbuQD:bb89xm) ([raw file](https://github.com/eastgenomics/eris/blob/6f127a7a93e0d41f0fbe52aaf4721bf77a1a2c41/panels_backend/management/commands/utils.py#L20)):*
> ```Python
>     """
>     if not padded_version:
>         return 0.0
> ```

let's make this consistent and return a string "0.0" a


<!-- Sent from Reviewable.io -->

2024-02-27 09:35 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/95)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/utils.py` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eris/95#-NrdpsMiATLY7-Ukl9pi:-NrduaqQ1PbMAkliC1Hj:b-z1v0qu) ([raw file](https://github.com/eastgenomics/eris/blob/6f127a7a93e0d41f0fbe52aaf4721bf77a1a2c41/panels_backend/management/commands/utils.py#L13)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this function return a string
</blockquote></details>

Done now that it returns "0.0" not float(0.0)
___
*[`panels_backend/management/commands/utils.py` line 20 at r2](https://reviewable.io/reviews/eastgenomics/eris/95#-NrdpwCe8NqeH73tbuQC:-NrdufNXE_P944TP8l4y:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/6f127a7a93e0d41f0fbe52aaf4721bf77a1a2c41/panels_backend/management/commands/utils.py#L20)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

let's make this consistent and return a string "0.0" a
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 09:44 UTC, JasonLing95 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/95)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)



<!-- Sent from Reviewable.io -->

2024-02-27 09:44 UTC, merged